variablesConf: charmed_wjets_ds

samplesConf: powheg_truth

data: Data

channels:
  2018_el_wplusd_OS:
    samples:
      - Wjets_emu_Matched | 2018_l_wplusd_OS_Matched
      - Wjets_emu_Rest | 2018_l_wplusd_OS_Rest
      - Top_Matched | 2018_l_wplusd_OS_Matched
      - Top_Rest | 2018_l_wplusd_OS_Rest
      - Wjets_emu_NoMatch | 2018_l_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_Ds_OS
      - 2018_mu_SR_Ds_OS
    label:
      - "W#rightarrowl#nu+D, D#rightarrowKK#pi, OS"
      - "Powheg"
    lumi: "2018"
    save_to_file: True

  2018_el_wplusd_SS:
    samples:
      - Wjets_emu_Matched | 2018_l_wplusd_SS_Matched
      - Wjets_emu_Rest | 2018_l_wplusd_SS_Rest
      - Top_Matched | 2018_l_wplusd_SS_Matched
      - Top_Rest | 2018_l_wplusd_SS_Rest
      - Wjets_emu_NoMatch | 2018_l_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_Ds_SS
      - 2018_mu_SR_Ds_SS
    label:
      - "W#rightarrowl#nu+D, D#rightarrowKK#pi, SS"
      - "Powheg"
    lumi: "2018"
    save_to_file: True

  2018_el_wplusd_OS-SS:
    samples:
      - Wjets_emu_Matched | 2018_l_wplusd_OS-SS_Matched
      - Wjets_emu_Rest | 2018_l_wplusd_OS-SS_Rest
      - Top_Matched | 2018_l_wplusd_OS-SS_Matched
      - Top_Rest | 2018_l_wplusd_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_l_wplusd_OS-SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_Ds_OS
      - 2018_mu_SR_Ds_OS
      - -2018_el_SR_Ds_SS
      - -2018_mu_SR_Ds_SS
    label:
      - "W#rightarrowl#nu+D, D#rightarrowKK#pi, OS-SS"
      - "Powheg"
    lumi: "2018"
    save_to_file: True

  2018_l_wplusd_OS_Matched:
    regions:
      - 2018_el_SR_Ds_OS_Matched
      - 2018_mu_SR_Ds_OS_Matched
    make_plots: False

  2018_l_wplusd_SS_Matched:
    regions:
      - 2018_el_SR_Ds_SS_Matched
      - 2018_mu_SR_Ds_SS_Matched
    make_plots: False

  2018_l_wplusd_OS-SS_Matched:
    regions:
      - 2018_el_SR_Ds_OS_Matched
      - 2018_mu_SR_Ds_OS_Matched
      - -2018_el_SR_Ds_SS_Matched
      - -2018_mu_SR_Ds_SS_Matched
    make_plots: False

  2018_l_wplusd_OS_NoMatch:
    regions:
      - 2018_el_SR_Ds_OS_Other
      - 2018_mu_SR_Ds_OS_Other
    make_plots: False

  2018_l_wplusd_SS_NoMatch:
    regions:
      - 2018_el_SR_Ds_SS_Other
      - 2018_mu_SR_Ds_SS_Other
    make_plots: False

  2018_l_wplusd_OS-SS_NoMatch:
    regions:
      - 2018_el_SR_Ds_OS_Other
      - 2018_mu_SR_Ds_OS_Other
      - -2018_el_SR_Ds_SS_Other
      - -2018_mu_SR_Ds_SS_Other
    make_plots: False

  2018_l_wplusd_OS_Rest:
    regions:
      - 2018_el_SR_Ds_OS
      - 2018_mu_SR_Ds_OS
      - -2018_el_SR_Ds_OS_Matched
      - -2018_mu_SR_Ds_OS_Matched
      - -2018_el_SR_Ds_OS_Other
      - -2018_mu_SR_Ds_OS_Other
    make_plots: False

  2018_l_wplusd_SS_Rest:
    regions:
      - 2018_el_SR_Ds_SS
      - 2018_mu_SR_Ds_SS
      - -2018_el_SR_Ds_SS_Matched
      - -2018_mu_SR_Ds_SS_Matched
      - -2018_el_SR_Ds_SS_Other
      - -2018_mu_SR_Ds_SS_Other
    make_plots: False

  2018_l_wplusd_OS-SS_Rest:
    regions:
      - 2018_el_SR_Ds_OS
      - 2018_mu_SR_Ds_OS
      - -2018_el_SR_Ds_OS_Matched
      - -2018_mu_SR_Ds_OS_Matched
      - -2018_el_SR_Ds_OS_Other
      - -2018_mu_SR_Ds_OS_Other
      - -2018_el_SR_Ds_SS
      - -2018_mu_SR_Ds_SS
      - 2018_el_SR_Ds_SS_Matched
      - 2018_mu_SR_Ds_SS_Matched
      - 2018_el_SR_Ds_SS_Other
      - 2018_mu_SR_Ds_SS_Other
    make_plots: False