variablesConf: charmed_wjets_dstar

samplesConf: madgraph_truth

data: Data

channels:
  2018_el_SR_DstarKPiPi0_OS:
    samples:
      - Wjets_emu_Matched | 2018_l_wplusdPi0_OS_Matched
      - Wjets_emu_Rest | 2018_l_wplusdPi0_OS_Rest
      - Top_Matched | 2018_l_wplusdPi0_OS_Matched
      - Top_Rest | 2018_l_wplusdPi0_OS_Rest
      - Wjets_emu_NoMatch | 2018_l_wplusdPi0_OS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_DstarKPiPi0_OS
#       - 2018_mu_SR_DstarKPiPi0_OS
    label:
      - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS"
      - "MadGraph Truth"
    lumi: "2018"
    save_to_file: True

  2018_l_wplusdPi0_OS_Matched:
   regions:
     - 2018_el_SR_DstarKPiPi0_OS_Matched
#      - 2018_mu_SR_DstarKPiPi0_OS_Matched
   make_plots: False

  2018_l_wplusdPi0_OS_Rest:
   regions:
     - 2018_el_SR_DstarKPiPi0_OS_Other
#      - 2018_mu_SR_DstarKPiPi0_OS_Other
   make_plots: False

  2018_l_wplusdPi0_OS_NoMatch:
   regions:
     - 2018_el_SR_DstarKPiPi0_OS_MisMatched
#      - 2018_mu_SR_DstarKPiPi0_OS_MisMatched
   make_plots: False
#############################   
  2018_el_SR_DstarKPiPi0_SS:
    samples:
      - Wjets_emu_Matched | 2018_l_wplusdPi0_SS_Matched
      - Wjets_emu_Rest | 2018_l_wplusdPi0_SS_Rest
      - Top_Matched | 2018_l_wplusdPi0_SS_Matched
      - Top_Rest | 2018_l_wplusdPi0_SS_Rest
      - Wjets_emu_NoMatch | 2018_l_wplusdPi0_SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_DstarKPiPi0_SS
#       - 2018_mu_SR_DstarKPiPi0_OS
    label:
      - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, SS"
      - "MadGraph Truth"
    lumi: "2018"
    save_to_file: True

  2018_l_wplusdPi0_SS_Matched:
   regions:
     - 2018_el_SR_DstarKPiPi0_SS_Matched
#      - 2018_mu_SR_DstarKPiPi0_SS_Matched
   make_plots: False

  2018_l_wplusdPi0_SS_Rest:
   regions:
     - 2018_el_SR_DstarKPiPi0_SS_Other
#      - 2018_mu_SR_DstarKPiPi0_OS_Other
   make_plots: False

  2018_l_wplusdPi0_SS_NoMatch:
   regions:
     - 2018_el_SR_DstarKPiPi0_SS_MisMatched
#      - 2018_mu_SR_DstarKPiPi0_OS_MisMatched
   make_plots: False
   
#######################################################
  2018_el_SR_DstarKPiPi0_OS-SS:
    samples:
      - Wjets_emu_Matched | 2018_l_wplusdPi0_OS-SS_Matched
      - Wjets_emu_Rest | 2018_l_wplusdPi0_OS-SS_Rest
      - Top_Matched | 2018_l_wplusdPi0_OS-SS_Matched
      - Top_Rest | 2018_l_wplusdPi0_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_l_wplusdPi0_OS-SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_DstarKPiPi0_OS
      - -2018_el_SR_DstarKPiPi0_SS
#       - 2018_mu_SR_DstarKPiPi0_OS
    label:
      - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS-SS"
      - "MadGraph Truth"
    lumi: "2018"
    save_to_file: True

  2018_l_wplusdPi0_OS-SS_Matched:
   regions:
     - 2018_el_SR_DstarKPiPi0_OS_Matched
     - -2018_el_SR_DstarKPiPi0_SS_Matched
#      - 2018_mu_SR_DstarKPiPi0_SS_Matched
   make_plots: False

  2018_l_wplusdPi0_OS-SS_Rest:
   regions:
     - 2018_el_SR_DstarKPiPi0_OS_Other
     - -2018_el_SR_DstarKPiPi0_SS_Other
#      - 2018_mu_SR_DstarKPiPi0_OS_Other
   make_plots: False

  2018_l_wplusdPi0_OS-SS_NoMatch:
   regions:
     - 2018_el_SR_DstarKPiPi0_OS_MisMatched
     - -2018_el_SR_DstarKPiPi0_SS_MisMatched
#      - 2018_mu_SR_DstarKPiPi0_OS_MisMatched
   make_plots: False
    
#   2018_el_wplusd_SS:
#     samples:
#       - Wjets_emu_Matched | 2018_el_wplusd_SS_Matched
#       - Wjets_emu_Rest | 2018_el_wplusd_SS_Rest
#       - Top_Matched | 2018_el_wplusd_SS_Matched
#       - Top_Rest | 2018_el_wplusd_SS_Rest
#       - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch
#       - Other
#       - Zjets_emu
#     regions:
#       - SS_2018_el_SR_DstarKPiPi0
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, SS"
#       - "MadGraph"
#     lumi: "2018"
# #     save_to_file: True

#   2018_el_wplusd_OS-SS:
#     samples:
#       - Wjets_emu_Matched | 2018_el_wplusd_OS-SS_Matched
#       - Wjets_emu_Rest | 2018_el_wplusd_OS-SS_Rest
#       - Top_Matched | 2018_el_wplusd_OS-SS_Matched
#       - Top_Rest | 2018_el_wplusd_OS-SS_Rest
#       - Wjets_emu_NoMatch | 2018_el_wplusd_OS-SS_NoMatch
#       - Other
#       - Zjets_emu
#     regions:
#       - OS_2018_el_SR_DstarKPiPi0
#       - -SS_2018_el_SR_DstarKPiPi0
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS-SS"
#       - "MadGraph"
#     lumi: "2018"
# #     save_to_file: True

#   2018_mu_wplusd_OS:
#     samples:
#       - Wjets_emu_Matched | 2018_mu_wplusd_OS_Matched
#       - Wjets_emu_Rest | 2018_mu_wplusd_OS_Rest
#       - Top_Matched | 2018_mu_wplusd_OS_Matched
#       - Top_Rest | 2018_mu_wplusd_OS_Rest
#       - Wjets_emu_NoMatch | 2018_mu_wplusd_OS_NoMatch
#       - Other
#       - Zjets_emu
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS"
#       - "MadGraph"
#     lumi: "2018"
# #     save_to_file: True

#   2018_mu_wplusd_SS:
#     samples:
#       - Wjets_emu_Matched | 2018_mu_wplusd_SS_Matched
#       - Wjets_emu_Rest | 2018_mu_wplusd_SS_Rest
#       - Top_Matched | 2018_mu_wplusd_SS_Matched
#       - Top_Rest | 2018_mu_wplusd_SS_Rest
#       - Wjets_emu_NoMatch | 2018_mu_wplusd_SS_NoMatch
#       - Other
#       - Zjets_emu
#     regions:
#       - SS_2018_mu_SR_DstarKPiPi0
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, SS"
#       - "MadGraph"
#     lumi: "2018"
# #     save_to_file: True
    
#   2018_mu_wplusd_OS-SS:
#     samples:
#       - Wjets_emu_Matched | 2018_mu_wplusd_OS-SS_Matched
#       - Wjets_emu_Rest | 2018_mu_wplusd_OS-SS_Rest
#       - Top_Matched | 2018_mu_wplusd_OS-SS_Matched
#       - Top_Rest | 2018_mu_wplusd_OS-SS_Rest
#       - Wjets_emu_NoMatch | 2018_mu_wplusd_OS-SS_NoMatch
#       - Other
#       - Zjets_emu
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0
#       - -SS_2018_mu_SR_DstarKPiPi0
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS-SS"
#       - "MadGraph"
#     lumi: "2018"
# #     save_to_file: True

#   2018_el_wplusd_OS_Matched:
#     regions:
#       - OS_2018_el_SR_DstarKPiPi0_Matched
# #     make_plots: False

#   2018_el_wplusd_SS_Matched:
#     regions:
#       - SS_2018_el_SR_DstarKPiPi0_Matched
# #     make_plots: False

#   2018_el_wplusd_OS-SS_Matched:
#     regions:
#       - OS_2018_el_SR_DstarKPiPi0_Matched
#       - -SS_2018_el_SR_DstarKPiPi0_Matched
# #     make_plots: False

#   2018_el_wplusd_OS_NoMatch:
#     regions:
#       - OS_2018_el_SR_DstarKPiPi0_Other
# #     make_plots: False

#   2018_el_wplusd_SS_NoMatch:
#     regions:
#       - SS_2018_el_SR_DstarKPiPi0_Other
# #     make_plots: False

#   2018_el_wplusd_OS-SS_NoMatch:
#     regions:
#       - OS_2018_el_SR_DstarKPiPi0_Other
#       - -SS_2018_el_SR_DstarKPiPi0_Other
# #     make_plots: False

#   2018_el_wplusd_OS_Rest:
#     regions:
#       - OS_2018_el_SR_DstarKPiPi0
#       - -OS_2018_el_SR_DstarKPiPi0_Matched
#       - -OS_2018_el_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_el_wplusd_SS_Rest:
#     regions:
#       - SS_2018_el_SR_DstarKPiPi0
#       - -SS_2018_el_SR_DstarKPiPi0_Matched
#       - -SS_2018_el_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_el_wplusd_OS-SS_Rest:
#     regions:
#       - OS_2018_el_SR_DstarKPiPi0
#       - -OS_2018_el_SR_DstarKPiPi0_Matched
#       - -OS_2018_el_SR_DstarKPiPi0_Other
#       - -SS_2018_el_SR_DstarKPiPi0
#       - SS_2018_el_SR_DstarKPiPi0_Matched
#       - SS_2018_el_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_mu_wplusd_OS_Matched:
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0_Matched
#     make_plots: False

#   2018_mu_wplusd_SS_Matched:
#     regions:
#       - SS_2018_mu_SR_DstarKPiPi0_Matched
#     make_plots: False

#   2018_mu_wplusd_OS-SS_Matched:
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0_Matched
#       - -SS_2018_mu_SR_DstarKPiPi0_Matched
#     make_plots: False

#   2018_mu_wplusd_OS_NoMatch:
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_mu_wplusd_SS_NoMatch:
#     regions:
#       - SS_2018_mu_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_mu_wplusd_OS-SS_NoMatch:
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0_Other
#       - -SS_2018_mu_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_mu_wplusd_OS_Rest:
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0
#       - -OS_2018_mu_SR_DstarKPiPi0_Matched
#       - -OS_2018_mu_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_mu_wplusd_SS_Rest:
#     regions:
#       - SS_2018_mu_SR_DstarKPiPi0
#       - -SS_2018_mu_SR_DstarKPiPi0_Matched
#       - -SS_2018_mu_SR_DstarKPiPi0_Other
#     make_plots: False

#   2018_mu_wplusd_OS-SS_Rest:
#     regions:
#       - OS_2018_mu_SR_DstarKPiPi0
#       - -OS_2018_mu_SR_DstarKPiPi0_Matched
#       - -OS_2018_mu_SR_DstarKPiPi0_Other
#       - -SS_2018_mu_SR_DstarKPiPi0
#       - SS_2018_mu_SR_DstarKPiPi0_Matched
#       - SS_2018_mu_SR_DstarKPiPi0_Other
#     make_plots: False
