variablesConf: charmed_wjets_dstar

samplesConf: sherpa

data: Data

samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson

channels:
  2018_el_SR_DstarKPiPi0_OS:
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    regions:
      - 2018_el_SR_DstarKPiPi0_OS
    label:
      - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS"
      - "Sherpa"
    lumi: "2018"
    
    
  2018_el_SR_DstarKPiPi0_SS:
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    regions:
      - 2018_el_SR_DstarKPiPi0_SS
    label:
      - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, SS"
      - "Sherpa"
    lumi: "2018"
    
    
    
  2018_el_SR_DstarKPiPi0_OS-SS:
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    regions:
      - 2018_el_SR_DstarKPiPi0_OS
      - -2018_el_SR_DstarKPiPi0_SS
    label:
      - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS-SS"
      - "Sherpa"
    lumi: "2018"

#   2018_el_wplusd_OS:
#     regions:
#       - 2018_el_SR_Dstar_OS
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS"
#       - "Sherpa"
#     lumi: "2018"

#   2018_el_wplusd_SS:
#     regions:
#       - 2018_el_SR_Dstar_SS
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, SS"
#       - "Sherpa"
#     lumi: "2018"

#   2018_el_wplusd_OS-SS:
#     regions:
#       - 2018_el_SR_Dstar_OS
#       - 2018_el_SR_Dstar_SS
#     samples:
#       - Wjets_tau
#       - Wjets_cjets_emu
#       - Wjets_bjets_emu
#       - Wjets_light_emu
# #       - Zjets
# #       - Top
# #       - Diboson
#     label:
#       - "W#rightarrowe#nu+D*, D*#rightarrow(K#pi#pi^{0})#pi, OS-SS"
#       - "Sherpa"
#     extra_rebin: 2
#     lumi: "2018"

#   2018_mu_wplusd:
#     regions:
#       - 2018_mu_SR_Dstar
#     label:
#       - "W#rightarrow#mu#nu+D, D*#rightarrow(K#pi#pi^{0})#pi"
#       - "Sherpa"
#     lumi: "2018"

#   2018_mu_wplusd_OS:
#     regions:
#       - 2018_mu_SR_Dstar_OS
#     label:
#       - "W#rightarrow#mu#nu+D, D#rightarrow(K#pi#pi^{0})#pi, OS"
#       - "Sherpa"
#     lumi: "2018"

#   2018_mu_wplusd_SS:
#     regions:
#       - 2018_mu_SR_Dstar_SS
#     label:
#       - "W#rightarrow#mu#nu+D, D#rightarrow(K#pi#pi^{0})#pi, SS"
#       - "Sherpa"
#     lumi: "2018"

#   2018_mu_wplusd_OS-SS:
#     regions:
#       - 2018_mu_SR_Dstar_OS
#       - -2018_mu_SR_Dstar_SS
#     samples:
#       - Wjets_tau
#       - Wjets_cjets_emu
#       - Wjets_bjets_emu
#       - Wjets_light_emu
# #       - Zjets
# #       - Top
# #       - Diboson
#     label:
#       - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
#       - "Sherpa"
#     extra_rebin: 2
#     lumi: "2018"
