channels:
  2018_el_wplusd_OS_Matched:
    regions:
      - 2018_el_SR_Dplus_OS_Matched
    make_plots: False

  2018_el_wplusd_OS_NoMatch:
    regions:
      - 2018_el_SR_Dplus_OS_Other
    make_plots: False

  2018_el_wplusd_OS_HardMisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_HardMisMatched
    make_plots: False

  2018_el_wplusd_OS_MxMisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_MxMisMatched
    make_plots: False

  2018_el_wplusd_OS_MxMatched:
    regions:
      - 2018_el_SR_Dplus_OS_MxMatched
    make_plots: False

  2018_el_wplusd_OS_411MisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_411MisMatched
    make_plots: False

  2018_el_wplusd_OS_413MisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_413MisMatched
    make_plots: False

  2018_el_wplusd_OS_421MisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_421MisMatched
    make_plots: False

  2018_el_wplusd_OS_431MisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_431MisMatched
    make_plots: False

  2018_el_wplusd_OS_BaryonMisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_4122MisMatched
      - 2018_el_SR_Dplus_OS_4132MisMatched
      - 2018_el_SR_Dplus_OS_4232MisMatched
    make_plots: False

  2018_el_wplusd_OS_Charm:
    regions:
      - 2018_el_SR_Dplus_OS
      - -2018_el_SR_Dplus_OS_HardMisMatched
      - -2018_el_SR_Dplus_OS_Matched
      - -2018_el_SR_Dplus_OS_Other
    make_plots: False

  2018_el_wplusd_SS_Matched:
    regions:
      - 2018_el_SR_Dplus_SS_Matched
    make_plots: False

  2018_el_wplusd_SS_NoMatch:
    regions:
      - 2018_el_SR_Dplus_SS_Other
    make_plots: False

  2018_el_wplusd_SS_HardMisMatched:
    regions:
      - 2018_el_SR_Dplus_SS_HardMisMatched
    make_plots: False

  2018_el_wplusd_SS_Charm:
    regions:
      - 2018_el_SR_Dplus_SS
      - -2018_el_SR_Dplus_SS_HardMisMatched
      - -2018_el_SR_Dplus_SS_Matched
      - -2018_el_SR_Dplus_SS_Other
    make_plots: False

  2018_el_wplusd_OS-SS_Matched:
    regions:
      - 2018_el_SR_Dplus_OS_Matched
      - -2018_el_SR_Dplus_SS_Matched
    make_plots: False

  2018_el_wplusd_OS-SS_NoMatch:
    regions:
      - 2018_el_SR_Dplus_OS_Other
      - -2018_el_SR_Dplus_SS_Other
    make_plots: False

  2018_el_wplusd_OS-SS_HardMisMatched:
    regions:
      - 2018_el_SR_Dplus_OS_HardMisMatched
      - -2018_el_SR_Dplus_SS_HardMisMatched
    make_plots: False

  2018_el_wplusd_OS-SS_Charm:
    regions:
      - 2018_el_SR_Dplus_OS
      - -2018_el_SR_Dplus_OS_Matched
      - -2018_el_SR_Dplus_OS_Other
      - -2018_el_SR_Dplus_OS_HardMisMatched
      - -2018_el_SR_Dplus_SS
      - 2018_el_SR_Dplus_SS_Matched
      - 2018_el_SR_Dplus_SS_Other
      - 2018_el_SR_Dplus_SS_HardMisMatched
    make_plots: False

  2018_mu_wplusd_OS_Matched:
    regions:
      - 2018_mu_SR_Dplus_OS_Matched
    make_plots: False

  2018_mu_wplusd_OS_NoMatch:
    regions:
      - 2018_mu_SR_Dplus_OS_Other
    make_plots: False

  2018_mu_wplusd_OS_HardMisMatched:
    regions:
      - 2018_mu_SR_Dplus_OS_HardMisMatched
    make_plots: False

  2018_mu_wplusd_OS_Charm:
    regions:
      - 2018_mu_SR_Dplus_OS
      - -2018_mu_SR_Dplus_OS_HardMisMatched
      - -2018_mu_SR_Dplus_OS_Matched
      - -2018_mu_SR_Dplus_OS_Other
    make_plots: False

  2018_mu_wplusd_SS_Matched:
    regions:
      - 2018_mu_SR_Dplus_SS_Matched
    make_plots: False

  2018_mu_wplusd_SS_NoMatch:
    regions:
      - 2018_mu_SR_Dplus_SS_Other
    make_plots: False

  2018_mu_wplusd_SS_HardMisMatched:
    regions:
      - 2018_mu_SR_Dplus_SS_HardMisMatched
    make_plots: False

  2018_mu_wplusd_SS_Charm:
    regions:
      - 2018_mu_SR_Dplus_SS
      - -2018_mu_SR_Dplus_SS_HardMisMatched
      - -2018_mu_SR_Dplus_SS_Matched
      - -2018_mu_SR_Dplus_SS_Other
    make_plots: False

  2018_mu_wplusd_OS-SS_Matched:
    regions:
      - 2018_mu_SR_Dplus_OS_Matched
      - -2018_mu_SR_Dplus_SS_Matched
    make_plots: False

  2018_mu_wplusd_OS-SS_NoMatch:
    regions:
      - 2018_mu_SR_Dplus_OS_Other
      - -2018_mu_SR_Dplus_SS_Other
    make_plots: False

  2018_mu_wplusd_OS-SS_HardMisMatched:
    regions:
      - 2018_mu_SR_Dplus_OS_HardMisMatched
      - -2018_mu_SR_Dplus_SS_HardMisMatched
    make_plots: False

  2018_mu_wplusd_OS-SS_Charm:
    regions:
      - 2018_mu_SR_Dplus_OS
      - -2018_mu_SR_Dplus_OS_Matched
      - -2018_mu_SR_Dplus_OS_Other
      - -2018_mu_SR_Dplus_OS_HardMisMatched
      - -2018_mu_SR_Dplus_SS
      - 2018_mu_SR_Dplus_SS_Matched
      - 2018_mu_SR_Dplus_SS_Other
      - 2018_mu_SR_Dplus_SS_HardMisMatched
    make_plots: False
