colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: powheg

data: Data

samples:
  - Top
  - Wjets_emu
  - Wjets_tau
  - Zjets_emu
  - Zjets_tau
  - Diboson

channels:
  2018_el_wplusd:
    regions:
      - 2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi"
      - "Powheg"
    lumi: "2018"

  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "Powheg"
    lumi: "2018"

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "Powheg"
    lumi: "2018"

  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    samples:
      - Wjets_emu
      - Wjets_tau
      - Zjets_emu
      - Zjets_tau
      - Top
      - Diboson
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "Powheg"
    extra_rebin: 2
    lumi: "2018"

  2018_mu_wplusd_OS:
    regions:
      - OS_2018_mu_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "Powheg"
    lumi: "2018"

  2018_mu_wplusd_SS:
    regions:
      - SS_2018_mu_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "Powheg"
    lumi: "2018"

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus
    samples:
      - Wjets_emu
      - Wjets_tau
      - Zjets_emu
      - Zjets_tau
      - Top
      - Diboson
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "Powheg"
    extra_rebin: 2
    lumi: "2018"
