variablesConf: charmed_wjets

samplesConf: madgraph

data: Data

samples:
  - Top
  - Wjets_tau
  - Wjets_cjets_emu
  - Wjets_bjets_emu
  - Wjets_light_emu
  - Zjets
  - Diboson

channels:
  2018_el_wplusd_0tag:
    regions:
      - 2018_el_0tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi"
      - "MadGraph, 0 #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_1tag:
    regions:
      - 2018_el_1tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi"
      - "MadGraph, 1 #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_2tag:
    regions:
      - 2018_el_2tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi"
      - "MadGraph, 2+ #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_OS_0tag:
    regions:
      - OS_2018_el_0tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 0 #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_OS_1tag:
    regions:
      - OS_2018_el_1tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 1 #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_OS_2tag:
    regions:
      - OS_2018_el_2tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 2+ #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_SS_0tag:
    regions:
      - SS_2018_el_0tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 0 #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_SS_1tag:
    regions:
      - SS_2018_el_1tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 1 #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_SS_2tag:
    regions:
      - SS_2018_el_2tag_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 2+ #it{b}-tag"
    lumi: "2018"

  2018_el_wplusd_OS-SS_0tag:
    regions:
      - OS_2018_el_0tag_SR_Dplus
      - -SS_2018_el_0tag_SR_Dplus
    samples:
      - Wjets_tau
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 0 #it{b}-tag"
    extra_rebin: 2
    lumi: "2018"

  2018_el_wplusd_OS-SS_1tag:
    regions:
      - OS_2018_el_1tag_SR_Dplus
      - -SS_2018_el_1tag_SR_Dplus
    samples:
      - Wjets_tau
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 1 #it{b}-tag"
    extra_rebin: 2
    lumi: "2018"

  2018_el_wplusd_OS-SS_2tag:
    regions:
      - OS_2018_el_2tag_SR_Dplus
      - -SS_2018_el_2tag_SR_Dplus
    samples:
      - Wjets_tau
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 2+ #it{b}-tag"
    extra_rebin: 2
    lumi: "2018"

  2018_mu_wplusd_0tag:
    regions:
      - 2018_mu_0tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi"
      - "MadGraph, 0 #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_1tag:
    regions:
      - 2018_mu_1tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi"
      - "MadGraph, 1 #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_2tag:
    regions:
      - 2018_mu_2tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi"
      - "MadGraph, 2+ #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_OS_0tag:
    regions:
      - OS_2018_mu_0tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 0 #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_OS_1tag:
    regions:
      - OS_2018_mu_1tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 1 #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_OS_2tag:
    regions:
      - OS_2018_mu_2tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 2+ #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_SS_0tag:
    regions:
      - SS_2018_mu_0tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 0 #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_SS_1tag:
    regions:
      - SS_2018_mu_1tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 1 #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_SS_2tag:
    regions:
      - SS_2018_mu_2tag_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 2+ #it{b}-tag"
    lumi: "2018"

  2018_mu_wplusd_OS-SS_0tag:
    regions:
      - OS_2018_mu_0tag_SR_Dplus
      - -SS_2018_mu_0tag_SR_Dplus
    samples:
      - Wjets_tau
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 0 #it{b}-tag"
    extra_rebin: 2
    lumi: "2018"

  2018_mu_wplusd_OS-SS_1tag:
    regions:
      - OS_2018_mu_1tag_SR_Dplus
      - -SS_2018_mu_1tag_SR_Dplus
    samples:
      - Wjets_tau
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 1 #it{b}-tag"
    extra_rebin: 2
    lumi: "2018"

  2018_mu_wplusd_OS-SS_2tag:
    regions:
      - OS_2018_mu_2tag_SR_Dplus
      - -SS_2018_mu_2tag_SR_Dplus
    samples:
      - Wjets_tau
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 2+ #it{b}-tag"
    extra_rebin: 2
    lumi: "2018"
