variablesConf: charmed_wjets

samplesConf: madgraph_truth

data: Data

channels:
  include: wplusd/truth_match.yaml

  2018_el_wplusd_OS:
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_OS_Matched
      - Wjets_emu_Charm | 2018_el_wplusd_OS_Charm
      - Wjets_emu_HardMisMatched | 2018_el_wplusd_OS_HardMisMatched
      - Top_Matched | 2018_el_wplusd_OS_Matched
      - Top_Charm | 2018_el_wplusd_OS_Charm
      - Top_HardMisMatched | 2018_el_wplusd_OS_HardMisMatched
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_Dplus_OS
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_el_wplusd_SS:
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_SS_Matched
      - Wjets_emu_Charm | 2018_el_wplusd_SS_Charm
      - Wjets_emu_HardMisMatched | 2018_el_wplusd_SS_HardMisMatched
      - Top_Matched | 2018_el_wplusd_SS_Matched
      - Top_Charm | 2018_el_wplusd_SS_Charm
      - Top_HardMisMatched | 2018_el_wplusd_SS_HardMisMatched
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_Dplus_SS
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_el_wplusd_OS-SS:
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_OS-SS_Matched
      - Wjets_emu_Charm | 2018_el_wplusd_OS-SS_Charm
      - Wjets_emu_HardMisMatched | 2018_el_wplusd_OS-SS_HardMisMatched
      - Top_Matched | 2018_el_wplusd_OS-SS_Matched
      - Top_Charm | 2018_el_wplusd_OS-SS_Charm
      - Top_HardMisMatched | 2018_el_wplusd_OS-SS_HardMisMatched
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS-SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_el_SR_Dplus_OS
      - -2018_el_SR_Dplus_SS
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_mu_wplusd_OS:
    samples:
      - Wjets_emu_Matched | 2018_mu_wplusd_OS_Matched
      - Wjets_emu_Charm | 2018_mu_wplusd_OS_Charm
      - Wjets_emu_HardMisMatched | 2018_mu_wplusd_OS_HardMisMatched
      - Top_Matched | 2018_mu_wplusd_OS_Matched
      - Top_Charm | 2018_mu_wplusd_OS_Charm
      - Top_HardMisMatched | 2018_mu_wplusd_OS_HardMisMatched
      - Wjets_emu_NoMatch | 2018_mu_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_mu_SR_Dplus_OS
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_mu_wplusd_SS:
    samples:
      - Wjets_emu_Matched | 2018_mu_wplusd_SS_Matched
      - Wjets_emu_Charm | 2018_mu_wplusd_SS_Charm
      - Wjets_emu_HardMisMatched | 2018_mu_wplusd_SS_HardMisMatched
      - Top_Matched | 2018_mu_wplusd_SS_Matched
      - Top_Charm | 2018_mu_wplusd_SS_Charm
      - Top_HardMisMatched | 2018_mu_wplusd_SS_HardMisMatched
      - Wjets_emu_NoMatch | 2018_mu_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_mu_SR_Dplus_SS
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True
    
  2018_mu_wplusd_OS-SS:
    samples:
      - Wjets_emu_Matched | 2018_mu_wplusd_OS-SS_Matched
      - Wjets_emu_Charm | 2018_mu_wplusd_OS-SS_Charm
      - Wjets_emu_HardMisMatched | 2018_mu_wplusd_OS-SS_HardMisMatched
      - Top_Matched | 2018_mu_wplusd_OS-SS_Matched
      - Top_Charm | 2018_mu_wplusd_OS-SS_Charm
      - Top_HardMisMatched | 2018_mu_wplusd_OS-SS_HardMisMatched
      - Wjets_emu_NoMatch | 2018_mu_wplusd_OS-SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - 2018_mu_SR_Dplus_OS
      - -2018_mu_SR_Dplus_SS
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True
