variablesConf: charmed_wjets

samplesConf: madgraph

data: Data

samples:
  - Top
  - Wjets_cjets_emu
  - Wjets_bjets_emu
  - Wjets_light_emu
  - Wjets_tau
  - Zjets
  - Diboson

channels:
  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"

  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    extra_rebin: 2
    lumi: "2018"

  2018_mu_wplusd_OS:
    regions:
      - OS_2018_mu_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"

  2018_mu_wplusd_SS:
    regions:
      - SS_2018_mu_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    extra_rebin: 2
    lumi: "2018"
