variablesConf: charmed_wjets

samplesConf: powheg_truth

data: Data

channels:
  2018_el_wplusd_OS:
    samples:
      - Top
      - Wjets_tau
      - Wjets_emu_Matched | 2018_el_wplusd_OS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_OS_Rest
      - Zjets
      - Diboson
    regions:
      - OS_2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"

  2018_el_wplusd_SS:
    samples:
      - Top
      - Wjets_tau
      - Wjets_emu_Matched | 2018_el_wplusd_SS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_SS_Rest
      - Zjets
      - Diboson
    regions:
      - SS_2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"

  2018_el_wplusd_OS-SS:
    samples:
      - Wjets_tau
      - Wjets_emu_Matched | 2018_el_wplusd_OS-SS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_OS-SS_Rest
      - Top
      - Zjets
      - Diboson
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    lumi: "2018"

  2018_mu_wplusd_OS:
    samples:
      - Top
      - Wjets_tau
      - Wjets_emu_Matched | 2018_mu_wplusd_OS_Matched
      - Wjets_emu_Rest | 2018_mu_wplusd_OS_Rest
      - Zjets
      - Diboson
    regions:
      - OS_2018_mu_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"

  2018_mu_wplusd_SS:
    samples:
      - Top
      - Wjets_tau
      - Wjets_emu_Matched | 2018_mu_wplusd_SS_Matched
      - Wjets_emu_Rest | 2018_mu_wplusd_SS_Rest
      - Zjets
      - Diboson
    regions:
      - SS_2018_mu_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"

  2018_mu_wplusd_OS-SS:
    samples:
      - Wjets_tau
      - Wjets_emu_Matched | 2018_mu_wplusd_OS-SS_Matched
      - Wjets_emu_Rest | 2018_mu_wplusd_OS-SS_Rest
      - Top
      - Zjets
      - Diboson
    regions:
      - OS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    lumi: "2018"

  2018_el_wplusd_OS_Matched:
    regions:
      - OS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_SS_Matched:
    regions:
      - SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_OS-SS_Matched:
    regions:
      - OS_2018_el_SR_Dplus_Matched
      - -SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_OS_Rest:
    regions:
      - OS_2018_el_SR_Dplus
      - -OS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_SS_Rest:
    regions:
      - SS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_OS-SS_Rest:
    regions:
      - OS_2018_el_SR_Dplus
      - -OS_2018_el_SR_Dplus_Matched
      - -SS_2018_el_SR_Dplus
      - SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_mu_wplusd_OS_Matched:
    regions:
      - OS_2018_mu_SR_Dplus_Matched
    make_plots: False

  2018_mu_wplusd_SS_Matched:
    regions:
      - SS_2018_mu_SR_Dplus_Matched
    make_plots: False

  2018_mu_wplusd_OS-SS_Matched:
    regions:
      - OS_2018_mu_SR_Dplus_Matched
      - -SS_2018_mu_SR_Dplus_Matched
    make_plots: False

  2018_mu_wplusd_OS_Rest:
    regions:
      - OS_2018_mu_SR_Dplus
      - -OS_2018_mu_SR_Dplus_Matched
    make_plots: False

  2018_mu_wplusd_SS_Rest:
    regions:
      - SS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus_Matched
    make_plots: False

  2018_mu_wplusd_OS-SS_Rest:
    regions:
      - OS_2018_mu_SR_Dplus
      - -OS_2018_mu_SR_Dplus_Matched
      - -SS_2018_mu_SR_Dplus
      - SS_2018_mu_SR_Dplus_Matched
    make_plots: False
