type: updown
affecting:
  - Sherpa2211_Wjets_Charm
  - Sherpa2211_Wjets_Rest
  - Sherpa2211_Wjets_MisMatched
  - MG_Wjets_Rest
  - MG_Wjets_Charm
  - Top
  - DibosonZjets
variations:
  - DMESON_RESO_IBL
  - DMESON_RESO_Overal
  - DMESON_RESO_PP0
  - DMESON_RESO_QGSP
  - DMESON_RESO_TEST
  # - DMESON_RESO_TRK_RES_D0_DEAD
  # - DMESON_RESO_TRK_RES_D0_MEAS
  # - DMESON_RESO_TRK_RES_Z0_DEAD
  # - DMESON_RESO_TRK_RES_Z0_MEAS
