type: updown
affecting:
  - Sherpa2211_WplusD_Matched
  - Sherpa2211_WplusD_Matched_truth_pt_bin1
  - Sherpa2211_WplusD_Matched_truth_pt_bin2
  - Sherpa2211_WplusD_Matched_truth_pt_bin3
  - Sherpa2211_WplusD_Matched_truth_pt_bin4
  - Sherpa2211_WplusD_Matched_truth_pt_bin5
  - MGPy8EG_NLO_WplusD_Matched
  - MGPy8EG_NLO_WplusD_Matched_truth_pt_bin1
  - MGPy8EG_NLO_WplusD_Matched_truth_pt_bin2
  - MGPy8EG_NLO_WplusD_Matched_truth_pt_bin3
  - MGPy8EG_NLO_WplusD_Matched_truth_pt_bin4
  - MGPy8EG_NLO_WplusD_Matched_truth_pt_bin5
use_replacement: True
variations:
  - RESO_ADHOC_1
  - RESO_ADHOC_2
  - RESO_ADHOC_4
  # - DMESON_RESO_ADHOC_1
  # - DMESON_RESO_ADHOC_2
  # - DMESON_RESO_ADHOC_4
  # - DMESON_MASS_ADHOC_UP
  # - DMESON_MASS_ADHOC_DN
  # - DMESON_MASS_ADHOC_2UP
  # - DMESON_MASS_ADHOC_2DN
