variations:
  - EG_RESOLUTION_ALL__1down
  - EG_RESOLUTION_ALL__1up
  - EG_SCALE_AF2__1down
  - EG_SCALE_AF2__1up
  - EG_SCALE_ALL__1down
  - EG_SCALE_ALL__1up
  - EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR__1down
  - EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR__1up
  - EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR__1down
  - EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR__1up
  - EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR__1down
  - EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR__1up
  - EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR__1down
  - EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR__1up
  - EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR__1down
  - EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR__1up
  - JET_BJES_Response__1down
  - JET_BJES_Response__1up
  - JET_EffectiveNP_1__1down
  - JET_EffectiveNP_1__1up
  - JET_EffectiveNP_2__1down
  - JET_EffectiveNP_2__1up
  - JET_EffectiveNP_3__1down
  - JET_EffectiveNP_3__1up
  - JET_EffectiveNP_4__1down
  - JET_EffectiveNP_4__1up
  - JET_EffectiveNP_5__1down
  - JET_EffectiveNP_5__1up
  - JET_EffectiveNP_6__1down
  - JET_EffectiveNP_6__1up
  - JET_EffectiveNP_7__1down
  - JET_EffectiveNP_7__1up
  - JET_EffectiveNP_8restTerm__1down
  - JET_EffectiveNP_8restTerm__1up
  - JET_EtaIntercalibration_Modelling__1down
  - JET_EtaIntercalibration_Modelling__1up
  - JET_EtaIntercalibration_NonClosure_highE__1down
  - JET_EtaIntercalibration_NonClosure_highE__1up
  - JET_EtaIntercalibration_NonClosure_negEta__1down
  - JET_EtaIntercalibration_NonClosure_negEta__1up
  - JET_EtaIntercalibration_NonClosure_posEta__1down
  - JET_EtaIntercalibration_NonClosure_posEta__1up
  - JET_EtaIntercalibration_TotalStat__1down
  - JET_EtaIntercalibration_TotalStat__1up
  - JET_Flavor_Composition__1down
  - JET_Flavor_Composition__1up
  - JET_Flavor_Response__1down
  - JET_Flavor_Response__1up
  - JET_JER_DataVsMC_MC16__1down
  - JET_JER_DataVsMC_MC16__1up
  - JET_JER_EffectiveNP_1__1down
  - JET_JER_EffectiveNP_1__1up
  - JET_JER_EffectiveNP_2__1down
  - JET_JER_EffectiveNP_2__1up
  - JET_JER_EffectiveNP_3__1down
  - JET_JER_EffectiveNP_3__1up
  - JET_JER_EffectiveNP_4__1down
  - JET_JER_EffectiveNP_4__1up
  - JET_JER_EffectiveNP_5__1down
  - JET_JER_EffectiveNP_5__1up
  - JET_JER_EffectiveNP_6__1down
  - JET_JER_EffectiveNP_6__1up
  - JET_JER_EffectiveNP_7restTerm__1down
  - JET_JER_EffectiveNP_7restTerm__1up
  - JET_JvtEfficiency__1down
  - JET_JvtEfficiency__1up
  - JET_Pileup_OffsetMu__1down
  - JET_Pileup_OffsetMu__1up
  - JET_Pileup_OffsetNPV__1down
  - JET_Pileup_OffsetNPV__1up
  - JET_Pileup_PtTerm__1down
  - JET_Pileup_PtTerm__1up
  - JET_Pileup_RhoTopology__1down
  - JET_Pileup_RhoTopology__1up
  - JET_PunchThrough_MC16__1down
  - JET_PunchThrough_MC16__1up
  - JET_SingleParticle_HighPt__1down
  - JET_SingleParticle_HighPt__1up
  - MET_SoftTrk_ResoPara
  - MET_SoftTrk_ResoPerp
  - MET_SoftTrk_ScaleDown
  - MET_SoftTrk_ScaleUp
  - MUON_EFF_RECO_STAT__1down
  - MUON_EFF_RECO_STAT__1up
  - MUON_EFF_RECO_STAT_LOWPT__1down
  - MUON_EFF_RECO_STAT_LOWPT__1up
  - MUON_EFF_RECO_SYS__1down
  - MUON_EFF_RECO_SYS__1up
  - MUON_EFF_RECO_SYS_LOWPT__1down
  - MUON_EFF_RECO_SYS_LOWPT__1up
  - MUON_EFF_TrigStatUncertainty__1down
  - MUON_EFF_TrigStatUncertainty__1up
  - MUON_EFF_TrigSystUncertainty__1down
  - MUON_EFF_TrigSystUncertainty__1up
  - MUON_EFF_TTVA_STAT__1down
  - MUON_EFF_TTVA_STAT__1up
  - MUON_EFF_TTVA_SYS__1down
  - MUON_EFF_TTVA_SYS__1up
  - MUON_ID__1down
  - MUON_ID__1up
  - MUON_MS__1down
  - MUON_MS__1up
  - MUON_SAGITTA_RESBIAS__1down
  - MUON_SAGITTA_RESBIAS__1up
  - MUON_SAGITTA_RHO__1down
  - MUON_SAGITTA_RHO__1up
  - MUON_SCALE__1down
  - MUON_SCALE__1up
  - PRW_DATASF__1down
  - PRW_DATASF__1up
