type: updown
affecting:
  - Multijet_MatrixMethod
  - Multijet_MatrixMethod_Offset
  - Multijet_MatrixMethod_FF
  - Multijet_MatrixMethod_Tight
  - Multijet_MatrixMethod_AntiTight
variations:
  - MM_EL_RR_STAT__1up
  - MM_EL_RR_STAT__1down
  - MM_EL_FR_STAT__1up
  - MM_EL_FR_STAT__1down
  - MM_EL_RR_MadGraph_Var
  - MM_EL_FR__Wjets_MadGraph_Var
  - MM_EL_FR_MET_Var
  - MM_EL_NON_CLOSURE
  - MM_MU_RR_STAT__1up
  - MM_MU_RR_STAT__1down
  - MM_MU_FR_STAT__1up
  - MM_MU_FR_STAT__1down
  - MM_MU_RR_MadGraph_Var
  - MM_MU_FR__Wjets_MadGraph_Var
  - MM_MU_NON_CLOSURE
  - MM_MU_FR_MET_Var
