type: updown
affecting:
  - Multijet_MatrixMethod
variations:
  - MM_REAL_RATE_STAT__1up
  - MM_REAL_RATE_STAT__1down
  - MM_REAL_RATE__Wjets_Sherpa
  - MM_REAL_RATE__Wjets_MadGraph
  - MM_FAKE_RATE_STAT__1up
  - MM_FAKE_RATE_STAT__1down
  - MM_FAKE_RATE__Wjets_Sherpa
  - MM_FAKE_RATE__Wjets_MadGraph_Up
  - MM_FAKE_RATE__Wjets_MadGraph_Dn