type: overall
size: 0.01
affecting:
  - DibosonZjets
  - Multijet_MatrixMethod
  - Top
  - Wjets_emu_411MisMatched
  - Wjets_emu_Charm
  - Wjets_emu_Matched
  - Wjets_emu_MisMatched
  - Wjets_emu_Rest
  - Wjets_Rest
variations:
  - PROXY_NORM__1up
  - PROXY_NORM__1dn
