# type: updown
type: NNPDF30_nnlo_as_0118_hessian
affecting:
  - Sherpa2211_WplusD
  - Sherpa2211_Wjets
variations:
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200
  - GEN_ME_ONLY_MUR1_MUF1_PDF303201
  - GEN_ME_ONLY_MUR1_MUF1_PDF303202
  - GEN_ME_ONLY_MUR1_MUF1_PDF303203
  - GEN_ME_ONLY_MUR1_MUF1_PDF303204
  - GEN_ME_ONLY_MUR1_MUF1_PDF303205
  - GEN_ME_ONLY_MUR1_MUF1_PDF303206
  - GEN_ME_ONLY_MUR1_MUF1_PDF303207
  - GEN_ME_ONLY_MUR1_MUF1_PDF303208
  - GEN_ME_ONLY_MUR1_MUF1_PDF303209
  - GEN_ME_ONLY_MUR1_MUF1_PDF303210
  - GEN_ME_ONLY_MUR1_MUF1_PDF303211
  - GEN_ME_ONLY_MUR1_MUF1_PDF303212
  - GEN_ME_ONLY_MUR1_MUF1_PDF303213
  - GEN_ME_ONLY_MUR1_MUF1_PDF303214
  - GEN_ME_ONLY_MUR1_MUF1_PDF303215
  - GEN_ME_ONLY_MUR1_MUF1_PDF303216
  - GEN_ME_ONLY_MUR1_MUF1_PDF303217
  - GEN_ME_ONLY_MUR1_MUF1_PDF303218
  - GEN_ME_ONLY_MUR1_MUF1_PDF303219
  - GEN_ME_ONLY_MUR1_MUF1_PDF303220
  - GEN_ME_ONLY_MUR1_MUF1_PDF303221
  - GEN_ME_ONLY_MUR1_MUF1_PDF303222
  - GEN_ME_ONLY_MUR1_MUF1_PDF303223
  - GEN_ME_ONLY_MUR1_MUF1_PDF303224
  - GEN_ME_ONLY_MUR1_MUF1_PDF303225
  - GEN_ME_ONLY_MUR1_MUF1_PDF303226
  - GEN_ME_ONLY_MUR1_MUF1_PDF303227
  - GEN_ME_ONLY_MUR1_MUF1_PDF303228
  - GEN_ME_ONLY_MUR1_MUF1_PDF303229
  - GEN_ME_ONLY_MUR1_MUF1_PDF303230
  - GEN_ME_ONLY_MUR1_MUF1_PDF303231
  - GEN_ME_ONLY_MUR1_MUF1_PDF303232
  - GEN_ME_ONLY_MUR1_MUF1_PDF303233
  - GEN_ME_ONLY_MUR1_MUF1_PDF303234
  - GEN_ME_ONLY_MUR1_MUF1_PDF303235
  - GEN_ME_ONLY_MUR1_MUF1_PDF303236
  - GEN_ME_ONLY_MUR1_MUF1_PDF303237
  - GEN_ME_ONLY_MUR1_MUF1_PDF303238
  - GEN_ME_ONLY_MUR1_MUF1_PDF303239
  - GEN_ME_ONLY_MUR1_MUF1_PDF303240
  - GEN_ME_ONLY_MUR1_MUF1_PDF303241
  - GEN_ME_ONLY_MUR1_MUF1_PDF303242
  - GEN_ME_ONLY_MUR1_MUF1_PDF303243
  - GEN_ME_ONLY_MUR1_MUF1_PDF303244
  - GEN_ME_ONLY_MUR1_MUF1_PDF303245
  - GEN_ME_ONLY_MUR1_MUF1_PDF303246
  - GEN_ME_ONLY_MUR1_MUF1_PDF303247
  - GEN_ME_ONLY_MUR1_MUF1_PDF303248
  - GEN_ME_ONLY_MUR1_MUF1_PDF303249
  - GEN_ME_ONLY_MUR1_MUF1_PDF303250
  - GEN_ME_ONLY_MUR1_MUF1_PDF303251
  - GEN_ME_ONLY_MUR1_MUF1_PDF303252
  - GEN_ME_ONLY_MUR1_MUF1_PDF303253
  - GEN_ME_ONLY_MUR1_MUF1_PDF303254
  - GEN_ME_ONLY_MUR1_MUF1_PDF303255
  - GEN_ME_ONLY_MUR1_MUF1_PDF303256
  - GEN_ME_ONLY_MUR1_MUF1_PDF303257
  - GEN_ME_ONLY_MUR1_MUF1_PDF303258
  - GEN_ME_ONLY_MUR1_MUF1_PDF303259
  - GEN_ME_ONLY_MUR1_MUF1_PDF303260
  - GEN_ME_ONLY_MUR1_MUF1_PDF303261
  - GEN_ME_ONLY_MUR1_MUF1_PDF303262
  - GEN_ME_ONLY_MUR1_MUF1_PDF303263
  - GEN_ME_ONLY_MUR1_MUF1_PDF303264
  - GEN_ME_ONLY_MUR1_MUF1_PDF303265
  - GEN_ME_ONLY_MUR1_MUF1_PDF303266
  - GEN_ME_ONLY_MUR1_MUF1_PDF303267
  - GEN_ME_ONLY_MUR1_MUF1_PDF303268
  - GEN_ME_ONLY_MUR1_MUF1_PDF303269
  - GEN_ME_ONLY_MUR1_MUF1_PDF303270
  - GEN_ME_ONLY_MUR1_MUF1_PDF303271
  - GEN_ME_ONLY_MUR1_MUF1_PDF303272
  - GEN_ME_ONLY_MUR1_MUF1_PDF303273
  - GEN_ME_ONLY_MUR1_MUF1_PDF303274
  - GEN_ME_ONLY_MUR1_MUF1_PDF303275
  - GEN_ME_ONLY_MUR1_MUF1_PDF303276
  - GEN_ME_ONLY_MUR1_MUF1_PDF303277
  - GEN_ME_ONLY_MUR1_MUF1_PDF303278
  - GEN_ME_ONLY_MUR1_MUF1_PDF303279
  - GEN_ME_ONLY_MUR1_MUF1_PDF303280
  - GEN_ME_ONLY_MUR1_MUF1_PDF303281
  - GEN_ME_ONLY_MUR1_MUF1_PDF303282
  - GEN_ME_ONLY_MUR1_MUF1_PDF303283
  - GEN_ME_ONLY_MUR1_MUF1_PDF303284
  - GEN_ME_ONLY_MUR1_MUF1_PDF303285
  - GEN_ME_ONLY_MUR1_MUF1_PDF303286
  - GEN_ME_ONLY_MUR1_MUF1_PDF303287
  - GEN_ME_ONLY_MUR1_MUF1_PDF303288
  - GEN_ME_ONLY_MUR1_MUF1_PDF303289
  - GEN_ME_ONLY_MUR1_MUF1_PDF303290
  - GEN_ME_ONLY_MUR1_MUF1_PDF303291
  - GEN_ME_ONLY_MUR1_MUF1_PDF303292
  - GEN_ME_ONLY_MUR1_MUF1_PDF303293
  - GEN_ME_ONLY_MUR1_MUF1_PDF303294
  - GEN_ME_ONLY_MUR1_MUF1_PDF303295
  - GEN_ME_ONLY_MUR1_MUF1_PDF303296
  - GEN_ME_ONLY_MUR1_MUF1_PDF303297
  - GEN_ME_ONLY_MUR1_MUF1_PDF303298
  - GEN_ME_ONLY_MUR1_MUF1_PDF303299
  - GEN_ME_ONLY_MUR1_MUF1_PDF303300
