type: minmax
affecting:
  - Sherpa2211_WplusD
  - Sherpa2211_Wjets
  - Sherpa2211_WplusD_Matched
  - Sherpa2211_WplusD_Matched_truth_pt_bin1
  - Sherpa2211_WplusD_Matched_truth_pt_bin2
  - Sherpa2211_WplusD_Matched_truth_pt_bin3
  - Sherpa2211_WplusD_Matched_truth_pt_bin4
  - Sherpa2211_WplusD_Matched_truth_pt_bin5
  - Sherpa2211_Wjets_Charm
  - Sherpa2211_Wjets_MisMatched
  - Sherpa2211_Wjets_Rest
  - MG_Wjets_Rest
variations:
  - GEN_MUR05_MUF05_PDF303200_PSMUR05_PSMUF05
  - GEN_MUR05_MUF1_PDF303200_PSMUR05_PSMUF1
  - GEN_MUR1_MUF05_PDF303200_PSMUR1_PSMUF05
  - GEN_MUR1_MUF2_PDF303200_PSMUR1_PSMUF2
  - GEN_MUR2_MUF1_PDF303200_PSMUR2_PSMUF1
  - GEN_MUR2_MUF2_PDF303200_PSMUR2_PSMUF2
