type: updown
affecting:
  - Sherpa2211_WplusD
  - Sherpa2211_Wjets
  - Sh_2211_Multijet
variations:
  - GEN_MUR05_MUF05_PDF303200_PSMUR05_PSMUF05
  - GEN_MUR05_MUF1_PDF303200_PSMUR05_PSMUF1
  - GEN_MUR1_MUF05_PDF303200_PSMUR1_PSMUF05
  - GEN_MUR1_MUF2_PDF303200_PSMUR1_PSMUF2
  - GEN_MUR2_MUF1_PDF303200_PSMUR2_PSMUF1
  - GEN_MUR2_MUF2_PDF303200_PSMUR2_PSMUF2
