type: minmax
affecting:
  - Sherpa2211_WplusD
  - Sherpa2211_Wjets
  - Sherpa2211_WplusD_Matched
  - Sherpa2211_WplusD_Matched_truth_pt_bin1
  - Sherpa2211_WplusD_Matched_truth_pt_bin2
  - Sherpa2211_WplusD_Matched_truth_pt_bin3
  - Sherpa2211_WplusD_Matched_truth_pt_bin4
  - Sherpa2211_WplusD_Matched_truth_pt_bin5
  - Sherpa2211_WplusD_Matched_truth_eta_bin1
  - Sherpa2211_WplusD_Matched_truth_eta_bin2
  - Sherpa2211_WplusD_Matched_truth_eta_bin3
  - Sherpa2211_WplusD_Matched_truth_eta_bin4
  - Sherpa2211_WplusD_Matched_truth_eta_bin5
  - Sherpa2211_Wjets_Charm
  - Sherpa2211_Wjets_MisMatched
  - Sherpa2211_Wjets_Rest
  - MG_Wjets_Rest
variations:
  - GEN_MUR1_MUF1_PDF269000
  - GEN_MUR1_MUF1_PDF270000
