type: updown
affecting:
  - Sherpa2211_WplusD
  - Sherpa2211_Wjets
variations:
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_ASSEW
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_ASSEWLO1
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_ASSEWLO1LO2
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_ASSEWLO1LO2LO3
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_EXPASSEW
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_EXPASSEWLO1
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_EXPASSEWLO1LO2
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_EXPASSEWLO1LO2LO3
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_MULTIASSEW
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_MULTIASSEWLO1
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_MULTIASSEWLO1LO2
  - GEN_ME_ONLY_MUR1_MUF1_PDF303200_MULTIASSEWLO1LO2LO3
