type: updown
affecting:
  - Sherpa2211_WplusD_Matched
  - Sherpa2211_WplusD_Matched_truth_pt_bin1
  - Sherpa2211_WplusD_Matched_truth_pt_bin2
  - Sherpa2211_WplusD_Matched_truth_pt_bin3
  - Sherpa2211_WplusD_Matched_truth_pt_bin4
  - Sherpa2211_WplusD_Matched_truth_pt_bin5
  - Sherpa2211_WplusD_Matched_truth_eta_bin1
  - Sherpa2211_WplusD_Matched_truth_eta_bin2
  - Sherpa2211_WplusD_Matched_truth_eta_bin3
  - Sherpa2211_WplusD_Matched_truth_eta_bin4
  - Sherpa2211_WplusD_Matched_truth_eta_bin5
  - Sherpa2211_Wjets_Charm
  - Sherpa2211_Wjets_MisMatched
  - MG_Wjets_Charm
  - DibosonZjets
  - Top
variations:
  - PROD_FRAC_EIG_1
  - PROD_FRAC_EIG_2
  - PROD_FRAC_EIG_3
