type: updown
affecting:
  - Top_Matched
  - Top_Rest
  - Top
variations:
  - GEN_muR_10_muF_05
  - GEN_muR_10_muF_20
  - GEN_muR_05_muF_10
  - GEN_muR_20_muF_10
  - GEN_isrmuRfac10_fsrmuRfac20
  - GEN_isrmuRfac10_fsrmuRfac05
  - GEN_Var3cDown
  - GEN_Var3cUp
