type: updown
variations:
  - PROD_FRAC_EIG_1
  - PROD_FRAC_EIG_2
  - PROD_FRAC_EIG_3
  # - PROD_FRAC_NOWEIGHT
  # - WJETS_THEORY_NOWEIGHT
  - WJETS_THEORY_PDF
  - WJETS_THEORY_QCD_SCALE
  - WJETS_THEORY_SHERPA_PT
  - FID_EFF_WDPLUS