type: updown
affecting:
  - Wjets_emu_Matched
  - Wjets_emu_Matched_truth_pt_bin1
  - Wjets_emu_Matched_truth_pt_bin2
  - Wjets_emu_Matched_truth_pt_bin3
  - Wjets_emu_Matched_truth_pt_bin4
  - Wjets_emu_Matched_truth_pt_bin5
  - Wjets_emu_411MisMatched
  - Wjets_emu_413MisMatched
  - Wjets_emu_Charm
  - Wjets_emu_MisMatched
variations:
  - PROD_FRAC_EIG_1
  - PROD_FRAC_EIG_2
  - PROD_FRAC_EIG_3
  # - PROD_FRAC_NOWEIGHT
  # - WJETS_THEORY_NOWEIGHT
  - WJETS_THEORY_PDF
  - WJETS_THEORY_QCD_SCALE
  - WJETS_THEORY_SHERPA_PT
  - FID_EFF_WPLUSD_SHERPA
  - FID_EFF_WPLUSD_QCD__1up
  - FID_EFF_WPLUSD_QCD__1down