type: updown
affecting:
  - Sherpa2211_WplusD_Matched
  - Sherpa2211_WplusD_Matched_truth_pt_bin1
  - Sherpa2211_WplusD_Matched_truth_pt_bin2
  - Sherpa2211_WplusD_Matched_truth_pt_bin3
  - Sherpa2211_WplusD_Matched_truth_pt_bin4
  - Sherpa2211_WplusD_Matched_truth_pt_bin5
  - Sherpa2211_WplusD_Matched_truth_eta_bin1
  - Sherpa2211_WplusD_Matched_truth_eta_bin2
  - Sherpa2211_WplusD_Matched_truth_eta_bin3
  - Sherpa2211_WplusD_Matched_truth_eta_bin4
  - Sherpa2211_WplusD_Matched_truth_eta_bin5
  - Sherpa2211_Wjets_MisMatched
variations:
  - FID_EFF_WPLUSD_MG
  - FID_EFF_WPLUSD_MG_FxFx
  - FID_EFF_WPLUSD_QCD__1up
  - FID_EFF_WPLUSD_QCD__1down
  - FID_EFF_WPLUSD_PDF__1up
  - FID_EFF_WPLUSD_PDF__1down
  - FID_EFF_WPLUSD_AS__1up
  - FID_EFF_WPLUSD_AS__1down
