type: updown
affecting:
  - MG_Wjets_Charm
  - MG_Wjets_Charm_Minus
  - MG_Wjets_Charm_Plus
variations:
  - WJETS_THEORY_NOWEIGHT
  - WJETS_THEORY_ALPHA_S
  - WJETS_THEORY_PDF
  - WJETS_THEORY_QCD_SCALE
  - DPLUS_BKG_BR_Dplus
  - DPLUS_BKG_BR_Dsubs
  - DPLUS_BKG_BR_Dzero
