variablesConf: charmed_wjets

samplesConf: powheg_truth

data: Data

channels:
  include: likelihood_fit/wplusd/truth_match_el.yaml

  2018_el_wplusd_PT_Template_OS:
    regions:
      - OS_2018_el_QCD_DplusSideBand
    samples:
      - Multijet
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Template_OS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Template_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Template_OS_NoMatch
      - Other
      - Zjets_emu
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_el_wplusd_PT_Template_SS:
    regions:
      - SS_2018_el_QCD_DplusSideBand
    samples:
      - Multijet
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Template_SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Template_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Template_SS_NoMatch
      - Other
      - Zjets_emu
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_el_wplusd_PT_PreFit_OS:
    regions:
      - OS_2018_el_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_OS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_OS_NoMatch
      - Other
      - Zjets_emu
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Fit Region, Powheg'
    lumi: "2018"

  2018_el_wplusd_PT_PreFit_SS:
    regions:
      - SS_2018_el_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_SS_NoMatch
      - Other
      - Zjets_emu
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Fit Region, Powheg'
    lumi: "2018"

  2018_el_wplusd_PT_Fit_OS:
    regions:
      - OS_2018_el_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_OS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_OS
    save_to_file: True
    make_plots: False

  2018_el_wplusd_PT_Fit_SS:
    regions:
      - SS_2018_el_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_SS
    save_to_file: True
    make_plots: False

  2018_el_wplusd_PT_Extrapolated_OS:
    regions:
      - OS_2018_el_SR_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS
    save_to_file: True
    make_plots: False

  2018_el_wplusd_PT_Extrapolated_SS:
    regions:
      - SS_2018_el_SR_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_SS
    save_to_file: True
    make_plots: False

  2018_el_wplusd_OS:
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - OS_2018_el_SR_DplusSideBand
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "Powheg"
    lumi: "2018"

  2018_el_wplusd_SS:
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
    regions:
      - SS_2018_el_SR_DplusSideBand
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "Powheg"
    lumi: "2018"

  2018_el_wplusd_OS_SR:
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
    regions:
      - OS_2018_el_SR_DplusSideBand
      - OS_2018_el_SR_DplusCentral
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "Powheg"
    lumi: "2018"

  2018_el_wplusd_SS_SR:
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_SS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_el_wplusd_SS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
    regions:
      - SS_2018_el_SR_DplusSideBand
      - SS_2018_el_SR_DplusCentral
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "Powheg"
    lumi: "2018"
