variablesConf: charmed_wjets

channelVariables:
  lep_pt:
    label: lepton p_{T}
    unit: GeV
    rebin: 5
    x_range: [0, 200]
    ratio_range: [0.5, 1.49]

  Dmeson_m:
    label: 'D^{#pm} m'
    unit: 'GeV'
    rebin: 20
    ratio_range: [0.5, 1.49]

samplesConf: madgraph_truth

data: Data

channels:
  2018_el_wplusd_PT_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_Dplus
      - -SS_2018_el_QCD_Dplus
    samples:
      - Multijet
      - Wjets_emu
      - Wjets_tau
      - Top
      - Zjets
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_el_wplusd_PT_PreFit_OS-SS:
    regions:
      - OS_2018_el_Dplus
      - -SS_2018_el_Dplus
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_OS-SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_OS-SS_Rest
      - Wjets_emu_Top_NoMatch | 2018_el_wplusd_PT_Loose_OS-SS_NoMatch
      - Other
      - Zjets_emu
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Fit Region'
    lumi: "2018"

  2018_el_wplusd_PT_Fit_OS-SS:
    regions:
      - OS_2018_el_Dplus
      - -SS_2018_el_Dplus
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_OS-SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_OS-SS_Rest
      - Wjets_emu_Top_NoMatch | 2018_el_wplusd_PT_Loose_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_OS-SS
    save_to_file: True
    make_plots: False

  2018_el_wplusd_PT_Extrapolated_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS-SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS-SS_Rest
      - Wjets_emu_Top_NoMatch | 2018_el_wplusd_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS-SS
    save_to_file: True
    make_plots: False

  2018_el_wplusd_PT_Template_OS_Matched:
    regions:
      - OS_2018_el_QCD_Dplus_Matched
    make_plots: False

  2018_el_wplusd_PT_Template_SS_Matched:
    regions:
      - SS_2018_el_QCD_Dplus_Matched
    make_plots: False

  2018_el_wplusd_PT_Template_OS_NoMatch:
    regions:
      - OS_2018_el_QCD_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Template_SS_NoMatch:
    regions:
      - SS_2018_el_QCD_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Template_OS_Rest:
    regions:
      - OS_2018_el_QCD_Dplus
      - -OS_2018_el_QCD_Dplus_Matched
      - -OS_2018_el_QCD_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Template_SS_Rest:
    regions:
      - SS_2018_el_QCD_Dplus
      - -SS_2018_el_QCD_Dplus_Matched
      - -SS_2018_el_QCD_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS_Matched:
    regions:
      - OS_2018_el_Dplus_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_SS_Matched:
    regions:
      - SS_2018_el_Dplus_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_Matched:
    regions:
      - OS_2018_el_Dplus_Matched
      - -SS_2018_el_Dplus_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_OS_NoMatch:
    regions:
      - OS_2018_el_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_NoMatch:
    regions:
      - OS_2018_el_Dplus_Other
      - -SS_2018_el_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_SS_NoMatch:
    regions:
      - SS_2018_el_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS_Rest:
    regions:
      - OS_2018_el_Dplus
      - -OS_2018_el_Dplus_Matched
      - -OS_2018_el_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_SS_Rest:
    regions:
      - SS_2018_el_Dplus
      - -SS_2018_el_Dplus_Matched
      - -SS_2018_el_Dplus_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_Rest:
    regions:
      - OS_2018_el_Dplus
      - -OS_2018_el_Dplus_Matched
      - -OS_2018_el_Dplus_Other
      - -SS_2018_el_Dplus
      - SS_2018_el_Dplus_Matched
      - SS_2018_el_Dplus_Other
    make_plots: False

  2018_el_wplusd_PTCut_Template_OS:
    regions:
      - OS_2018_el_QCD_PTCut_Dplus
    make_plots: False

  2018_el_wplusd_PTCut_Template_SS:
    regions:
      - SS_2018_el_QCD_PTCut_Dplus
    make_plots: False

  2018_el_wplusd_PTCut_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_PTCut_Dplus
      - -SS_2018_el_QCD_PTCut_Dplus
    make_plots: False

  2018_el_wplusd_OS_Matched:
    regions:
      - OS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_SS_Matched:
    regions:
      - SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_OS-SS_Matched:
    regions:
      - OS_2018_el_SR_Dplus_Matched
      - -SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_OS_NoMatch:
    regions:
      - OS_2018_el_SR_Dplus_Other
    make_plots: False

  2018_el_wplusd_SS_NoMatch:
    regions:
      - SS_2018_el_SR_Dplus_Other
    make_plots: False

  2018_el_wplusd_OS-SS_NoMatch:
    regions:
      - OS_2018_el_SR_Dplus_Other
      - -SS_2018_el_SR_Dplus_Other
    make_plots: False

  2018_el_wplusd_OS_Rest:
    regions:
      - OS_2018_el_SR_Dplus
      - -OS_2018_el_SR_Dplus_Matched
      - -OS_2018_el_SR_Dplus_Other
    make_plots: False

  2018_el_wplusd_SS_Rest:
    regions:
      - SS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus_Matched
      - -SS_2018_el_SR_Dplus_Other
    make_plots: False

  2018_el_wplusd_OS-SS_Rest:
    regions:
      - OS_2018_el_SR_Dplus
      - -OS_2018_el_SR_Dplus_Matched
      - -OS_2018_el_SR_Dplus_Other
      - -SS_2018_el_SR_Dplus
      - SS_2018_el_SR_Dplus_Matched
      - SS_2018_el_SR_Dplus_Other
    make_plots: False
