colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets

channelVariables:
  lep_pt:
    label: lepton p_{T}
    unit: GeV
    rebin: 10
    x_range: [0, 200]
    ratio_range: [0.5, 1.49]

samplesConf: madgraph_truth

data: Data

channels:
  2018_el_wplusd_PT_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_Dplus
      - -SS_2018_el_QCD_Dplus
    samples:
      - Wjets_light
      - Wjets_tau
      - Top
      - Zjets
      - Diboson
      - Multijet
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet
    extra_rebin: 2

  # 2018_el_wplusd_PT_Fit_OS-SS:
  #   regions:
  #     - OS_2018_el_Dplus
  #     - -SS_2018_el_Dplus
  #   samples:
  #     - Wjets_light_Matched | 2018_el_wplusd_PT_Loose_OS-SS_Matched
  #     - Wjets_light_Rest | 2018_el_wplusd_PT_Loose_OS-SS_Rest
  #     - Wjets_tau
  #     - Top
  #     - Zjets
  #     - Multijet | 2018_el_wplusd_PT_Template_OS-SS
  #     - Diboson
  #   label:
  #      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
  #      - 'Fit Region'
  #   lumi: "2018"
  #   save_to_file: True

  # 2018_el_wplusd_PT_Extrapolated_OS-SS:
  #   regions:
  #     - OS_2018_el_SR_Dplus
  #     - -SS_2018_el_SR_Dplus
  #   samples:
  #     - Wjets_light_Matched | 2018_el_wplusd_OS-SS_Matched
  #     - Wjets_light_Rest | 2018_el_wplusd_OS-SS_Rest
  #     - Wjets_tau
  #     - Top
  #     - Zjets
  #     - Multijet | 2018_el_wplusd_PTCut_Template_OS-SS
  #     - Diboson
  #   save_to_file: True
  #   make_plots: False

  2018_el_wplusd_PTCut_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_PTCut_Dplus
      - -SS_2018_el_QCD_PTCut_Dplus
    make_plots: False

  2018_el_wplusd_OS-SS_Matched:
    regions:
      - OS_2018_el_SR_Dplus_Matched
      - -SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_OS-SS_Rest:
    regions:
      - OS_2018_el_SR_Dplus
      - -OS_2018_el_SR_Dplus_Matched
      - -SS_2018_el_SR_Dplus
      - SS_2018_el_SR_Dplus_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_Matched:
    regions:
      - OS_2018_el_Dplus_Matched
      - -SS_2018_el_Dplus_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_Rest:
    regions:
      - OS_2018_el_Dplus
      - -OS_2018_el_Dplus_Matched
      - -SS_2018_el_Dplus
      - SS_2018_el_Dplus_Matched
    make_plots: False
