variablesConf: charmed_wjets

samplesConf: madgraph_truth

data: Data

channels:
  include: likelihood_fit/wplusd/truth_match_el.yaml

  2018_el_wplusd_PT_Fit_OS:
    regions:
      - OS_2018_el_Dplus_SideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_OS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_OS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_OS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Fit Region, MadGraph'
    lumi: "2018"
    print_scale_factors: True

  2018_el_wplusd_PT_Fit_SS:
    regions:
      - SS_2018_el_Dplus_SideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_SS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Fit Region, MadGraph'
    lumi: "2018"
    print_scale_factors: True

  2018_el_wplusd_PT_Fit_OS-SS:
    regions:
      - OS_2018_el_Dplus_SideBand
      - -SS_2018_el_Dplus_SideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_PT_Loose_OS-SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_PT_Loose_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_OS-SS
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_OS
        Multijet | SS: mu_QCD_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Fit Region, MadGraph'
    lumi: "2018"
    print_scale_factors: True

  2018_el_wplusd_PT_Extrapolated_OS:
    regions:
      - OS_2018_el_SR_Dplus_SideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_extrapolated_OS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: False

  2018_el_wplusd_PT_Extrapolated_SS:
    regions:
      - SS_2018_el_SR_Dplus_SideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_SS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: True

  2018_el_wplusd_PT_Extrapolated_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus_SideBand
      - -SS_2018_el_SR_Dplus_SideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS-SS_Matched
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS-SS
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_extrapolated_OS
        Multijet | SS: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: True

  OS_2018_el_SR_Dplus:
    regions:
      - OS_2018_el_SR_Dplus_SideBand
      - OS_2018_el_SR_Dplus_Central
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS_SBplusCentral
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_extrapolated_OS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: False
    save_to_file: True

  SS_2018_el_SR_Dplus:
    regions:
      - SS_2018_el_SR_Dplus_SideBand
      - SS_2018_el_SR_Dplus_Central
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_SS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_el_wplusd_SS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_SS_SBplusCentral
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: False
    save_to_file: True

  OS-SS_2018_el_SR_Dplus:
    regions:
      - OS_2018_el_SR_Dplus_SideBand
      - OS_2018_el_SR_Dplus_Central
      - -SS_2018_el_SR_Dplus_SideBand
      - -SS_2018_el_SR_Dplus_Central
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS-SS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS-SS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS-SS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS-SS_SBplusCentral
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_extrapolated_OS
        Multijet | SS: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: False
    save_to_file: True

  2018_el_wplusd_OS-SS_Central:
    regions:
      - OS_2018_el_SR_Dplus_Central
      - -SS_2018_el_SR_Dplus_Central
    samples:
      - Wjets_emu_Top_Matched | 2018_el_wplusd_OS-SS_Matched_Central
      - Wjets_emu_Top_Rest | 2018_el_wplusd_OS-SS_Rest_Central
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS-SS_NoMatch_Central
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS-SS_Central
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_extrapolated_OS
        Multijet | SS: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: False
    save_to_file: True
