variablesConf: charmed_wjets

samplesConf: madgraph_truth

data: Data

channels:
  2018_el_wplusd_PT_Fit_OS:
    regions:
      - OS_2018_el_DplusSideBand
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_PT_Loose_OS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_PT_Loose_OS_Rest
      - Top_Matched | 2018_el_wplusd_PT_Loose_OS_Matched
      - Top_Rest | 2018_el_wplusd_PT_Loose_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_OS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
      scale_factors:
        Top_Rest: mu_Rest_OS
        Top_Matched: mu_Top_Matched_OS
        Wjets_emu_Rest: mu_Rest_OS
        Wjets_emu_Matched: mu_Wjets_emu_Matched_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_OS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Fit Region, MadGraph'
    lumi: "2018"
    print_scale_factors: True

  2018_el_wplusd_PT_Fit_SS:
    regions:
      - SS_2018_el_DplusSideBand
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_PT_Loose_SS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_PT_Loose_SS_Rest
      - Top_Matched | 2018_el_wplusd_PT_Loose_SS_Matched
      - Top_Rest | 2018_el_wplusd_PT_Loose_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_SS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Top_Rest: mu_Rest_SS
        Top_Matched: mu_Top_Matched_SS
        Wjets_emu_Rest: mu_Rest_SS
        Wjets_emu_Matched: mu_Wjets_emu_Matched_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Fit Region, MadGraph'
    lumi: "2018"
    print_scale_factors: True

  2018_el_wplusd_PT_Fit_OS-SS:
    regions:
      - OS_2018_el_DplusSideBand
      - -SS_2018_el_DplusSideBand
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_PT_Loose_OS-SS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_PT_Loose_OS-SS_Rest
      - Top_Matched | 2018_el_wplusd_PT_Loose_OS-SS_Matched
      - Top_Rest | 2018_el_wplusd_PT_Loose_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_PT_Loose_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PT_Template_OS-SS
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Top_Rest | OS: mu_Rest_OS
        Top_Rest | SS: mu_Rest_SS
        Top_Matched | OS: mu_Top_Matched_OS
        Top_Matched | SS: mu_Top_Matched_SS
        Wjets_emu_Rest | OS: mu_Rest_OS
        Wjets_emu_Rest | SS: mu_Rest_SS
        Wjets_emu_Matched | OS: mu_Wjets_emu_Matched_OS
        Wjets_emu_Matched | SS: mu_Wjets_emu_Matched_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_OS
        Multijet | SS: mu_QCD_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Fit Region, MadGraph'
    lumi: "2018"
    print_scale_factors: True

  2018_el_wplusd_PT_Extrapolated_OS:
    regions:
      - OS_2018_el_SR_DplusSideBand
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_OS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_OS_Rest
      - Top_Matched | 2018_el_wplusd_OS_Matched
      - Top_Rest | 2018_el_wplusd_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
      scale_factors:
        Top_Rest: mu_Rest_OS
        Top_Matched: mu_Top_Matched_OS
        Wjets_emu_Rest: mu_Rest_OS
        Wjets_emu_Matched: mu_Wjets_emu_Matched_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_extrapolated_OS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: True

  2018_el_wplusd_PT_Extrapolated_SS:
    regions:
      - SS_2018_el_SR_DplusSideBand
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_SS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_SS_Rest
      - Top_Matched | 2018_el_wplusd_SS_Matched
      - Top_Rest | 2018_el_wplusd_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_SS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Top_Rest: mu_Rest_SS
        Top_Matched: mu_Top_Matched_SS
        Wjets_emu_Rest: mu_Rest_SS
        Wjets_emu_Matched: mu_Wjets_emu_Matched_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: True

  2018_el_wplusd_PT_Extrapolated_OS-SS:
    regions:
      - OS_2018_el_SR_DplusSideBand
      - -SS_2018_el_SR_DplusSideBand
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_OS-SS_Matched
      - Wjets_emu_Rest | 2018_el_wplusd_OS-SS_Rest
      - Top_Matched | 2018_el_wplusd_OS-SS_Matched
      - Top_Rest | 2018_el_wplusd_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS-SS
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Top_Rest | OS: mu_Rest_OS
        Top_Rest | SS: mu_Rest_SS
        Top_Matched | OS: mu_Top_Matched_OS
        Top_Matched | SS: mu_Top_Matched_SS
        Wjets_emu_Rest | OS: mu_Rest_OS
        Wjets_emu_Rest | SS: mu_Rest_SS
        Wjets_emu_Matched | OS: mu_Wjets_emu_Matched_OS
        Wjets_emu_Matched | SS: mu_Wjets_emu_Matched_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_extrapolated_OS
        Multijet | SS: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: True

  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR_DplusSideBand
      - OS_2018_el_SR_DplusCentral
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_OS_Matched_SBplusCentral
      - Wjets_emu_Rest | 2018_el_wplusd_OS_Rest_SBplusCentral
      - Top_Matched | 2018_el_wplusd_OS_Matched_SBplusCentral
      - Top_Rest | 2018_el_wplusd_OS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_el_wplusd_OS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_OS_SBplusCentral
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_OS.json
      scale_factors:
        Top_Rest: mu_Rest_OS
        Top_Matched: mu_Top_Matched_OS
        Wjets_emu_Rest: mu_Rest_OS
        Wjets_emu_Matched: mu_Wjets_emu_Matched_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_extrapolated_OS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: True

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR_DplusSideBand
      - SS_2018_el_SR_DplusCentral
    samples:
      - Wjets_emu_Matched | 2018_el_wplusd_SS_Matched_SBplusCentral
      - Wjets_emu_Rest | 2018_el_wplusd_SS_Rest_SBplusCentral
      - Top_Matched | 2018_el_wplusd_SS_Matched_SBplusCentral
      - Top_Rest | 2018_el_wplusd_SS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_el_wplusd_SS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_el_wplusd_PTCut_Template_SS_SBplusCentral
    scale_factors:
      input_file: likelihood_fit/wplusd/export_madgraph_truth_el_SB/2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Top_Rest: mu_Rest_SS
        Top_Matched: mu_Top_Matched_SS
        Wjets_emu_Rest: mu_Rest_SS
        Wjets_emu_Matched: mu_Wjets_emu_Matched_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Signal Region, MadGraph'
    lumi: '2018'
    print_scale_factors: True

  2018_el_wplusd_PT_Template_OS:
    regions:
      - OS_2018_el_QCD_DplusSideBand
    make_plots: False

  2018_el_wplusd_PT_Template_SS:
    regions:
      - SS_2018_el_QCD_DplusSideBand
    make_plots: False

  2018_el_wplusd_PT_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_DplusSideBand
      - -SS_2018_el_QCD_DplusSideBand
    make_plots: False

  2018_el_wplusd_PT_Template_OS_Matched:
    regions:
      - OS_2018_el_QCD_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_PT_Template_SS_Matched:
    regions:
      - SS_2018_el_QCD_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_PT_Template_OS_NoMatch:
    regions:
      - OS_2018_el_QCD_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Template_SS_NoMatch:
    regions:
      - SS_2018_el_QCD_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Template_OS_Rest:
    regions:
      - OS_2018_el_QCD_DplusSideBand
      - -OS_2018_el_QCD_DplusSideBand_Matched
      - -OS_2018_el_QCD_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Template_SS_Rest:
    regions:
      - SS_2018_el_QCD_DplusSideBand
      - -SS_2018_el_QCD_DplusSideBand_Matched
      - -SS_2018_el_QCD_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS_Matched:
    regions:
      - OS_2018_el_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_SS_Matched:
    regions:
      - SS_2018_el_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_Matched:
    regions:
      - OS_2018_el_DplusSideBand_Matched
      - -SS_2018_el_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_PT_Loose_OS_NoMatch:
    regions:
      - OS_2018_el_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_SS_NoMatch:
    regions:
      - SS_2018_el_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_NoMatch:
    regions:
      - OS_2018_el_DplusSideBand_Other
      - -SS_2018_el_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS_Rest:
    regions:
      - OS_2018_el_DplusSideBand
      - -OS_2018_el_DplusSideBand_Matched
      - -OS_2018_el_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_SS_Rest:
    regions:
      - SS_2018_el_DplusSideBand
      - -SS_2018_el_DplusSideBand_Matched
      - -SS_2018_el_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PT_Loose_OS-SS_Rest:
    regions:
      - OS_2018_el_DplusSideBand
      - -OS_2018_el_DplusSideBand_Matched
      - -OS_2018_el_DplusSideBand_Other
      - -SS_2018_el_DplusSideBand
      - SS_2018_el_DplusSideBand_Matched
      - SS_2018_el_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_PTCut_Template_OS:
    regions:
      - OS_2018_el_QCD_PTCut_DplusSideBand
    make_plots: False

  2018_el_wplusd_PTCut_Template_SS:
    regions:
      - SS_2018_el_QCD_PTCut_DplusSideBand
    make_plots: False

  2018_el_wplusd_PTCut_Template_OS_SBplusCentral:
    regions:
      - OS_2018_el_QCD_PTCut_DplusSideBand
      - OS_2018_el_QCD_PTCut_DplusCentral
    make_plots: False

  2018_el_wplusd_PTCut_Template_SS_SBplusCentral:
    regions:
      - SS_2018_el_QCD_PTCut_DplusSideBand
      - SS_2018_el_QCD_PTCut_DplusCentral
    make_plots: False

  2018_el_wplusd_PTCut_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_PTCut_DplusSideBand
      - -SS_2018_el_QCD_PTCut_DplusSideBand
    make_plots: False

  2018_el_wplusd_OS_Matched:
    regions:
      - OS_2018_el_SR_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_OS_Matched_SBplusCentral:
    regions:
      - OS_2018_el_SR_DplusSideBand_Matched
      - OS_2018_el_SR_DplusCentral_Matched
    make_plots: False

  2018_el_wplusd_SS_Matched:
    regions:
      - SS_2018_el_SR_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_SS_Matched_SBplusCentral:
    regions:
      - SS_2018_el_SR_DplusSideBand_Matched
      - SS_2018_el_SR_DplusCentral_Matched
    make_plots: False

  2018_el_wplusd_OS-SS_Matched:
    regions:
      - OS_2018_el_SR_DplusSideBand_Matched
      - -SS_2018_el_SR_DplusSideBand_Matched
    make_plots: False

  2018_el_wplusd_OS_NoMatch:
    regions:
      - OS_2018_el_SR_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_SS_NoMatch:
    regions:
      - SS_2018_el_SR_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_OS_NoMatch_SBplusCentral:
    regions:
      - OS_2018_el_SR_DplusSideBand_Other
      - OS_2018_el_SR_DplusCentral_Other
    make_plots: False

  2018_el_wplusd_SS_NoMatch_SBplusCentral:
    regions:
      - SS_2018_el_SR_DplusSideBand_Other
      - SS_2018_el_SR_DplusCentral_Other
    make_plots: False

  2018_el_wplusd_OS-SS_NoMatch:
    regions:
      - OS_2018_el_SR_DplusSideBand_Other
      - -SS_2018_el_SR_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_OS_Rest:
    regions:
      - OS_2018_el_SR_DplusSideBand
      - -OS_2018_el_SR_DplusSideBand_Matched
      - -OS_2018_el_SR_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_OS_Rest_SBplusCentral:
    regions:
      - OS_2018_el_SR_DplusSideBand
      - -OS_2018_el_SR_DplusSideBand_Matched
      - -OS_2018_el_SR_DplusSideBand_Other
      - OS_2018_el_SR_DplusCentral
      - -OS_2018_el_SR_DplusCentral_Matched
      - -OS_2018_el_SR_DplusCentral_Other
    make_plots: False

  2018_el_wplusd_SS_Rest:
    regions:
      - SS_2018_el_SR_DplusSideBand
      - -SS_2018_el_SR_DplusSideBand_Matched
      - -SS_2018_el_SR_DplusSideBand_Other
    make_plots: False

  2018_el_wplusd_SS_Rest_SBplusCentral:
    regions:
      - SS_2018_el_SR_DplusSideBand
      - -SS_2018_el_SR_DplusSideBand_Matched
      - -SS_2018_el_SR_DplusSideBand_Other
      - SS_2018_el_SR_DplusCentral
      - -SS_2018_el_SR_DplusCentral_Matched
      - -SS_2018_el_SR_DplusCentral_Other
    make_plots: False

  2018_el_wplusd_OS-SS_Rest:
    regions:
      - OS_2018_el_SR_DplusSideBand
      - -OS_2018_el_SR_DplusSideBand_Matched
      - -OS_2018_el_SR_DplusSideBand_Other
      - -SS_2018_el_SR_DplusSideBand
      - SS_2018_el_SR_DplusSideBand_Matched
      - SS_2018_el_SR_DplusSideBand_Other
    make_plots: False
