variablesConf: charmed_wjets

samplesConf: sherpa_truth

data: Data

channels:
  include: likelihood_fit/wplusd/truth_match_mu.yaml

  2018_mu_wplusd_PT_Fit_OS:
    regions:
      - OS_2018_mu_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_PT_Loose_OS_Matched
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_PT_Loose_OS_Rest
      - Wjets_emu_NoMatch | 2018_mu_wplusd_PT_Loose_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PT_Template_OS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_OS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_OS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Fit Region, Sherpa'
    lumi: "2018"
    print_scale_factors: True

  2018_mu_wplusd_PT_Fit_SS:
    regions:
      - SS_2018_mu_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_PT_Loose_SS_Matched
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_PT_Loose_SS_Rest
      - Wjets_emu_NoMatch | 2018_mu_wplusd_PT_Loose_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PT_Template_SS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_SS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Fit Region, Sherpa'
    lumi: "2018"
    print_scale_factors: True

  2018_mu_wplusd_PT_Fit_OS-SS:
    regions:
      - OS_2018_mu_DplusSideBand
      - -SS_2018_mu_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_PT_Loose_OS-SS_Matched
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_PT_Loose_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_mu_wplusd_PT_Loose_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PT_Template_OS-SS
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_OS
        Multijet | SS: mu_QCD_SS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Fit Region, Sherpa'
    lumi: "2018"
    print_scale_factors: True

  2018_mu_wplusd_PT_Extrapolated_OS:
    regions:
      - OS_2018_mu_SR_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_OS_Matched
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_OS_Rest
      - Wjets_emu_NoMatch | 2018_mu_wplusd_OS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PTCut_Template_OS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_OS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_extrapolated_OS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Signal Region, Sherpa'
    lumi: '2018'
    print_scale_factors: False

  2018_mu_wplusd_PT_Extrapolated_SS:
    regions:
      - SS_2018_mu_SR_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_SS_Matched
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_SS_Rest
      - Wjets_emu_NoMatch | 2018_mu_wplusd_SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PTCut_Template_SS
    scale_factors:
      input_file: likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Signal Region, Sherpa'
    lumi: '2018'
    print_scale_factors: True

  2018_mu_wplusd_PT_Extrapolated_OS-SS:
    regions:
      - OS_2018_mu_SR_DplusSideBand
      - -SS_2018_mu_SR_DplusSideBand
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_OS-SS_Matched
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_mu_wplusd_OS-SS_NoMatch
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PTCut_Template_OS-SS
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_extrapolated_OS
        Multijet | SS: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Signal Region, Sherpa'
    lumi: '2018'
    print_scale_factors: True

  2018_mu_wplusd_OS:
    regions:
      - OS_2018_mu_SR_DplusSideBand
      - OS_2018_mu_SR_DplusCentral
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_OS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_OS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_mu_wplusd_OS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PTCut_Template_OS_SBplusCentral
    scale_factors:
      input_file: likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_OS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_OS
        Multijet: mu_QCD_extrapolated_OS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
       - 'Signal Region, Sherpa'
    lumi: '2018'
    print_scale_factors: False

  2018_mu_wplusd_SS:
    regions:
      - SS_2018_mu_SR_DplusSideBand
      - SS_2018_mu_SR_DplusCentral
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_SS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_SS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_mu_wplusd_SS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PTCut_Template_SS_SBplusCentral
    scale_factors:
      input_file: likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch: mu_Wjets_emu_NoMatch_SS
        Multijet: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
       - 'Signal Region, Sherpa'
    lumi: '2018'
    print_scale_factors: False

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR_DplusSideBand
      - OS_2018_mu_SR_DplusCentral
      - -SS_2018_mu_SR_DplusSideBand
      - -SS_2018_mu_SR_DplusCentral
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_OS-SS_Matched_SBplusCentral
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_OS-SS_Rest_SBplusCentral
      - Wjets_emu_NoMatch | 2018_mu_wplusd_OS-SS_NoMatch_SBplusCentral
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PTCut_Template_OS-SS_SBplusCentral
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_extrapolated_OS
        Multijet | SS: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Signal Region, Sherpa'
    lumi: '2018'
    print_scale_factors: False

  2018_mu_wplusd_OS-SS_Central:
    regions:
      - OS_2018_mu_SR_DplusCentral
      - -SS_2018_mu_SR_DplusCentral
    samples:
      - Wjets_emu_Top_Matched | 2018_mu_wplusd_OS-SS_Matched_Central
      - Wjets_emu_Top_Rest | 2018_mu_wplusd_OS-SS_Rest_Central
      - Wjets_emu_NoMatch | 2018_mu_wplusd_OS-SS_NoMatch_Central
      - Other
      - Zjets_emu
      - Multijet | 2018_mu_wplusd_PTCut_Template_OS-SS_Central
    scale_factors:
      input_file:
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_OS.json
        - likelihood_fit/wplusd/export_sherpa_truth_mu_SB/2018_mu_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_emu_Top_Rest | OS: mu_Wjets_emu_Top_Rest_OS
        Wjets_emu_Top_Rest | SS: mu_Wjets_emu_Top_Rest_SS
        Wjets_emu_NoMatch | OS: mu_Wjets_emu_NoMatch_OS
        Wjets_emu_NoMatch | SS: mu_Wjets_emu_NoMatch_SS
        Multijet | OS: mu_QCD_extrapolated_OS
        Multijet | SS: mu_QCD_extrapolated_SS
    label:
       - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
       - 'Signal Region, Sherpa'
    lumi: '2018'
    print_scale_factors: False