colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets_os-ss

samplesConf: common

data: Data

samples:
  - Powheg_Wjets
  - Sherpa_Zjets
  - Top
  - Diboson

channels:
  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_el_wplusd_MET_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_Dplus
      - -SS_2018_el_QCD_Dplus
    samples:
      - Multijet_Powheg
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet_Powheg

  2018_el_wplusd_MET_Loose_OS-SS:
    regions:
      - OS_2018_mu_Dplus
      - -SS_2018_mu_Dplus
    samples:
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
      - 'Loose SR for MET fit'
    lumi: '2018'

  2018_el_wplusd_MET_Fit_OS-SS:
    regions:
      - OS_2018_mu_Dplus
      - -SS_2018_mu_Dplus
    samples:
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_el_wplusd_MET_Template_OS-SS
      - Diboson
    likelihood_fit:
      variable: met_met
      range: [0, 50]
      extrapolated_region: 2018_el_wplusd_MET_Extrapolated_OS-SS
      extrapolated_multijet: 2018_el_wplusd_METCut_Template_OS-SS
      fixed:
        - Sherpa_Zjets
        - Top
        - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
      - 'Likelihood MET fit'
    lumi: '2018'

  2018_el_wplusd_MET_Extrapolated_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    samples:
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_el_wplusd_METCut_Template_OS-SS
      - Diboson
    scale_factors:
      input_file: 2018_el_wplusd_MET_Fit_OS-SS.json
      scale_factors:
        Powheg_Wjets: Powheg_Wjets
        Sherpa_Zjets: Sherpa_Zjets
        Top: Top
        Diboson: Diboson
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_el_wplusd_METCut_Template_OS-SS:
    regions:
      - OS_2018_el_QCD_METCut_Dplus
      - -SS_2018_el_QCD_METCut_Dplus
    make_plots: False
