colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets

samplesConf: powheg

data: Data

samples:
  - Wjets_light
  - Wjets_tau
  - Zjets
  - Top
  - Diboson

channels:
  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR_Dplus
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR_Dplus
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_el_wplusd_PT_Template_OS:
    regions:
      - OS_2018_el_QCD_Dplus
    samples:
      - Multijet
      - Wjets_light
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_el_wplusd_PT_Template_SS:
    regions:
      - SS_2018_el_QCD_Dplus
    samples:
      - Multijet
      - Wjets_light
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_el_wplusd_PT_Loose_OS:
    regions:
      - OS_2018_el_Dplus
    samples:
      - Wjets_light
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
      - 'Loose SR for PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Loose_SS:
    regions:
      - SS_2018_el_Dplus
    samples:
      - Wjets_light
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
      - 'Loose SR for PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Fit_OS:
    regions:
      - OS_2018_el_Dplus
    samples:
      - Wjets
      - Top
      - Zjets
      - Multijet | 2018_el_wplusd_PT_Template_OS
      - Diboson
    likelihood_fit:
      variable: lep_pt
      range: [28, 100]
      extrapolated_region: 2018_el_wplusd_PT_Extrapolated_OS
      extrapolated_multijet: 2018_el_wplusd_PTCut_Template_OS
      fixed:
        - Diboson
        - Zjets
        - Top
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
      - 'Likelihood PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Fit_SS:
    regions:
      - SS_2018_el_Dplus
    samples:
      - Wjets
      - Top
      - Zjets
      - Multijet | 2018_el_wplusd_PT_Template_SS
      - Diboson
    likelihood_fit:
      variable: lep_pt
      range: [28, 100]
      extrapolated_region: 2018_el_wplusd_PT_Extrapolated_SS
      extrapolated_multijet: 2018_el_wplusd_PTCut_Template_SS
      fixed:
        - Diboson
        - Zjets
        - Top
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
      - 'Likelihood PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Extrapolated_OS:
    regions:
      - OS_2018_el_SR_Dplus
    samples:
      - Wjets_light
      - Wjets_tau
      - Zjets
      - Top
      - Multijet | 2018_el_wplusd_PTCut_Template_OS
      - Diboson
    scale_factors:
      input_file: 2018_el_wplusd_PT_Fit_OS.json
      scale_factors:
        Wjets_light: Wjets
        Wjets_tau: Wjets
        Zjets: Zjets
        Top: Top
        Diboson: Diboson
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_el_wplusd_PT_Extrapolated_SS:
    regions:
      - SS_2018_el_SR_Dplus
    samples:
      - Wjets_light
      - Wjets_tau
      - Zjets
      - Top
      - Multijet | 2018_el_wplusd_PTCut_Template_SS
      - Diboson
    scale_factors:
      input_file: 2018_el_wplusd_PT_Fit_SS.json
      scale_factors:
        Wjets_light: Wjets
        Wjets_tau: Wjets
        Zjets: Zjets
        Top: Top
        Diboson: Diboson
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_el_wplusd_PTCut_Template_OS:
    regions:
      - OS_2018_el_QCD_PTCut_Dplus
    make_plots: False

  2018_el_wplusd_PTCut_Template_SS:
    regions:
      - SS_2018_el_QCD_PTCut_Dplus
    make_plots: False
