colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets

samplesConf: common

data: Data

samples:
  - Powheg_Wjets_light
  - Powheg_Wjets_tau
  - Sherpa_Zjets
  - Top
  - Diboson

channels:
  2018_mu_wplusd_OS:
    regions:
      - OS_2018_mu_SR
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_mu_wplusd_SS:
    regions:
      - SS_2018_mu_SR
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR
      - -SS_2018_mu_SR
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_mu_wplusd_MET_Template_OS:
    regions:
      - OS_2018_mu_QCD
    samples:
      - Multijet_Powheg
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet_Powheg

  2018_mu_wplusd_MET_Template_SS:
    regions:
      - SS_2018_mu_QCD
    samples:
      - Multijet_Powheg
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet_Powheg

  2018_mu_wplusd_MET_Loose_OS:
    regions:
      - OS_2018_mu
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
      - 'Loose SR for MET fit'
    lumi: '2018'

  2018_mu_wplusd_MET_Loose_SS:
    regions:
      - SS_2018_mu
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
      - 'Loose SR for MET fit'
    lumi: '2018'

  2018_mu_wplusd_MET_Fit_OS:
    regions:
      - OS_2018_mu
    samples:
      - Powheg_Wjets
      - Top
      - Sherpa_Zjets
      - Multijet_Powheg | 2018_mu_wplusd_MET_Template_OS
      - Diboson
    likelihood_fit:
      variable: met_met
      range: [0, 155]
      extrapolated_region: 2018_mu_wplusd_MET_Extrapolated_OS
      extrapolated_multijet: 2018_mu_wplusd_METCut_Template_OS
      fixed:
        - Diboson
        - Sherpa_Zjets
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
      - 'Likelihood MET fit'
    lumi: '2018'

  2018_mu_wplusd_MET_Fit_SS:
    regions:
      - SS_2018_mu
    samples:
      - Powheg_Wjets
      - Top
      - Sherpa_Zjets
      - Multijet_Powheg | 2018_mu_wplusd_MET_Template_SS
      - Diboson
    likelihood_fit:
      variable: met_met
      range: [0, 140]
      extrapolated_region: 2018_mu_wplusd_MET_Extrapolated_SS
      extrapolated_multijet: 2018_mu_wplusd_METCut_Template_SS
      fixed:
        - Diboson
        - Sherpa_Zjets
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
      - 'Likelihood MET fit'
    lumi: '2018'

  2018_mu_wplusd_MET_Extrapolated_OS:
    regions:
      - OS_2018_mu_SR
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_mu_wplusd_METCut_Template_OS
      - Diboson
    scale_factors:
      input_file: 2018_mu_wplusd_MET_Fit_OS.json
      scale_factors:
        Powheg_Wjets_light: Powheg_Wjets
        Powheg_Wjets_tau: Powheg_Wjets
        Sherpa_Zjets: Sherpa_Zjets
        Top: Top
        Diboson: Diboson
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_mu_wplusd_MET_Extrapolated_SS:
    regions:
      - SS_2018_mu_SR
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_mu_wplusd_METCut_Template_SS
      - Diboson
    scale_factors:
      input_file: 2018_mu_wplusd_MET_Fit_SS.json
      scale_factors:
        Powheg_Wjets_light: Powheg_Wjets
        Powheg_Wjets_tau: Powheg_Wjets
        Sherpa_Zjets: Sherpa_Zjets
        Top: Top
        Diboson: Diboson
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_mu_wplusd_METCut_Template_OS:
    regions:
      - OS_2018_mu_QCD_METCut
    make_plots: False

  2018_mu_wplusd_METCut_Template_SS:
    regions:
      - SS_2018_mu_QCD_METCut
    make_plots: False
