colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets_os-ss

channelsVariables:
  met_met:
    label: MET
    unit: GeV
    rebin: 20
    x_range: [0, 100]
    ratio_range: [0.5, 1.49]

samplesConf: common

data: Data

samples:
  - Powheg_Wjets_light
  - Powheg_Wjets_tau
  - Sherpa_Zjets
  - Top
  - Diboson

channels:
  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus
    label: "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
    lumi: "2018"

  2018_mu_wplusd_MET_Template_OS-SS:
    regions:
      - OS_2018_mu_QCD_Dplus
      - -SS_2018_mu_QCD_Dplus
    samples:
      - Multijet_Powheg
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MET < 30 GeV, no m_{T} cut"
    lumi: "2018"
    qcd_template: Multijet_Powheg

  2018_mu_wplusd_MET_Loose_OS-SS:
    regions:
      - OS_2018_mu_Dplus
      - -SS_2018_mu_Dplus
    samples:
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "Loose SR for MET fit"
    lumi: "2018"

  2018_mu_wplusd_MET_Fit_OS-SS:
    regions:
      - OS_2018_mu_Dplus
      - -SS_2018_mu_Dplus
    samples:
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_mu_wplusd_MET_Template_OS-SS
      - Diboson
    likelihood_fit:
      variable: met_met
      range: [0, 80]
      extrapolated_region: 2018_mu_wplusd_MET_Extrapolated_OS-SS
      extrapolated_multijet: 2018_mu_wplusd_METCut_Template_OS-SS
      fixed:
        - Top
        - Diboson
        - Sherpa_Zjets
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "Likelihood MET fit"
    lumi: "2018"

  2018_mu_wplusd_MET_Extrapolated_OS-SS:
    regions:
      - OS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus
    samples:
      - Powheg_Wjets
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_mu_wplusd_METCut_Template_OS-SS
      - Diboson
    scale_factors:
      input_file: 2018_mu_wplusd_MET_Fit_OS-SS.json
      scale_factors:
        Powheg_Wjets: Powheg_Wjets
        Sherpa_Zjets: Sherpa_Zjets
        Top: Top
        Diboson: Diboson
    label: "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
    lumi: "2018"

  2018_mu_wplusd_METCut_Template_OS-SS:
    regions:
      - OS_2018_mu_QCD_METCut_Dplus
      - -SS_2018_mu_QCD_METCut_Dplus
    make_plots: False
