variablesConf: charmed_wjets

samplesConf: wdplus_jets_mc_mc

channels:
  OS-SS_0tag_inclusive_has_jet:
    regions:
      - el_minus_SR_0tag_Dplus_OS_has_jet_bin1
      - el_plus_SR_0tag_Dplus_OS_has_jet_bin1
      - mu_minus_SR_0tag_Dplus_OS_has_jet_bin1
      - mu_plus_SR_0tag_Dplus_OS_has_jet_bin1
      - el_minus_SR_0tag_Dplus_OS_has_jet_bin2
      - el_plus_SR_0tag_Dplus_OS_has_jet_bin2
      - mu_minus_SR_0tag_Dplus_OS_has_jet_bin2
      - mu_plus_SR_0tag_Dplus_OS_has_jet_bin2
      - el_minus_SR_0tag_Dplus_OS_has_jet_bin3
      - el_plus_SR_0tag_Dplus_OS_has_jet_bin3
      - mu_minus_SR_0tag_Dplus_OS_has_jet_bin3
      - mu_plus_SR_0tag_Dplus_OS_has_jet_bin3
      - el_minus_SR_0tag_Dplus_OS_has_jet_bin4
      - el_plus_SR_0tag_Dplus_OS_has_jet_bin4
      - mu_minus_SR_0tag_Dplus_OS_has_jet_bin4
      - mu_plus_SR_0tag_Dplus_OS_has_jet_bin4
      - -el_minus_SR_0tag_Dplus_SS_has_jet_bin1
      - -el_plus_SR_0tag_Dplus_SS_has_jet_bin1
      - -mu_minus_SR_0tag_Dplus_SS_has_jet_bin1
      - -mu_plus_SR_0tag_Dplus_SS_has_jet_bin1
      - -el_minus_SR_0tag_Dplus_SS_has_jet_bin2
      - -el_plus_SR_0tag_Dplus_SS_has_jet_bin2
      - -mu_minus_SR_0tag_Dplus_SS_has_jet_bin2
      - -mu_plus_SR_0tag_Dplus_SS_has_jet_bin2
      - -el_minus_SR_0tag_Dplus_SS_has_jet_bin3
      - -el_plus_SR_0tag_Dplus_SS_has_jet_bin3
      - -mu_minus_SR_0tag_Dplus_SS_has_jet_bin3
      - -mu_plus_SR_0tag_Dplus_SS_has_jet_bin3
      - -el_minus_SR_0tag_Dplus_SS_has_jet_bin4
      - -el_plus_SR_0tag_Dplus_SS_has_jet_bin4
      - -mu_minus_SR_0tag_Dplus_SS_has_jet_bin4
      - -mu_plus_SR_0tag_Dplus_SS_has_jet_bin4
    samples:
      - MG_Wjets_Matched_emu
      - Sh_2211_Wjets_Matched_emu
    label:
      - "W#rightarrowl#nu+D, D#rightarrowK#pi#pi, 0 tag"
      - "OS-SS, Isolation cut: OFF"
    lumi: "2015+2016A-B+2016C-L+2017+2018"

  OS-SS_1tag_inclusive_has_jet:
    regions:
      - el_minus_SR_1tag_Dplus_OS_has_jet_bin1
      - el_plus_SR_1tag_Dplus_OS_has_jet_bin1
      - mu_minus_SR_1tag_Dplus_OS_has_jet_bin1
      - mu_plus_SR_1tag_Dplus_OS_has_jet_bin1
      - el_minus_SR_1tag_Dplus_OS_has_jet_bin2
      - el_plus_SR_1tag_Dplus_OS_has_jet_bin2
      - mu_minus_SR_1tag_Dplus_OS_has_jet_bin2
      - mu_plus_SR_1tag_Dplus_OS_has_jet_bin2
      - el_minus_SR_1tag_Dplus_OS_has_jet_bin3
      - el_plus_SR_1tag_Dplus_OS_has_jet_bin3
      - mu_minus_SR_1tag_Dplus_OS_has_jet_bin3
      - mu_plus_SR_1tag_Dplus_OS_has_jet_bin3
      - el_minus_SR_1tag_Dplus_OS_has_jet_bin4
      - el_plus_SR_1tag_Dplus_OS_has_jet_bin4
      - mu_minus_SR_1tag_Dplus_OS_has_jet_bin4
      - mu_plus_SR_1tag_Dplus_OS_has_jet_bin4
      - -el_minus_SR_1tag_Dplus_SS_has_jet_bin1
      - -el_plus_SR_1tag_Dplus_SS_has_jet_bin1
      - -mu_minus_SR_1tag_Dplus_SS_has_jet_bin1
      - -mu_plus_SR_1tag_Dplus_SS_has_jet_bin1
      - -el_minus_SR_1tag_Dplus_SS_has_jet_bin2
      - -el_plus_SR_1tag_Dplus_SS_has_jet_bin2
      - -mu_minus_SR_1tag_Dplus_SS_has_jet_bin2
      - -mu_plus_SR_1tag_Dplus_SS_has_jet_bin2
      - -el_minus_SR_1tag_Dplus_SS_has_jet_bin3
      - -el_plus_SR_1tag_Dplus_SS_has_jet_bin3
      - -mu_minus_SR_1tag_Dplus_SS_has_jet_bin3
      - -mu_plus_SR_1tag_Dplus_SS_has_jet_bin3
      - -el_minus_SR_1tag_Dplus_SS_has_jet_bin4
      - -el_plus_SR_1tag_Dplus_SS_has_jet_bin4
      - -mu_minus_SR_1tag_Dplus_SS_has_jet_bin4
      - -mu_plus_SR_1tag_Dplus_SS_has_jet_bin4
    samples:
      - MG_Wjets_Matched_emu
      - Sh_2211_Wjets_Matched_emu
    label:
      - "W#rightarrowl#nu+D, D#rightarrowK#pi#pi, 1 tag"
      - "OS-SS, Isolation cut: OFF"
    lumi: "2015+2016A-B+2016C-L+2017+2018"
