Dmeson_m:
  label: 'D^{#pm} m'
  unit: 'GeV'
  rebin: 2
  x_range: [1.7, 2.2]
  ratio_range: [0.5, 1.49]

Dmeson_m_fit:
  name_override: Dmeson_m
  label: 'D^{#pm} m'
  unit: 'GeV'
  x_range: [1.7, 2.2]
  # xbins: [1.7, 1.75, 1.775, 1.8, 1.825, 1.85, 1.875, 1.9, 1.925, 1.95, 1.975, 2.0, 2.1, 2.2]
  xbins: [1.7, 1.775, 1.8, 1.825, 1.85, 1.875, 1.9, 1.925, 1.95, 2.0, 2.2]
  ratio_range: [0.5, 1.49]
  per_unit: True

Dmeson_m0:
  label: 'D^{#pm} m0'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m1:
  label: 'D^{#pm} m1'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m2:
  label: 'D^{#pm} m2'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m3:
  label: 'D^{#pm} m3'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m4:
  label: 'D^{#pm} m4'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m5:
  label: 'D^{#pm} m5'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m6:
  label: 'D^{#pm} m6'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m7:
  label: 'D^{#pm} m7'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m8:
  label: 'D^{#pm} m8'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m9:
  label: 'D^{#pm} m9'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_pt:
  label: 'D^{#pm} p_{T}'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt0:
  label: 'D^{#pm} p_{T}0'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt1:
  label: 'D^{#pm} p_{T}1'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt2:
  label: 'D^{#pm} p_{T}2'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt3:
  label: 'D^{#pm} p_{T}3'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt4:
  label: 'D^{#pm} p_{T}4'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt5:
  label: 'D^{#pm} p_{T}5'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt6:
  label: 'D^{#pm} p_{T}6'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt7:
  label: 'D^{#pm} p_{T}7'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt8:
  label: 'D^{#pm} p_{T}8'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt9:
  label: 'D^{#pm} p_{T}9'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta:
  label: 'D^{#pm} #eta'
  rebin: 5
  ratio_range: [0.5, 1.49]

Dmeson_eta0:
  label: 'D^{#pm} #eta0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta1:
  label: 'D^{#pm} #eta1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta2:
  label: 'D^{#pm} #eta2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta3:
  label: 'D^{#pm} #eta3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta4:
  label: 'D^{#pm} #eta4'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta5:
  label: 'D^{#pm} #eta5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta6:
  label: 'D^{#pm} #eta6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta7:
  label: 'D^{#pm} #eta7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta8:
  label: 'D^{#pm} #eta8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta9:
  label: 'D^{#pm} #eta9'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_phi:
  label: 'D^{#pm} #phi'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_Lxy:
  label: 'D^{#pm} L_{xy}'
  unit: 'mm'
  rebin: 5
  x_range: [0.0, 30]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy_in_SB:
  label: 'D^{#pm} L_{xy}'
  unit: 'mm'
  rebin: 1
  x_range: [20., 30.]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy_out_SB:
  label: 'D^{#pm} L_{xy}'
  unit: 'mm'
  rebin: 1
  x_range: [20., 30.]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy0:
  label: 'D^{#pm} L_{xy}0'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy1:
  label: 'D^{#pm} L_{xy}1'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy2:
  label: 'D^{#pm} L_{xy}2'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy3:
  label: 'D^{#pm} L_{xy}3'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy4:
  label: 'D^{#pm} L_{xy}4'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_impactSig:
  label: 'D^{#pm} 3D Impact Significance'
  rebin: 1
  x_range: [0.0, 10.0]
  ratio_range: [0.5, 1.49]

Dmeson_impactSig_in_SB:
  label: 'D^{#pm} 3D Impact Significance'
  rebin: 1
  x_range: [0.0, 10.0]
  ratio_range: [0.5, 1.49]

Dmeson_impactSig_out_SB:
  label: 'D^{#pm} 3D Impact Significance'
  rebin: 1
  x_range: [0.0, 10.0]
  ratio_range: [0.5, 1.49]

Dmeson_z0sinTheta:
  label: 'D^{#pm} z_{0}sin(#theta)'
  unit: 'mm'
  ratio_range: [0.0, 1.99]

Dmeson_cTau:
  label: 'D^{#pm} c#tau'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi2:
  label: 'D^{#pm} #chi^{2}'
  rebin: 4
  ratio_range: [0.5, 1.49]

Dmeson_chi2_in_SB:
  label: 'D^{#pm} #chi^{2}'
  rebin: 4
  ratio_range: [0.5, 1.49]

Dmeson_chi2_out_SB:
  label: 'D^{#pm} #chi^{2}'
  rebin: 4
  ratio_range: [0.5, 1.49]

Dmeson_chi20:
  label: 'D^{#pm} #chi^{2} 0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi21:
  label: 'D^{#pm} #chi^{2} 1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi22:
  label: 'D^{#pm} #chi^{2} 2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi23:
  label: 'D^{#pm} #chi^{2} 3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi24:
  label: 'D^{#pm} #chi^{2} 4'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi25:
  label: 'D^{#pm} #chi^{2} 5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi26:
  label: 'D^{#pm} #chi^{2} 6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi27:
  label: 'D^{#pm} #chi^{2} 7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi28:
  label: 'D^{#pm} #chi^{2} 8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi29:
  label: 'D^{#pm} #chi^{2} 9'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar:
  label: 'D^{#pm} cos#theta*'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar0:
  label: 'D^{#pm} cos#theta* 0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar1:
  label: 'D^{#pm} cos#theta* 1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar2:
  label: 'D^{#pm} cos#theta* 2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar3:
  label: 'D^{#pm} cos#theta* 3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar4:
  label: 'D^{#pm} cos#theta* 5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar6:
  label: 'D^{#pm} cos#theta* 6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar7:
  label: 'D^{#pm} cos#theta* 7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar8:
  label: 'D^{#pm} cos#theta* 8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar9:
  label: 'D^{#pm} cos#theta* 9'
  rebin: 2
  ratio_range: [0.5, 1.49]


met_met:
  label: MET
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

met_mt:
  label: m_{T}
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_pt:
  label: lepton p_{T}
  unit: GeV
  rebin: 2
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_eta:
  label: 'lepton #eta'
  rebin: 4
  ratio_range: [0.5, 1.49]

Dmeson_d0:
  label: 'D^{#pm} d_{0}'
  unit: '#mum'
  rebin: 1
  x_range: [-200, 200]
  ratio_range: [0.5, 1.49]

Dmeson_dRlep:
  label: '#DeltaR(D^{#pm}, lep)'
  rebin: 1
  ratio_range: [0.5, 1.49]

Dmeson_dRbjet:
  label: '#DeltaR(D^{#pm}, #it{b}-jet)_{min}'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_EOverP:
  label: 'lepton E/|p|'
  rebin: 2
  x_range: [0, 7]
  ratio_range: [0.5, 1.49]

met_dphi:
  label: 'lepton #Delta#phi(MET, l)'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_phi:
  label: 'lepton #phi'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_d0:
  label: d_{0}
  unit: '#mum'
  rebin: 2
  ratio_range: [0.0, 1.99]

lep_d0_fixed:
  label: lepton fixed d_{0}
  unit: '#mum'
  rebin: 2
  ratio_range: [0.0, 1.99]

lep_d0sig:
  label: 'lepton d_{0}/#sigma_{d_{0}}'
  ratio_range: [0.0, 1.99]

lep_d0sig_fixed:
  label: 'lepton fixed d_{0}/#sigma_{d_{0}}'
  ratio_range: [0.0, 1.99]

lep_z0sinTheta:
  label: 'lepton z_{0}sin(#theta)'
  unit: 'mm'
  ratio_range: [0.0, 1.99]

lep_topoetcone20_over_pt:
  label: lepton topoetcone20 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone20_TightTTVA_pt1000_over_pt:
  label: lepton ptvarcone20 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone30_TightTTVA_pt1000_over_pt:
  label: lepton ptvarcone30 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_topoetcone20:
  label: lepton topoetcone20
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone20_TightTTVA_pt1000:
  label: lepton ptvarcone20
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone30_TightTTVA_pt1000:
  label: lepton ptvarcone30
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

Dmeson_dPhilep:
  label: '#Delta#phi(D^{#pm}, lep)'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_dEtalep:
  label: '#Delta#eta(D^{#pm}, lep)'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_SVr:
  label: 'D^{#pm} SVr'
  unit: 'mm'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt:
  label: 'D^{#pm} ptcone40/p_{T}'
  rebin: 1
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt_in_SB:
  label: 'D^{#pm} ptcone40/p_{T}'
  rebin: 1
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt_out_SB:
  label: 'D^{#pm} ptcone40/p_{T}'
  rebin: 1
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt0:
  label: 'D^{#pm} ptcone40/p_{T} 0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt1:
  label: 'D^{#pm} ptcone40/p_{T} 1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt2:
  label: 'D^{#pm} ptcone40/p_{T} 2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt3:
  label: 'D^{#pm} ptcone40/p_{T} 3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt4:
  label: 'D^{#pm} ptcone40/p_{T} 4'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt5:
  label: 'D^{#pm} ptcone40/p_{T} 5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt6:
  label: 'D^{#pm} ptcone40/p_{T} 6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt7:
  label: 'D^{#pm} ptcone40/p_{T} 7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt8:
  label: 'D^{#pm} ptcone40/p_{T} 8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt9:
  label: 'D^{#pm} ptcone40/p_{T} 9'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_DsMin:
  label: 'D^{#pm} Ds veto'
  unit: 'GeV'
  rebin: 1
  x_range: [0,0.1]
  ratio_range: [0.5, 1.49]

Dmeson_m_DstarMin:
  label: 'D^{#pm} D* veto'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackZ0PV:
  label: 'D^{#pm} max z_{0}sin#theta_{PV}'
  unit: 'mm'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackZ0:
  label: 'D^{#pm} max z_{0}sin#theta'
  unit: 'mm'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_min_trackPt:
  label: 'D^{#pm} min p_{T}(tracks)'
  unit: 'MeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackdR:
  label: 'D^{#pm} max #DeltaR(tracks)'
  rebin: 2
  ratio_range: [0.5, 1.49]

N_Dplus:
  label: N_{D^{+}}
  ratio_range: [0.0, 1.99]
  allow_rebin: False

N_Dstar:
  label: N_{D^*}
  ratio_range: [0.0, 1.99]
  allow_rebin: False

min_dR:
  label: "#DeltaR(D)_{min}"
  ratio_range: [0.0, 1.99]
  rebin: 4

run_number:
  label: 'run number'
  ratio_range: [0.5, 1.49]
  allow_rebin: False

pileup:
  label: '<#mu>'
  ratio_range: [0.5, 1.49]
  allow_rebin: False

Dmeson_m_impact_sig:
  label: 'D^{#pm} m (w/o imp sig)'
  unit: 'GeV'
  x_range:  [1.7, 2.2]
  rebin: 5
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy:
  label: 'D^{#pm} m (w/o Lxy)'
  unit: 'GeV'
  rebin: 5
  x_range:  [1.7, 2.2]
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy0:
  label: 'D^{#pm} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy1:
  label: 'D^{#pm} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy2:
  label: 'D^{#pm} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy3:
  label: 'D^{#pm} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy4:
  label: 'D^{#pm} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_ptcone40_pt:
  label: 'D^{#pm} m (Isolation)'
  unit: 'GeV'
  rebin: 5
  x_range: [1.7, 2.2]
  ratio_range: [0.5, 1.49]

Dmeson_m_DsMin:
  label: 'D^{#pm} m (Ds min)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_DstarMin:
  label: 'D^{#pm} (D* min) m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_chi2:
  label: 'D^{#pm} m (chi2)'
  unit: 'GeV'
  rebin: 5
  x_range:  [1.7, 2.2]
  ratio_range: [0.5, 1.49]

Dmeson_m_dRlep:
  label: 'D^{#pm} m (dR lep)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_cosThetaStar:
  label: 'D^{#pm} m (cosThetaStar)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m0:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 0'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m1:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 1'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m2:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 2'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m3:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 3'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m4:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 4'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m5:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 5'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m6:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 6'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m7:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 7'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m8:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 8'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

Dmeson_chi2_x_m9:
  make_plots: False
  allow_rebin: False
#  label: 'D^{#pm} #chi^{2} 9'
#  rebin: 2
#  ratio_range: [0.5, 1.49]

# CharmEventInfo_PV_Z:
#   label: 'PV_{z}'
#   unit: mm
#   ratio_range: [0.0, 1.99]

# beamPosX_minus_PVX:
#   label: 'BS_{x} - PV_{x}'
#   unit: '#mum'
#   ratio_range: [0.0, 1.99]

# beamPosY_minus_PVY:
#   label: 'BS_{y} - PV_{y}'
#   unit: '#mum'
#   ratio_range: [0.0, 1.99]

lep_dR_bjet:
  label: '#Delta({b}-jet}, lep)'
  ratio_range: [0.5, 1.49]

lep_dR_Dmeson:
  label: '#Delta(lep, D_{loose})'
  ratio_range: [0.5, 1.49]

lep_newflowisol_over_pt:
  label: 'lepton (ptvarcone30_TightTTVA_pt500 + 0.4 neflowisol20) / p_{T}'
  rebin: 2
  ratio_range: [0.5, 1.49]

njets:
  label: N_{jet}
  ratio_range: [0.5, 1.49]
  allow_rebin: False

nbjets:
  label: N_{#it{b}-jet}
  ratio_range: [0.5, 1.49]
  allow_rebin: False

lep_pt_eta:
  make_plots: False
  allow_rebin: False

lep_pt_calo_eta:
  make_plots: False
  allow_rebin: False

Dmeson_transfer_matrix:
  make_plots: False
  allow_rebin: False

Dmeson_differential_pt:
  make_plots: True
  allow_rebin: False

Dmeson_truth_differential_pt:
  make_plots: True
  allow_rebin: False

truth_Dmeson_pt:
  label: 'D^{truth} p_{T}'
  unit: 'GeV'
  rebin: 1
  ratio_range: [0.5, 1.49]
