Dmeson_m:
  label: 'D* m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]
  
Dmeson_pt:
  label: 'D* p_{T}'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta:
  label: 'D* #eta'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_mdiff:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  x_range: [140,180]
  ratio_range: [0.5,1.49]
  do_overflow: False
  do_underflow: False

Dmeson_mdiff_fit:
  name_override: Dmeson_mdiff
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  x_range: [140,180]
  do_overflow: False
  do_underflow: False
  xbins: [140., 142., 143., 144., 145., 146., 147., 148., 149., 150., 157.5, 165., 172.5, 180.]
  # xbins: [140., 141., 142., 143., 144., 145., 146., 147., 148., 149., 150., 153., 156., 159., 162., 165., 168., 171., 174., 177., 180.]
  ratio_range: [0.5, 1.49]
  per_unit: True

Dmeson_mdiff_norebin:
  name_override: Dmeson_mdiff
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  x_range: [140,180]
  do_overflow: False
  do_underflow: False
  ratio_range: [0.5, 1.49]

Dmeson_mdiff_impact_sig:
  label: 'm(D*-D^{0}) (w/o ImpSig)'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
  do_overflow: False
  do_underflow: False
  dstar_tail_rebin: True

Dmeson_phi:
  label: 'D* #phi'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_Lxy:
  label: 'D* L_{xy}'
  unit: 'mm'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cTau:
  label: 'D* c#tau'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi2:
  label: 'D* #chi^{2}'
  rebin: 2
  ratio_range: [0.5, 1.49]

met_met:
  label: MET
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

met_mt:
  label: m_{T}
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_pt:
  label: lepton p_{T}
  unit: GeV
  rebin: 2
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_eta:
  label: 'lepton #eta'
  rebin: 4
  ratio_range: [0.5, 1.49]

Dmeson_d0:
  label: 'D* d_{0}'
  unit: '#mum'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_dRlep:
  label: '#DeltaR(D*, lep)'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_EOverP:
  label: 'lepton E/|p|'
  rebin: 2
  x_range: [0, 7]
  ratio_range: [0.5, 1.49]

met_dphi:
  label: 'lepton #Delta#phi(MET, l)'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_phi:
  label: 'lepton #phi'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_d0:
  label: d_{0}
  unit: '#mum'
  rebin: 2
  ratio_range: [0.0, 1.99]

lep_d0_fixed:
  label: lepton fixed d_{0}
  unit: '#mum'
  rebin: 2
  ratio_range: [0.0, 1.99]

lep_d0sig:
  label: 'lepton d_{0}/#sigma_{d_{0}}'
  ratio_range: [0.0, 1.99]

lep_d0sig_fixed:
  label: 'lepton fixed d_{0}/#sigma_{d_{0}}'
  ratio_range: [0.0, 1.99]

lep_z0sinTheta:
  label: 'lepton z_{0}sin(#theta)'
  unit: 'mm'
  ratio_range: [0.0, 1.99]

lep_topoetcone20_over_pt:
  label: lepton topoetcone20 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone20_TightTTVA_pt1000_over_pt:
  label: lepton ptvarcone20 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone30_TightTTVA_pt1000_over_pt:
  label: lepton ptvarcone30 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_topoetcone20:
  label: lepton topoetcone20
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone20_TightTTVA_pt1000:
  label: lepton ptvarcone20
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone30_TightTTVA_pt1000:
  label: lepton ptvarcone30
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

Dmeson_dPhilep:
  label: '#Delta#phi(D*, lep)'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_dEtalep:
  label: '#Delta#eta(D*, lep)'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_SVr:
  label: 'D* SVr'
  unit: 'mm'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt:
  label: 'D* ptcone40/p_{T}'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackZ0PV:
  label: 'D* max z_{0}sin#theta_{PV}'
  unit: 'mm'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackZ0:
  label: 'D* max z_{0}sin#theta'
  unit: 'mm'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_min_trackPt:
  label: 'D* min p_{T}(tracks)'
  unit: 'MeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackdR:
  label: 'D* max #DeltaR(tracks)'
  rebin: 2
  ratio_range: [0.5, 1.49]

run_number:
  label: 'run number'
  ratio_range: [0.5, 1.49]

pileup:
  label: '<#mu>'
  ratio_range: [0.5, 1.49]

CharmEventInfo_PV_Z:
  label: 'PV_{z}'
  unit: mm
  ratio_range: [0.0, 1.99]

beamPosX_minus_PVX:
  label: 'BS_{x} - PV_{x}'
  unit: '#mum'
  ratio_range: [0.0, 1.99]

beamPosY_minus_PVY:
  label: 'BS_{y} - PV_{y}'
  unit: '#mum'
  ratio_range: [0.0, 1.99]

njets:
  label: N_{jet}
  ratio_range: [0.5, 1.49]

nbjets:
  label: N_{#it{b}-jet}
  ratio_range: [0.5, 1.49]

N_Dplus:
  label: N_{D^{+}}
  ratio_range: [0.0, 1.99]

#Cut scan repetitions
Dmeson_mdiff0:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff1:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff2:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff3:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff4:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff5:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff6:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff7:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff8:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]
Dmeson_mdiff9:
  label: 'm(D*-D^{0})'
  unit: 'MeV'
  rebin: 10
  ratio_range: [0.5,1.49]