D_m:
  label: "D^{#pm} m"
  unit: "GeV"
  rebin: 1
  x_range: [1.7, 2.2]
  ratio_range: [0.5, 1.49]

D_m_tracks:
  label: "D^{#pm} m(tracks)"
  unit: "GeV"
  rebin: 1
  x_range: [1.7, 2.2]
  ratio_range: [0.5, 1.49]

D_pt:
  label: "D^{#pm} p_{T}"
  unit: "GeV"
  rebin: 1
  x_range: [0, 150]
  ratio_range: [0.5, 1.49]

D_differential_pt:
  label: "D^{#pm} p_{T}"
  unit: "GeV"
  allow_rebin: False

D_eta:
  label: "D^{#pm} #eta"
  rebin: 2
  ratio_range: [0.5, 1.49]

D_phi:
  label: "D^{#pm} #phi"
  rebin: 2
  ratio_range: [0.5, 1.49]

D_pt_eta:
  make_plots: False
  allow_rebin: False

met_met:
  label: MET
  unit: GeV
  rebin: 2
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

met_mt:
  label: m_{T}
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_pt:
  label: lepton p_{T}
  unit: GeV
  rebin: 2
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_eta:
  label: "lepton #eta"
  rebin: 4
  ratio_range: [0.5, 1.49]

D_differential_pt:
  label: "D^{#pm} p_{T}"
  make_plots: False
  allow_rebin: False

N_Dplus:
  label: "N(D^{#pm})"

dR_min_Dplus:
  label: "#DeltaR^{min}(D^{#pm})"

dR_min_OS_Dplus:
  label: "#DeltaR^{min}_{OS}(D^{#pm})"
