D_m:
  label: "D^{#pm} m"
  unit: "GeV"
  rebin: 1
  x_range: [1.7, 2.2]
  ratio_range: [0.5, 1.49]

D_m_tracks:
  label: "D^{#pm} m(tracks)"
  unit: "GeV"
  rebin: 1
  x_range: [1.7, 2.2]
  ratio_range: [0.5, 1.49]

D_pt:
  label: "D^{#pm} p_{T}"
  unit: "GeV"
  rebin: 5
  x_range: [0, 150]
  ratio_range: [0.5, 1.49]

D_pt_truth:
  name_override: D_pt
  label: "D^{#pm} p_{T}"
  unit: "GeV"
  rebin: 1
  xbins: [8, 10, 12, 14, 16, 18, 20, 30, 40, 60, 80, 150]
  ratio_range: [0.5, 1.49]
  per_unit: True

D_pt_fit:
  name_override: D_pt
  label: "D^{#pm} p_{T}"
  unit: "GeV"
  rebin: 1
  xbins: [8, 12, 20, 40, 80, 150]
  ratio_range: [0.5, 1.49]
  per_unit: False

D_pt_fit:
  name_override: D_pt
  label: "D^{#pm} p_{T}"
  unit: "GeV"
  rebin: 1
  xbins: [8, 12, 20, 40, 80, 150]
  ratio_range: [0.5, 1.49]
  per_unit: True

D_differential_pt:
  label: "D^{#pm} p_{T}"
  unit: "GeV"
  allow_rebin: False

D_eta:
  label: "D^{#pm} #eta"
  rebin: 2
  ratio_range: [0.5, 1.49]

D_phi:
  label: "D^{#pm} #phi"
  rebin: 2
  ratio_range: [0.5, 1.49]

D_pt_eta:
  make_plots: False
  allow_rebin: False

met_met:
  label: MET
  unit: GeV
  rebin: 2
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

met_mt:
  label: m_{T}
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_pt:
  label: lepton p_{T}
  unit: GeV
  rebin: 2
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_eta:
  label: "lepton #eta"
  rebin: 4
  ratio_range: [0.5, 1.49]

D_differential_pt:
  label: "D^{#pm} p_{T}"
  make_plots: True
  allow_rebin: False

N_Dplus:
  label: "N(D^{#pm})"

dR_min_Dplus:
  label: "#DeltaR^{min}(D^{#pm})"

dR_min_OS_Dplus:
  label: "#DeltaR^{min}_{OS}(D^{#pm})"

v_m:
  label: "v_m"

D_m_pi0:
  label: "D_m_pi0"

v_phi:
  label: "v_phi"

lep_charge:
  label: "lep_charge"

v_eta:
  label: "v_eta"

v_pt:
  label: "v_pt"

D_decay_dplus:
  name_override: D_decay
  label: 'D+ decay'
  rebin: 1
  x_range: [-0.5, 10.5]
  x_bin_labels: ["Other", "K#pi#pi", "KK#pi", "#pi#pi#pi", "K#pi#pi#pi_{0}", "#pi#pi#pi#pi_{0}", "K#pi#mu#nu", "K#pie#nu", "K_{0}#pi#pi#pi"]
  do_overflow: False
  do_underflow: False

D_decay_dzero:
  name_override: D_decay
  label: 'D0 decay'
  rebin: 1
  x_range: [19.5, 30.5]
  x_bin_labels: ["Other", "K#pi", "K#pi#pi_{0}", "K#pi#pi_{0}#pi_{0}", "K_{0}#pi#pi", "K#pi#pi#pi", "K#pi#pi#pi#pi_{0}", "#pi#pi#pi#pi", "#pi#pi#pi#pi#pi_{0}"]
  do_overflow: False
  do_underflow: False

D_decay_dsubs:
  name_override: D_decay
  label: 'Ds decay'
  rebin: 1
  x_range: [39.5, 50.5]
  x_bin_labels: ["Other", "KK#pi", "K#pi#pi", "#pi#pi#pi", "#pi#pi#pi#gamma", "#pi#pi#pi#pi0", "#pi#pi#piX", "KK#mu#nu", "KKe#nu"]
  do_overflow: False
  do_underflow: False
