Dmeson_m:
  label: 'D_{s} m'
  unit: 'GeV'
  rebin: 20
  x_range: [1.6, 2.3]
  ratio_range: [0.5, 1.49]

Dmeson_m_impact_sig:
  label: 'D_{s} m (w/o Imp Sig)'
  unit: 'GeV'
  rebin: 20
  ratio_range: [0.5, 1.49]

Dmeson_m0:
  label: 'D_{s} m0'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m1:
  label: 'D_{s} m1'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m2:
  label: 'D_{s} m2'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m3:
  label: 'D_{s} m3'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m4:
  label: 'D_{s} m4'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m5:
  label: 'D_{s} m5'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m6:
  label: 'D_{s} m6'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m7:
  label: 'D_{s} m7'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m8:
  label: 'D_{s} m8'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m9:
  label: 'D_{s} m9'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_pt:
  label: 'D_{s} p_{T}'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt0:
  label: 'D_{s} p_{T}0'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt1:
  label: 'D_{s} p_{T}1'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt2:
  label: 'D_{s} p_{T}2'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt3:
  label: 'D_{s} p_{T}3'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt4:
  label: 'D_{s} p_{T}4'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt5:
  label: 'D_{s} p_{T}5'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt6:
  label: 'D_{s} p_{T}6'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt7:
  label: 'D_{s} p_{T}7'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt8:
  label: 'D_{s} p_{T}8'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_pt9:
  label: 'D_{s} p_{T}9'
  unit: 'GeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta:
  label: 'D_{s} #eta'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta0:
  label: 'D_{s} #eta0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta1:
  label: 'D_{s} #eta1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta2:
  label: 'D_{s} #eta2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta3:
  label: 'D_{s} #eta3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta4:
  label: 'D_{s} #eta4'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta5:
  label: 'D_{s} #eta5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta6:
  label: 'D_{s} #eta6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta7:
  label: 'D_{s} #eta7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta8:
  label: 'D_{s} #eta8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_eta9:
  label: 'D_{s} #eta9'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_phi:
  label: 'D_{s} #phi'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_Lxy:
  label: 'D_{s} L_{xy}'
  unit: 'mm'
  rebin: 5
  x_range: [0, 30]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy0:
  label: 'D_{s} L_{xy}0'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy1:
  label: 'D_{s} L_{xy}1'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy2:
  label: 'D_{s} L_{xy}2'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy3:
  label: 'D_{s} L_{xy}3'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_Lxy4:
  label: 'D_{s} L_{xy}4'
  unit: 'mm'
  rebin: 1
  x_range: [0.75, 3]
  ratio_range: [0.5, 1.49]

Dmeson_cTau:
  label: 'D_{s} c#tau'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi2:
  label: 'D_{s} #chi^{2}'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi20:
  label: 'D_{s} #chi^{2} 0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi21:
  label: 'D_{s} #chi^{2} 1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi22:
  label: 'D_{s} #chi^{2} 2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi23:
  label: 'D_{s} #chi^{2} 3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi24:
  label: 'D_{s} #chi^{2} 4'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi25:
  label: 'D_{s} #chi^{2} 5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi26:
  label: 'D_{s} #chi^{2} 6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi27:
  label: 'D_{s} #chi^{2} 7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi28:
  label: 'D_{s} #chi^{2} 8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_chi29:
  label: 'D_{s} #chi^{2} 9'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar:
  label: 'D_{s} cos#theta*'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar0:
  label: 'D_{s} cos#theta* 0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar1:
  label: 'D_{s} cos#theta* 1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar2:
  label: 'D_{s} cos#theta* 2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar3:
  label: 'D_{s} cos#theta* 3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar4:
  label: 'D_{s} cos#theta* 5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar6:
  label: 'D_{s} cos#theta* 6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar7:
  label: 'D_{s} cos#theta* 7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar8:
  label: 'D_{s} cos#theta* 8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_cosThetaStar9:
  label: 'D_{s} cos#theta* 9'
  rebin: 2
  ratio_range: [0.5, 1.49]

met_met:
  label: MET
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

met_mt:
  label: m_{T}
  unit: GeV
  rebin: 4
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_pt:
  label: lepton p_{T}
  unit: GeV
  rebin: 2
  x_range: [0, 200]
  ratio_range: [0.5, 1.49]

lep_eta:
  label: 'lepton #eta'
  rebin: 4
  ratio_range: [0.5, 1.49]

Dmeson_d0:
  label: 'D_{s} d_{0}'
  unit: '#mum'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_dRlep:
  label: '#DeltaR(D_{s}, lep)'
  rebin: 1
  ratio_range: [0.5, 1.49]

Dmeson_PhiMass:
  label: 'm(#phi)'
  unit: MeV
  rebin: 4
  ratio_range: [0.5, 1.49]
  x_range: [1012, 1028]

lep_EOverP:
  label: 'lepton E/|p|'
  rebin: 2
  x_range: [0, 7]
  ratio_range: [0.5, 1.49]

met_dphi:
  label: 'lepton #Delta#phi(MET, l)'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_phi:
  label: 'lepton #phi'
  rebin: 2
  ratio_range: [0.5, 1.49]

lep_d0:
  label: d_{0}
  unit: '#mum'
  rebin: 2
  ratio_range: [0.0, 1.99]

lep_d0_fixed:
  label: lepton fixed d_{0}
  unit: '#mum'
  rebin: 2
  ratio_range: [0.0, 1.99]

lep_d0sig:
  label: 'lepton d_{0}/#sigma_{d_{0}}'
  ratio_range: [0.0, 1.99]

lep_d0sig_fixed:
  label: 'lepton fixed d_{0}/#sigma_{d_{0}}'
  ratio_range: [0.0, 1.99]

lep_z0sinTheta:
  label: 'lepton z_{0}sin(#theta)'
  unit: 'mm'
  ratio_range: [0.0, 1.99]

lep_topoetcone20_over_pt:
  label: lepton topoetcone20 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone20_TightTTVA_pt1000_over_pt:
  label: lepton ptvarcone20 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone30_TightTTVA_pt1000_over_pt:
  label: lepton ptvarcone30 / p_{T}
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_topoetcone20:
  label: lepton topoetcone20
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone20_TightTTVA_pt1000:
  label: lepton ptvarcone20
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

lep_ptvarcone30_TightTTVA_pt1000:
  label: lepton ptvarcone30
  unit: GeV
  ratio_range: [0.0, 1.99]
  rebin: 2

Dmeson_dPhilep:
  label: '#Delta#phi(D_{s}, lep)'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_dEtalep:
  label: '#Delta#eta(D_{s}, lep)'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_SVr:
  label: 'D_{s} SVr'
  unit: 'mm'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt:
  label: 'D_{s} ptcone40/p_{T}'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt0:
  label: 'D_{s} ptcone40/p_{T} 0'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt1:
  label: 'D_{s} ptcone40/p_{T} 1'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt2:
  label: 'D_{s} ptcone40/p_{T} 2'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt3:
  label: 'D_{s} ptcone40/p_{T} 3'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt4:
  label: 'D_{s} ptcone40/p_{T} 4'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt5:
  label: 'D_{s} ptcone40/p_{T} 5'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt6:
  label: 'D_{s} ptcone40/p_{T} 6'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt7:
  label: 'D_{s} ptcone40/p_{T} 7'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt8:
  label: 'D_{s} ptcone40/p_{T} 8'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_ptcone40_pt9:
  label: 'D_{s} ptcone40/p_{T} 9'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_DsMin:
  label: 'D^{#pm} veto'
  unit: 'GeV'
  rebin: 1
  x_range: [0,0.1]
  ratio_range: [0.5, 1.49]

Dmeson_m_DstarMin:
  label: 'D_{s} D* veto'
  unit: 'GeV'
  rebin: 2
  x_range: [-1,1000000]
  ratio_range: [0.5, 1.49]

Dmeson_max_trackZ0PV:
  label: 'D_{s} max z_{0}sin#theta_{PV}'
  unit: 'mm'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_dRlep:
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackZ0:
  label: 'D_{s} max z_{0}sin#theta'
  unit: 'mm'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_min_trackPt:
  label: 'D_{s} min p_{T}(tracks)'
  unit: 'MeV'
  rebin: 2
  ratio_range: [0.5, 1.49]

Dmeson_max_trackdR:
  label: 'D_{s} max #DeltaR(tracks)'
  rebin: 2
  ratio_range: [0.5, 1.49]

N_Dplus:
  label: N_{D^{+}}
  ratio_range: [0.0, 1.99]
  allow_rebin: False

run_number:
  label: 'run number'
  ratio_range: [0.5, 1.49]
  allow_rebin: False

pileup:
  label: '<#mu>'
  ratio_range: [0.5, 1.49]
  allow_rebin: False

Dmeson_m_Lxy:
  label: 'D_{s} m (no Lxy)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy0:
  label: 'D_{s} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy1:
  label: 'D_{s} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy2:
  label: 'D_{s} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy3:
  label: 'D_{s} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_Lxy4:
  label: 'D_{s} m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_ptcone40_pt:
  label: 'D_{s} m (Isolation)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_DsMin:
  label: 'D_{s} m (Ds min)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_DstarMin:
  label: 'D_{s} (D* min) m'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_chi2:
  label: 'D_{s} m (chi2)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_dRlep:
  label: 'D_{s} m (dR lep)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

Dmeson_m_cosThetaStar:
  label: 'D_{s} m (cosThetaStar)'
  unit: 'GeV'
  rebin: 10
  ratio_range: [0.5, 1.49]

# CharmEventInfo_PV_Z:
#   label: 'PV_{z}'
#   unit: mm
#   ratio_range: [0.0, 1.99]

# beamPosX_minus_PVX:
#   label: 'BS_{x} - PV_{x}'
#   unit: '#mum'
#   ratio_range: [0.0, 1.99]

# beamPosY_minus_PVY:
#   label: 'BS_{y} - PV_{y}'
#   unit: '#mum'
#   ratio_range: [0.0, 1.99]

# njets:
#   label: N_{jet}
#   ratio_range: [0.5, 1.49]
#   allow_rebin: False

# nbjets:
#   label: N_{#it{b}-jet}
#   ratio_range: [0.5, 1.49]
#   allow_rebin: False
