colorScheme: cheer_up_emo_kid

variablesConf: inclusive_wjets

samplesConf: powheg

data: Data

samples:
  - Wjets_light
  - Wjets_tau
  - Zjets_light
  - Zjets_tau
  - Top
  - Diboson

channels:
  2018_el:
    regions:
      - 2018_el_SR
    label:
      - '2018 el SR'
      - 'Powheg'
    lumi: '2018'

  2018_mu:
    regions:
      - 2018_mu_SR
    label:
      - '2018 el SR'
      - 'Powheg'
    lumi: '2018'
