colorScheme: gemstone_hues

variablesConf: inclusive_wjets

samplesConf: madgraph

data: Data

samples:
  - Wjets_light_emu
  - Wjets_bjets_emu
  - Wjets_cjets_emu
  - Wjets_tau
  - Zjets_emu
  - Zjets_tau
  - Diboson
  - Top

channels:
  2018_el:
    regions:
      - 2018_el_SR
    label:
      - "2018 el SR"
      - "MadGraph"
    lumi: "2018"

  2018_mu:
    regions:
      - 2018_mu_SR
    label:
      - "2018 mu SR"
      - "MadGraph"
    lumi: "2018"
