colorScheme: gemstone_hues

variablesConf: inclusive_wjets

samplesConf: madgraph

data: Data

systematics:
  - experimental

samples:
  - Wjets_light_emu
  - Wjets_bjets_emu
  - Wjets_cjets_emu
  - Wjets_tau
  - Zjets_emu
  - Zjets_tau
  - Diboson
  - Top

channels:
  el_0tag:
    regions:
      - el_minus_SR_0tag
      - el_plus_SR_0tag
    label:
      - "e^{#pm} 0-tag"
      - "MadGraph"
    lumi: "2015+2016A-B+2016C-L+2017+2018"

  mu_0tag:
    regions:
      - mu_minus_SR_0tag
      - mu_plus_SR_0tag
    label:
      - "#mu^{#pm} 0-tag"
      - "MadGraph"
    lumi: "2015+2016A-B+2016C-L+2017+2018"
