variablesConf: inclusive_zjets

samplesConf: sherpa2211

data: Data

# systematics:
#   - experimental

samples:
  - Zjets
  - Wjets
  - Diboson
  - Top

channels:
  el:
    regions:
      - el
      # - 2018_el
      # - 2017_el
      # - 2016A-B_el
      # - 2016C-L_el
      # - 2015_el
    label:
      - "el SR"
      - "Sherpa2.2.11"
    lumi: "2018"
    # lumi: "2018+2017+2016A-B+2016C-L+2015"

  mu:
    regions:
      - mu
      # - 2018_mu
      # - 2017_mu
      # - 2016A-B_mu
      # - 2016C-L_mu
      # - 2015_mu
    label:
      - "mu SR"
      - "Sherpa2.2.11"
    lumi: "2018"
    # lumi: "2018+2017+2016A-B+2016C-L+2015"
