colorScheme: cheer_up_emo_kid

variablesConf: inclusive_zjets

samplesConf: sherpa

data: Data

systematics:
  - experimental
#   - sherpa_theory_pdf
#   - sherpa_theory_qcd
#   - sherpa_theory_pdf_choice

samples:
  - Zjets_light_emu
  - Zjets_bjets_emu
  - Zjets_cjets_emu
  - Zjets_tau
  - Zjets_highpt_emu
  - Zjets_lowmass_emu
  - Diboson
  - Top

channels:
  2018_el:
    regions:
      - 2018_el
    label:
      - "2018 el SR"
      - "Sherpa"
    lumi: "2018"

  2018_mu:
    regions:
      - 2018_mu
    label:
      - "2018 mu SR"
      - "Sherpa"
    lumi: "2018"
