---
channels:
  2018_el_0tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_OS
      - '-2018_el_0tag_SR_Dplus_SS'
  2018_el_0tag_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_OS_Matched
      - '-2018_el_0tag_SR_Dplus_SS_Matched'
  2018_el_0tag_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_OS_Other
      - '-2018_el_0tag_SR_Dplus_SS_Other'
  2018_el_0tag_SR_Dplus_OS-SS_Rest:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_OS
      - '-2018_el_0tag_SR_Dplus_OS_Matched'
      - '-2018_el_0tag_SR_Dplus_OS_Other'
      - '-2018_el_0tag_SR_Dplus_SS'
      - 2018_el_0tag_SR_Dplus_SS_Matched
      - 2018_el_0tag_SR_Dplus_SS_Other
  2018_el_0tag_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_OS_Matched
  2018_el_0tag_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_OS_Other
  2018_el_0tag_SR_Dplus_OS_Rest:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_OS
      - '-2018_el_0tag_SR_Dplus_OS_Matched'
      - '-2018_el_0tag_SR_Dplus_OS_Other'
  2018_el_0tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-2018_el_0tag_SR_Dplus_OS'
      - 2018_el_0tag_SR_Dplus_SS
  2018_el_0tag_SR_Dplus_SS-OS_Matched:
    make_plots: false
    regions:
      - '-2018_el_0tag_SR_Dplus_OS_Matched'
      - 2018_el_0tag_SR_Dplus_SS_Matched
  2018_el_0tag_SR_Dplus_SS-OS_NoMatch:
    make_plots: false
    regions:
      - '-2018_el_0tag_SR_Dplus_OS_Other'
      - 2018_el_0tag_SR_Dplus_SS_Other
  2018_el_0tag_SR_Dplus_SS-OS_Rest:
    make_plots: false
    regions:
      - '-2018_el_0tag_SR_Dplus_OS'
      - 2018_el_0tag_SR_Dplus_OS_Matched
      - 2018_el_0tag_SR_Dplus_OS_Other
      - 2018_el_0tag_SR_Dplus_SS
      - '-2018_el_0tag_SR_Dplus_SS_Matched'
      - '-2018_el_0tag_SR_Dplus_SS_Other'
  2018_el_0tag_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_SS_Matched
  2018_el_0tag_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_SS_Other
  2018_el_0tag_SR_Dplus_SS_Rest:
    make_plots: false
    regions:
      - 2018_el_0tag_SR_Dplus_SS
      - '-2018_el_0tag_SR_Dplus_SS_Matched'
      - '-2018_el_0tag_SR_Dplus_SS_Other'
  2018_el_1tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_OS
      - '-2018_el_1tag_SR_Dplus_SS'
  2018_el_1tag_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_OS_Matched
      - '-2018_el_1tag_SR_Dplus_SS_Matched'
  2018_el_1tag_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_OS_Other
      - '-2018_el_1tag_SR_Dplus_SS_Other'
  2018_el_1tag_SR_Dplus_OS-SS_Rest:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_OS
      - '-2018_el_1tag_SR_Dplus_OS_Matched'
      - '-2018_el_1tag_SR_Dplus_OS_Other'
      - '-2018_el_1tag_SR_Dplus_SS'
      - 2018_el_1tag_SR_Dplus_SS_Matched
      - 2018_el_1tag_SR_Dplus_SS_Other
  2018_el_1tag_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_OS_Matched
  2018_el_1tag_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_OS_Other
  2018_el_1tag_SR_Dplus_OS_Rest:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_OS
      - '-2018_el_1tag_SR_Dplus_OS_Matched'
      - '-2018_el_1tag_SR_Dplus_OS_Other'
  2018_el_1tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-2018_el_1tag_SR_Dplus_OS'
      - 2018_el_1tag_SR_Dplus_SS
  2018_el_1tag_SR_Dplus_SS-OS_Matched:
    make_plots: false
    regions:
      - '-2018_el_1tag_SR_Dplus_OS_Matched'
      - 2018_el_1tag_SR_Dplus_SS_Matched
  2018_el_1tag_SR_Dplus_SS-OS_NoMatch:
    make_plots: false
    regions:
      - '-2018_el_1tag_SR_Dplus_OS_Other'
      - 2018_el_1tag_SR_Dplus_SS_Other
  2018_el_1tag_SR_Dplus_SS-OS_Rest:
    make_plots: false
    regions:
      - '-2018_el_1tag_SR_Dplus_OS'
      - 2018_el_1tag_SR_Dplus_OS_Matched
      - 2018_el_1tag_SR_Dplus_OS_Other
      - 2018_el_1tag_SR_Dplus_SS
      - '-2018_el_1tag_SR_Dplus_SS_Matched'
      - '-2018_el_1tag_SR_Dplus_SS_Other'
  2018_el_1tag_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_SS_Matched
  2018_el_1tag_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_SS_Other
  2018_el_1tag_SR_Dplus_SS_Rest:
    make_plots: false
    regions:
      - 2018_el_1tag_SR_Dplus_SS
      - '-2018_el_1tag_SR_Dplus_SS_Matched'
      - '-2018_el_1tag_SR_Dplus_SS_Other'
  2018_el_2tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_OS
      - '-2018_el_2tag_SR_Dplus_SS'
  2018_el_2tag_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_OS_Matched
      - '-2018_el_2tag_SR_Dplus_SS_Matched'
  2018_el_2tag_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_OS_Other
      - '-2018_el_2tag_SR_Dplus_SS_Other'
  2018_el_2tag_SR_Dplus_OS-SS_Rest:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_OS
      - '-2018_el_2tag_SR_Dplus_OS_Matched'
      - '-2018_el_2tag_SR_Dplus_OS_Other'
      - '-2018_el_2tag_SR_Dplus_SS'
      - 2018_el_2tag_SR_Dplus_SS_Matched
      - 2018_el_2tag_SR_Dplus_SS_Other
  2018_el_2tag_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_OS_Matched
  2018_el_2tag_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_OS_Other
  2018_el_2tag_SR_Dplus_OS_Rest:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_OS
      - '-2018_el_2tag_SR_Dplus_OS_Matched'
      - '-2018_el_2tag_SR_Dplus_OS_Other'
  2018_el_2tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-2018_el_2tag_SR_Dplus_OS'
      - 2018_el_2tag_SR_Dplus_SS
  2018_el_2tag_SR_Dplus_SS-OS_Matched:
    make_plots: false
    regions:
      - '-2018_el_2tag_SR_Dplus_OS_Matched'
      - 2018_el_2tag_SR_Dplus_SS_Matched
  2018_el_2tag_SR_Dplus_SS-OS_NoMatch:
    make_plots: false
    regions:
      - '-2018_el_2tag_SR_Dplus_OS_Other'
      - 2018_el_2tag_SR_Dplus_SS_Other
  2018_el_2tag_SR_Dplus_SS-OS_Rest:
    make_plots: false
    regions:
      - '-2018_el_2tag_SR_Dplus_OS'
      - 2018_el_2tag_SR_Dplus_OS_Matched
      - 2018_el_2tag_SR_Dplus_OS_Other
      - 2018_el_2tag_SR_Dplus_SS
      - '-2018_el_2tag_SR_Dplus_SS_Matched'
      - '-2018_el_2tag_SR_Dplus_SS_Other'
  2018_el_2tag_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_SS_Matched
  2018_el_2tag_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_SS_Other
  2018_el_2tag_SR_Dplus_SS_Rest:
    make_plots: false
    regions:
      - 2018_el_2tag_SR_Dplus_SS
      - '-2018_el_2tag_SR_Dplus_SS_Matched'
      - '-2018_el_2tag_SR_Dplus_SS_Other'
  2018_mu_0tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_OS
      - '-2018_mu_0tag_SR_Dplus_SS'
  2018_mu_0tag_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_OS_Matched
      - '-2018_mu_0tag_SR_Dplus_SS_Matched'
  2018_mu_0tag_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_OS_Other
      - '-2018_mu_0tag_SR_Dplus_SS_Other'
  2018_mu_0tag_SR_Dplus_OS-SS_Rest:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_OS
      - '-2018_mu_0tag_SR_Dplus_OS_Matched'
      - '-2018_mu_0tag_SR_Dplus_OS_Other'
      - '-2018_mu_0tag_SR_Dplus_SS'
      - 2018_mu_0tag_SR_Dplus_SS_Matched
      - 2018_mu_0tag_SR_Dplus_SS_Other
  2018_mu_0tag_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_OS_Matched
  2018_mu_0tag_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_OS_Other
  2018_mu_0tag_SR_Dplus_OS_Rest:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_OS
      - '-2018_mu_0tag_SR_Dplus_OS_Matched'
      - '-2018_mu_0tag_SR_Dplus_OS_Other'
  2018_mu_0tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-2018_mu_0tag_SR_Dplus_OS'
      - 2018_mu_0tag_SR_Dplus_SS
  2018_mu_0tag_SR_Dplus_SS-OS_Matched:
    make_plots: false
    regions:
      - '-2018_mu_0tag_SR_Dplus_OS_Matched'
      - 2018_mu_0tag_SR_Dplus_SS_Matched
  2018_mu_0tag_SR_Dplus_SS-OS_NoMatch:
    make_plots: false
    regions:
      - '-2018_mu_0tag_SR_Dplus_OS_Other'
      - 2018_mu_0tag_SR_Dplus_SS_Other
  2018_mu_0tag_SR_Dplus_SS-OS_Rest:
    make_plots: false
    regions:
      - '-2018_mu_0tag_SR_Dplus_OS'
      - 2018_mu_0tag_SR_Dplus_OS_Matched
      - 2018_mu_0tag_SR_Dplus_OS_Other
      - 2018_mu_0tag_SR_Dplus_SS
      - '-2018_mu_0tag_SR_Dplus_SS_Matched'
      - '-2018_mu_0tag_SR_Dplus_SS_Other'
  2018_mu_0tag_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_SS_Matched
  2018_mu_0tag_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_SS_Other
  2018_mu_0tag_SR_Dplus_SS_Rest:
    make_plots: false
    regions:
      - 2018_mu_0tag_SR_Dplus_SS
      - '-2018_mu_0tag_SR_Dplus_SS_Matched'
      - '-2018_mu_0tag_SR_Dplus_SS_Other'
  2018_mu_1tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_OS
      - '-2018_mu_1tag_SR_Dplus_SS'
  2018_mu_1tag_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_OS_Matched
      - '-2018_mu_1tag_SR_Dplus_SS_Matched'
  2018_mu_1tag_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_OS_Other
      - '-2018_mu_1tag_SR_Dplus_SS_Other'
  2018_mu_1tag_SR_Dplus_OS-SS_Rest:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_OS
      - '-2018_mu_1tag_SR_Dplus_OS_Matched'
      - '-2018_mu_1tag_SR_Dplus_OS_Other'
      - '-2018_mu_1tag_SR_Dplus_SS'
      - 2018_mu_1tag_SR_Dplus_SS_Matched
      - 2018_mu_1tag_SR_Dplus_SS_Other
  2018_mu_1tag_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_OS_Matched
  2018_mu_1tag_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_OS_Other
  2018_mu_1tag_SR_Dplus_OS_Rest:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_OS
      - '-2018_mu_1tag_SR_Dplus_OS_Matched'
      - '-2018_mu_1tag_SR_Dplus_OS_Other'
  2018_mu_1tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-2018_mu_1tag_SR_Dplus_OS'
      - 2018_mu_1tag_SR_Dplus_SS
  2018_mu_1tag_SR_Dplus_SS-OS_Matched:
    make_plots: false
    regions:
      - '-2018_mu_1tag_SR_Dplus_OS_Matched'
      - 2018_mu_1tag_SR_Dplus_SS_Matched
  2018_mu_1tag_SR_Dplus_SS-OS_NoMatch:
    make_plots: false
    regions:
      - '-2018_mu_1tag_SR_Dplus_OS_Other'
      - 2018_mu_1tag_SR_Dplus_SS_Other
  2018_mu_1tag_SR_Dplus_SS-OS_Rest:
    make_plots: false
    regions:
      - '-2018_mu_1tag_SR_Dplus_OS'
      - 2018_mu_1tag_SR_Dplus_OS_Matched
      - 2018_mu_1tag_SR_Dplus_OS_Other
      - 2018_mu_1tag_SR_Dplus_SS
      - '-2018_mu_1tag_SR_Dplus_SS_Matched'
      - 2018_mu_1tag_SR_Dplus_SS_Other
  2018_mu_1tag_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_SS_Matched
  2018_mu_1tag_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_SS_Other
  2018_mu_1tag_SR_Dplus_SS_Rest:
    make_plots: false
    regions:
      - 2018_mu_1tag_SR_Dplus_SS
      - '-2018_mu_1tag_SR_Dplus_SS_Matched'
      - '-2018_mu_1tag_SR_Dplus_SS_Other'
  2018_mu_2tag_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_OS_Matched
      - '-2018_mu_2tag_SR_Dplus_SS_Matched'
  2018_mu_2tag_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_OS_Other
      - '-2018_mu_2tag_SR_Dplus_SS_Other'
  2018_mu_2tag_SR_Dplus_OS-SS_Rest:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_OS
      - '-2018_mu_2tag_SR_Dplus_OS_Matched'
      - '-2018_mu_2tag_SR_Dplus_OS_Other'
      - '-2018_mu_2tag_SR_Dplus_SS'
      - 2018_mu_2tag_SR_Dplus_SS_Matched
      - 2018_mu_2tag_SR_Dplus_SS_Other
  2018_mu_2tag_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_OS_Matched
  2018_mu_2tag_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_OS_Other
  2018_mu_2tag_SR_Dplus_OS_Rest:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_OS
      - '-2018_mu_2tag_SR_Dplus_OS_Matched'
      - '-2018_mu_2tag_SR_Dplus_OS_Other'
  2018_mu_2tag_SR_Dplus_SS-OS_Matched:
    make_plots: false
    regions:
      - '-2018_mu_2tag_SR_Dplus_OS_Matched'
      - 2018_mu_2tag_SR_Dplus_SS_Matched
  2018_mu_2tag_SR_Dplus_SS-OS_NoMatch:
    make_plots: false
    regions:
      - '-2018_mu_2tag_SR_Dplus_OS_Other'
      - 2018_mu_2tag_SR_Dplus_SS_Other
  2018_mu_2tag_SR_Dplus_SS-OS_Rest:
    make_plots: false
    regions:
      - '-2018_mu_2tag_SR_Dplus_OS'
      - 2018_mu_2tag_SR_Dplus_OS_Matched
      - 2018_mu_2tag_SR_Dplus_OS_Other
      - 2018_mu_2tag_SR_Dplus_SS
      - '-2018_mu_2tag_SR_Dplus_SS_Matched'
      - '-2018_mu_2tag_SR_Dplus_SS_Other'
  2018_mu_2tag_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_SS_Matched
  2018_mu_2tag_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_SS_Other
  2018_mu_2tag_SR_Dplus_SS_Rest:
    make_plots: false
    regions:
      - 2018_mu_2tag_SR_Dplus_SS
      - '-2018_mu_2tag_SR_Dplus_SS_Matched'
      - '-2018_mu_2tag_SR_Dplus_SS_Other'
  MatrixMethod_2018_el_0tag_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_el_0tag_SR_Dplus_OS
      - '-Tight_2018_el_0tag_SR_Dplus_OS'
  MatrixMethod_2018_el_0tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_0tag_SR_Dplus_OS
      - '-Tight_2018_el_0tag_SR_Dplus_OS'
      - '-AntiTight_2018_el_0tag_SR_Dplus_SS'
      - Tight_2018_el_0tag_SR_Dplus_SS
  MatrixMethod_2018_el_0tag_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_0tag_SR_Dplus_SS
      - '-Tight_2018_el_0tag_SR_Dplus_SS'
  MatrixMethod_2018_el_0tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-AntiTight_2018_el_0tag_SR_Dplus_OS'
      - Tight_2018_el_0tag_SR_Dplus_OS
      - AntiTight_2018_el_0tag_SR_Dplus_SS
      - '-Tight_2018_el_0tag_SR_Dplus_SS'
  MatrixMethod_2018_el_1tag_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_el_1tag_SR_Dplus_OS
      - '-Tight_2018_el_1tag_SR_Dplus_OS'
  MatrixMethod_2018_el_1tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_1tag_SR_Dplus_OS
      - '-Tight_2018_el_1tag_SR_Dplus_OS'
      - '-AntiTight_2018_el_1tag_SR_Dplus_SS'
      - Tight_2018_el_1tag_SR_Dplus_SS
  MatrixMethod_2018_el_1tag_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_1tag_SR_Dplus_SS
      - '-Tight_2018_el_1tag_SR_Dplus_SS'
  MatrixMethod_2018_el_1tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-AntiTight_2018_el_1tag_SR_Dplus_OS'
      - Tight_2018_el_1tag_SR_Dplus_OS
      - AntiTight_2018_el_1tag_SR_Dplus_SS
      - '-Tight_2018_el_1tag_SR_Dplus_SS'
  MatrixMethod_2018_el_2tag_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_el_2tag_SR_Dplus_OS
      - '-Tight_2018_el_2tag_SR_Dplus_OS'
  MatrixMethod_2018_el_2tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_2tag_SR_Dplus_OS
      - '-Tight_2018_el_2tag_SR_Dplus_OS'
      - '-AntiTight_2018_el_2tag_SR_Dplus_SS'
      - Tight_2018_el_2tag_SR_Dplus_SS
  MatrixMethod_2018_el_2tag_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_2tag_SR_Dplus_SS
      - '-Tight_2018_el_2tag_SR_Dplus_SS'
  MatrixMethod_2018_el_2tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-AntiTight_2018_el_2tag_SR_Dplus_OS'
      - Tight_2018_el_2tag_SR_Dplus_OS
      - AntiTight_2018_el_2tag_SR_Dplus_SS
      - '-Tight_2018_el_2tag_SR_Dplus_SS'
  MatrixMethod_2018_mu_0tag_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_0tag_SR_Dplus_OS
      - '-Tight_2018_mu_0tag_SR_Dplus_OS'
  MatrixMethod_2018_mu_0tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_0tag_SR_Dplus_OS
      - '-Tight_2018_mu_0tag_SR_Dplus_OS'
      - '-AntiTight_2018_mu_0tag_SR_Dplus_SS'
      - Tight_2018_mu_0tag_SR_Dplus_SS
  MatrixMethod_2018_mu_0tag_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_0tag_SR_Dplus_SS
      - '-Tight_2018_mu_0tag_SR_Dplus_SS'
  MatrixMethod_2018_mu_0tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-AntiTight_2018_mu_0tag_SR_Dplus_OS'
      - Tight_2018_mu_0tag_SR_Dplus_OS
      - AntiTight_2018_mu_0tag_SR_Dplus_SS
      - '-Tight_2018_mu_0tag_SR_Dplus_SS'
  MatrixMethod_2018_mu_1tag_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_1tag_SR_Dplus_OS
      - '-Tight_2018_mu_1tag_SR_Dplus_OS'
  MatrixMethod_2018_mu_1tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_1tag_SR_Dplus_OS
      - '-Tight_2018_mu_1tag_SR_Dplus_OS'
      - '-AntiTight_2018_mu_1tag_SR_Dplus_SS'
      - Tight_2018_mu_1tag_SR_Dplus_SS
  MatrixMethod_2018_mu_1tag_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_1tag_SR_Dplus_SS
      - '-Tight_2018_mu_1tag_SR_Dplus_SS'
  MatrixMethod_2018_mu_1tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-AntiTight_2018_mu_1tag_SR_Dplus_OS'
      - Tight_2018_mu_1tag_SR_Dplus_OS
      - AntiTight_2018_mu_1tag_SR_Dplus_SS
      - '-Tight_2018_mu_1tag_SR_Dplus_SS'
  MatrixMethod_2018_mu_2tag_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_2tag_SR_Dplus_OS
      - '-Tight_2018_mu_2tag_SR_Dplus_OS'
  MatrixMethod_2018_mu_2tag_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_2tag_SR_Dplus_OS
      - '-Tight_2018_mu_2tag_SR_Dplus_OS'
      - '-AntiTight_2018_mu_2tag_SR_Dplus_SS'
      - Tight_2018_mu_2tag_SR_Dplus_SS
  MatrixMethod_2018_mu_2tag_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_2tag_SR_Dplus_SS
      - '-Tight_2018_mu_2tag_SR_Dplus_SS'
  MatrixMethod_2018_mu_2tag_SR_Dplus_SS-OS:
    make_plots: false
    regions:
      - '-AntiTight_2018_mu_2tag_SR_Dplus_OS'
      - Tight_2018_mu_2tag_SR_Dplus_OS
      - AntiTight_2018_mu_2tag_SR_Dplus_SS
      - '-Tight_2018_mu_2tag_SR_Dplus_SS'