channels:
  2018_el_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_el_SR_Dplus_OS_Matched_pt_bin4
  2018_el_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_SR_Dplus_OS_Other_pt_bin4
  2018_el_SR_Dplus_OS_Rest:
    regions:
      - 2018_el_SR_Dplus_OS_Other_pt_bin4
      - 2018_el_SR_Dplus_OS_MisMatched_pt_bin4
    make_plots: false
  MatrixMethod_2018_el_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_el_SR_Dplus_OS_pt_bin4
      - '-Tight_2018_el_SR_Dplus_OS_pt_bin4'

  2018_mu_SR_Dplus_OS_Matched:
    make_plots: false
    regions:
      - 2018_mu_SR_Dplus_OS_Matched_pt_bin4
  2018_mu_SR_Dplus_OS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_SR_Dplus_OS_Other_pt_bin4
  2018_mu_SR_Dplus_OS_Rest:
    regions:
      - 2018_mu_SR_Dplus_OS_Other_pt_bin4
      - 2018_mu_SR_Dplus_OS_MisMatched_pt_bin4
    make_plots: false
  MatrixMethod_2018_mu_SR_Dplus_OS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_SR_Dplus_OS_pt_bin4
      - '-Tight_2018_mu_SR_Dplus_OS_pt_bin4'

  2018_el_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_el_SR_Dplus_SS_Matched_pt_bin4
  2018_el_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_SR_Dplus_SS_Other_pt_bin4
  2018_el_SR_Dplus_SS_Rest:
    regions:
      - 2018_el_SR_Dplus_SS_Other_pt_bin4
      - 2018_el_SR_Dplus_SS_MisMatched_pt_bin4
    make_plots: false
  MatrixMethod_2018_el_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_SR_Dplus_SS_pt_bin4
      - '-Tight_2018_el_SR_Dplus_SS_pt_bin4'

  2018_mu_SR_Dplus_SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_SR_Dplus_SS_Matched_pt_bin4
  2018_mu_SR_Dplus_SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_SR_Dplus_SS_Other_pt_bin4
  2018_mu_SR_Dplus_SS_Rest:
    regions:
      - 2018_mu_SR_Dplus_SS_Other_pt_bin4
      - 2018_mu_SR_Dplus_SS_MisMatched_pt_bin4
    make_plots: false
  MatrixMethod_2018_mu_SR_Dplus_SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_SR_Dplus_SS_pt_bin4
      - '-Tight_2018_mu_SR_Dplus_SS_pt_bin4'

  2018_el_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_el_SR_Dplus_OS_Matched_pt_bin4
      - '-2018_el_SR_Dplus_SS_Matched_pt_bin4'
  2018_el_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_el_SR_Dplus_OS_Other_pt_bin4
      - '-2018_el_SR_Dplus_SS_Other_pt_bin4'
  2018_el_SR_Dplus_OS-SS_Rest:
    regions:
      - 2018_el_SR_Dplus_OS_Other_pt_bin4
      - 2018_el_SR_Dplus_OS_MisMatched_pt_bin4
      - '-2018_el_SR_Dplus_SS_Other_pt_bin4'
      - '-2018_el_SR_Dplus_SS_MisMatched_pt_bin4'
    make_plots: false
  MatrixMethod_2018_el_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_el_SR_Dplus_OS_pt_bin4
      - '-Tight_2018_el_SR_Dplus_OS_pt_bin4'
      - '-AntiTight_2018_el_SR_Dplus_SS_pt_bin4'
      - Tight_2018_el_SR_Dplus_SS_pt_bin4
  
  2018_mu_SR_Dplus_OS-SS_Matched:
    make_plots: false
    regions:
      - 2018_mu_SR_Dplus_OS_Matched_pt_bin4
      - '-2018_mu_SR_Dplus_SS_Matched_pt_bin4'
  2018_mu_SR_Dplus_OS-SS_NoMatch:
    make_plots: false
    regions:
      - 2018_mu_SR_Dplus_OS_Other_pt_bin4
      - '-2018_mu_SR_Dplus_SS_Other_pt_bin4'
  2018_mu_SR_Dplus_OS-SS_Rest:
    regions:
      - 2018_mu_SR_Dplus_OS_Other_pt_bin4
      - 2018_mu_SR_Dplus_OS_MisMatched_pt_bin4
      - '-2018_mu_SR_Dplus_SS_Other_pt_bin4'
      - '-2018_mu_SR_Dplus_SS_MisMatched_pt_bin4'
    make_plots: false
  MatrixMethod_2018_mu_SR_Dplus_OS-SS:
    make_plots: false
    regions:
      - AntiTight_2018_mu_SR_Dplus_OS_pt_bin4
      - '-Tight_2018_mu_SR_Dplus_OS_pt_bin4'
      - '-AntiTight_2018_mu_SR_Dplus_SS_pt_bin4'
      - Tight_2018_mu_SR_Dplus_SS_pt_bin4