colorScheme: gemstone_hues

variablesConf: inclusive_wjets

samplesConf: powheg

systematics:
  - experimental

data: Data

channels:
  2018_el_SR_noQCD:
    regions:
      - 2018_el_SR
    samples:
      - Wjets_emu
      - Wjets_tau
      - Zjets_emu
      - Zjets_tau
      - Top
      - Diboson
    label:
      - "2018 el SR"
      - "Powheg"
    lumi: "2018"
    save_to_file: True

  2018_mu_SR_noQCD:
    regions:
      - 2018_mu_SR
    samples:
      - Wjets_emu
      - Wjets_tau
      - Zjets_emu
      - Zjets_tau
      - Top
      - Diboson
    label:
      - "2018 mu SR"
      - "Powheg"
    lumi: "2018"
    save_to_file: True

  2018_el_SR:
    regions:
      - 2018_el_SR
    samples:
      - Wjets_emu
      - Wjets_tau
      - Zjets_emu
      - Zjets_tau
      - Multijet | MatrixMethod_2018_el_SR
      - Top
      - Diboson
    label:
      - "2018 el SR"
      - "Powheg"
    lumi: "2018"
    save_to_file: True

  2018_mu_SR:
    regions:
      - 2018_mu_SR
    samples:
      - Wjets_emu
      - Wjets_tau
      - Zjets_emu
      - Zjets_tau
      - Multijet | MatrixMethod_2018_mu_SR
      - Top
      - Diboson
    label:
      - "2018 mu SR"
      - "Powheg"
    lumi: "2018"
    save_to_file: True

  MatrixMethod_2018_el_SR:
    regions:
      - AntiTight_2018_el_SR
      - -Tight_2018_el_SR
    make_plots: False

  MatrixMethod_2018_mu_SR:
    regions:
      - AntiTight_2018_mu_SR
      - -Tight_2018_mu_SR
    make_plots: False
