colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: madgraph

channels:
  2018_el_QCD_Dplus:
    regions:
      - 2018_el_QCD_Dplus
    samples:
      - Multijet_Data_AntiTight | AntiTight_2018_el_QCD_Dplus
      - Multijet_Data_Tight | Tight_2018_el_QCD_Dplus
    label:
      - "2018 el QCD Closure"
      - "MET < 30 GeV, mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_mu_QCD_Dplus:
    regions:
      - 2018_mu_QCD_Dplus
    samples:
      - Multijet_Data_AntiTight | AntiTight_2018_mu_QCD_Dplus
      - Multijet_Data_Tight | Tight_2018_mu_QCD_Dplus
    label:
      - "2018 mu QCD Closure"
      - "MET < 30 GeV, mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_el_QCD_Dplus:
    regions:
      - AntiTight_2018_el_QCD_Dplus
    make_plots: False

  Tight_2018_el_QCD_Dplus:
    regions:
      - Tight_2018_el_QCD_Dplus
    make_plots: False

  AntiTight_2018_mu_QCD_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_Dplus
    make_plots: False

  Tight_2018_mu_QCD_Dplus:
    regions:
      - Tight_2018_mu_QCD_Dplus
    make_plots: False
