colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: madgraph

data: Data

channels:
  OS_2018_el_SR_Dplus:
    regions:
      - OS_2018_el_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets_emu
      - Top
      - Multijet_MatrixMethod | MatrixMethod_OS_2018_el_SR_Dplus
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  SS_2018_el_SR_Dplus:
    regions:
      - SS_2018_el_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets_emu
      - Top
      - Multijet_MatrixMethod | MatrixMethod_SS_2018_el_SR_Dplus
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  OS-SS_2018_el_SR_Dplus:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets_emu
      - Top
      - Multijet_MatrixMethod | MatrixMethod_OS-SS_2018_el_SR_Dplus
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  OS_2018_mu_SR_Dplus:
    regions:
      - OS_2018_mu_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets_emu
      - Top
      - Multijet_MatrixMethod | MatrixMethod_OS_2018_mu_SR_Dplus
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  SS_2018_mu_SR_Dplus:
    regions:
      - SS_2018_mu_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets_emu
      - Top
      - Multijet_MatrixMethod | MatrixMethod_SS_2018_mu_SR_Dplus
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  OS-SS_2018_mu_SR_Dplus:
    regions:
      - OS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Zjets_emu
      - Top
      - Multijet_MatrixMethod | MatrixMethod_OS-SS_2018_mu_SR_Dplus
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  MatrixMethod_OS_2018_el_SR_Dplus:
    regions:
      - OS_AntiTight_2018_el_SR_Dplus
      - -OS_Tight_2018_el_SR_Dplus
    make_plots: False

  MatrixMethod_SS_2018_el_SR_Dplus:
    regions:
      - SS_AntiTight_2018_el_SR_Dplus
      - -SS_Tight_2018_el_SR_Dplus
    make_plots: False

  MatrixMethod_OS-SS_2018_el_SR_Dplus:
    regions:
      - OS_AntiTight_2018_el_SR_Dplus
      - -SS_AntiTight_2018_el_SR_Dplus
      - -OS_Tight_2018_el_SR_Dplus
      - SS_Tight_2018_el_SR_Dplus
    make_plots: False

  MatrixMethod_OS_2018_mu_SR_Dplus:
    regions:
      - OS_AntiTight_2018_mu_SR_Dplus
      - -OS_Tight_2018_mu_SR_Dplus
    make_plots: False

  MatrixMethod_SS_2018_mu_SR_Dplus:
    regions:
      - SS_AntiTight_2018_mu_SR_Dplus
      - -SS_Tight_2018_mu_SR_Dplus
    make_plots: False

  MatrixMethod_OS-SS_2018_mu_SR_Dplus:
    regions:
      - OS_AntiTight_2018_mu_SR_Dplus
      - -SS_AntiTight_2018_mu_SR_Dplus
      - -OS_Tight_2018_mu_SR_Dplus
      - SS_Tight_2018_mu_SR_Dplus
    make_plots: False
