colorScheme: gemstone_hues

variablesConf: inclusive_wjets

samplesConf: real_fake_rate_measurement

channels:
  Tight_2018_el_0tag_SR_Dplus:
    regions:
      - Tight_2018_el_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el Tight"
      - "0-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2018_el_1tag_SR_Dplus:
    regions:
      - Tight_2018_el_1tag_SR_Dplus
      - Tight_2018_el_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el Tight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2018_mu_0tag_SR_Dplus:
    regions:
      - Tight_2018_mu_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu Tight"
      - "0-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2018_mu_1tag_SR_Dplus:
    regions:
      - Tight_2018_mu_1tag_SR_Dplus
      - Tight_2018_mu_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu Tight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_el_0tag_SR_Dplus:
    regions:
      - AntiTight_2018_el_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el AntiTight"
      - "0-tag"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_el_1tag_SR_Dplus:
    regions:
      - AntiTight_2018_el_1tag_SR_Dplus
      - AntiTight_2018_el_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el AntiTight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_mu_0tag_SR_Dplus:
    regions:
      - AntiTight_2018_mu_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu AntiTight"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_mu_1tag_SR_Dplus:
    regions:
      - AntiTight_2018_mu_1tag_SR_Dplus
      - AntiTight_2018_mu_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu AntiTight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2017_el_0tag_SR_Dplus:
    regions:
      - Tight_2017_el_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el Tight"
      - "0-tag"
    lumi: "2017"
    save_to_file: True

  Tight_2017_el_1tag_SR_Dplus:
    regions:
      - Tight_2017_el_1tag_SR_Dplus
      - Tight_2017_el_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el Tight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  Tight_2017_mu_0tag_SR_Dplus:
    regions:
      - Tight_2017_mu_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu Tight"
      - "0-tag"
    lumi: "2017"
    save_to_file: True

  Tight_2017_mu_1tag_SR_Dplus:
    regions:
      - Tight_2017_mu_1tag_SR_Dplus
      - Tight_2017_mu_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu Tight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_el_0tag_SR_Dplus:
    regions:
      - AntiTight_2017_el_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el AntiTight"
      - "0-tag"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_el_1tag_SR_Dplus:
    regions:
      - AntiTight_2017_el_1tag_SR_Dplus
      - AntiTight_2017_el_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el AntiTight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_mu_0tag_SR_Dplus:
    regions:
      - AntiTight_2017_mu_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu AntiTight"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_mu_1tag_SR_Dplus:
    regions:
      - AntiTight_2017_mu_1tag_SR_Dplus
      - AntiTight_2017_mu_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu AntiTight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  Tight_el_0tag_SR_Dplus:
    regions:
      - Tight_2018_el_0tag_SR_Dplus
      - Tight_2017_el_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el Tight"
      - "0-tag"
    lumi: "2017+2018"
    save_to_file: True

  Tight_el_1tag_SR_Dplus:
    regions:
      - Tight_2018_el_1tag_SR_Dplus
      - Tight_2018_el_2tag_SR_Dplus
      - Tight_2017_el_1tag_SR_Dplus
      - Tight_2017_el_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el Tight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True

  Tight_mu_0tag_SR_Dplus:
    regions:
      - Tight_2018_mu_0tag_SR_Dplus
      - Tight_2017_mu_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu Tight"
      - "0-tag"
    lumi: "2017+2018"
    save_to_file: True

  Tight_mu_1tag_SR_Dplus:
    regions:
      - Tight_2018_mu_1tag_SR_Dplus
      - Tight_2018_mu_2tag_SR_Dplus
      - Tight_2017_mu_1tag_SR_Dplus
      - Tight_2017_mu_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu Tight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_el_0tag_SR_Dplus:
    regions:
      - AntiTight_2018_el_0tag_SR_Dplus
      - AntiTight_2017_el_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el AntiTight"
      - "0-tag"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_el_1tag_SR_Dplus:
    regions:
      - AntiTight_2018_el_1tag_SR_Dplus
      - AntiTight_2018_el_2tag_SR_Dplus
      - AntiTight_2017_el_1tag_SR_Dplus
      - AntiTight_2017_el_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "el AntiTight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_mu_0tag_SR_Dplus:
    regions:
      - AntiTight_2018_mu_0tag_SR_Dplus
      - AntiTight_2017_mu_0tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu AntiTight"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_mu_1tag_SR_Dplus:
    regions:
      - AntiTight_2018_mu_1tag_SR_Dplus
      - AntiTight_2018_mu_2tag_SR_Dplus
      - AntiTight_2017_mu_1tag_SR_Dplus
      - AntiTight_2017_mu_2tag_SR_Dplus
    samples:
      - MG_Wjets_emu
      - Sh_Wjets_emu
      - Top_ttbar
    label:
      - "mu AntiTight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True
