colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: real_fake_rate_measurement

channels:
  Tight_2018_el_QCD_0tag_Dplus:
    regions:
      - Tight_2018_el_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  Tight_2018_el_QCD_1tag_Dplus:
    regions:
      - Tight_2018_el_QCD_1tag_Dplus
      - Tight_2018_el_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  Tight_2018_mu_QCD_0tag_Dplus:
    regions:
      - Tight_2018_mu_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  Tight_2018_mu_QCD_1tag_Dplus:
    regions:
      - Tight_2018_mu_QCD_1tag_Dplus
      - Tight_2018_mu_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_el_QCD_0tag_Dplus:
    regions:
      - AntiTight_2018_el_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_el_QCD_1tag_Dplus
      - AntiTight_2018_el_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_1tag_Dplus
      - AntiTight_2018_mu_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2018"
    save_to_file: True

  Tight_2017_el_QCD_0tag_Dplus:
    regions:
      - Tight_2017_el_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  Tight_2017_el_QCD_1tag_Dplus:
    regions:
      - Tight_2017_el_QCD_1tag_Dplus
      - Tight_2017_el_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  Tight_2017_mu_QCD_0tag_Dplus:
    regions:
      - Tight_2017_mu_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  Tight_2017_mu_QCD_1tag_Dplus:
    regions:
      - Tight_2017_mu_QCD_1tag_Dplus
      - Tight_2017_mu_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_el_QCD_0tag_Dplus:
    regions:
      - AntiTight_2017_el_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2017_el_QCD_1tag_Dplus
      - AntiTight_2017_el_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight_2017_mu_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2017_mu_QCD_1tag_Dplus
      - AntiTight_2017_mu_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017"
    save_to_file: True

  Tight_el_QCD_0tag_Dplus:
    regions:
      - Tight_2018_el_QCD_0tag_Dplus
      - Tight_2017_el_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True

  Tight_el_QCD_1tag_Dplus:
    regions:
      - Tight_2018_el_QCD_1tag_Dplus
      - Tight_2018_el_QCD_2tag_Dplus
      - Tight_2017_el_QCD_1tag_Dplus
      - Tight_2017_el_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True

  Tight_mu_QCD_0tag_Dplus:
    regions:
      - Tight_2018_mu_QCD_0tag_Dplus
      - Tight_2017_mu_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True

  Tight_mu_QCD_1tag_Dplus:
    regions:
      - Tight_2018_mu_QCD_1tag_Dplus
      - Tight_2018_mu_QCD_2tag_Dplus
      - Tight_2017_mu_QCD_1tag_Dplus
      - Tight_2017_mu_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD Tight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_el_QCD_0tag_Dplus:
    regions:
      - AntiTight_2018_el_QCD_0tag_Dplus
      - AntiTight_2017_el_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_el_QCD_1tag_Dplus
      - AntiTight_2018_el_QCD_2tag_Dplus
      - AntiTight_2017_el_QCD_1tag_Dplus
      - AntiTight_2017_el_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "el QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_0tag_Dplus
      - AntiTight_2017_mu_QCD_0tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_1tag_Dplus
      - AntiTight_2018_mu_QCD_2tag_Dplus
      - AntiTight_2017_mu_QCD_1tag_Dplus
      - AntiTight_2017_mu_QCD_2tag_Dplus
    samples:
      - MG_Multijet
      - MG_Multijet_Up
      - MG_Multijet_Dn
    label:
      - "mu QCD AntiTight"
      - "MET < 30 GeV, mT < 60 GeV"
    lumi: "2017+2018"
    save_to_file: True
