colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: madgraph_truth

data: Data

channels:
  2018_el_SR_0tag_Dplus_OS:
    regions:
      - 2018_el_SR_0tag_Dplus_OS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_0tag_Dplus_OS_Matched
      - Wjets_emu_Rest | 2018_el_SR_0tag_Dplus_OS_Rest
      - Top_Matched | 2018_el_SR_0tag_Dplus_OS_Matched
      - Top_Rest | 2018_el_SR_0tag_Dplus_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_0tag_Dplus_OS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_0tag_Dplus_OS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 0-tag"
    lumi: "2018"
    save_to_file: True

  2018_el_SR_0tag_Dplus_SS:
    regions:
      - 2018_el_SR_0tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_0tag_Dplus_SS_Matched
      - Wjets_emu_Rest | 2018_el_SR_0tag_Dplus_SS_Rest
      - Top_Matched | 2018_el_SR_0tag_Dplus_SS_Matched
      - Top_Rest | 2018_el_SR_0tag_Dplus_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_0tag_Dplus_SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_0tag_Dplus_SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 0-tag"
    lumi: "2018"
    save_to_file: True

  2018_el_SR_0tag_Dplus_OS-SS:
    regions:
      - 2018_el_SR_0tag_Dplus_OS
      - -2018_el_SR_0tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_0tag_Dplus_OS-SS_Matched
      - Wjets_emu_Rest | 2018_el_SR_0tag_Dplus_OS-SS_Rest
      - Top_Matched | 2018_el_SR_0tag_Dplus_OS-SS_Matched
      - Top_Rest | 2018_el_SR_0tag_Dplus_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_0tag_Dplus_OS-SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_0tag_Dplus_OS-SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 0-tag"
    lumi: "2018"
    trex_subtraction:
      OS: 2018_el_SR_0tag_Dplus_OS
      SS: 2018_el_SR_0tag_Dplus_SS
    save_to_file: True

  2018_el_SR_1tag_Dplus_OS:
    regions:
      - 2018_el_SR_1tag_Dplus_OS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_1tag_Dplus_OS_Matched
      - Wjets_emu_Rest | 2018_el_SR_1tag_Dplus_OS_Rest
      - Top_Matched | 2018_el_SR_1tag_Dplus_OS_Matched
      - Top_Rest | 2018_el_SR_1tag_Dplus_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_1tag_Dplus_OS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_1tag_Dplus_OS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 1-tag"
    lumi: "2018"
    save_to_file: True

  2018_el_SR_1tag_Dplus_SS:
    regions:
      - 2018_el_SR_1tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_1tag_Dplus_SS_Matched
      - Wjets_emu_Rest | 2018_el_SR_1tag_Dplus_SS_Rest
      - Top_Matched | 2018_el_SR_1tag_Dplus_SS_Matched
      - Top_Rest | 2018_el_SR_1tag_Dplus_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_1tag_Dplus_SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_1tag_Dplus_SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 1-tag"
    lumi: "2018"
    save_to_file: True

  2018_el_SR_1tag_Dplus_OS-SS:
    regions:
      - 2018_el_SR_1tag_Dplus_OS
      - -2018_el_SR_1tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_1tag_Dplus_OS-SS_Matched
      - Wjets_emu_Rest | 2018_el_SR_1tag_Dplus_OS-SS_Rest
      - Top_Matched | 2018_el_SR_1tag_Dplus_OS-SS_Matched
      - Top_Rest | 2018_el_SR_1tag_Dplus_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_1tag_Dplus_OS-SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_1tag_Dplus_OS-SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 1-tag"
    lumi: "2018"
    trex_subtraction:
      OS: 2018_el_SR_1tag_Dplus_OS
      SS: 2018_el_SR_1tag_Dplus_SS
    save_to_file: True

  2018_el_SR_2tag_Dplus_OS:
    regions:
      - 2018_el_SR_2tag_Dplus_OS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_2tag_Dplus_OS_Matched
      - Wjets_emu_Rest | 2018_el_SR_2tag_Dplus_OS_Rest
      - Top_Matched | 2018_el_SR_2tag_Dplus_OS_Matched
      - Top_Rest | 2018_el_SR_2tag_Dplus_OS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_2tag_Dplus_OS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_2tag_Dplus_OS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 2-tag"
    lumi: "2018"
    save_to_file: True

  2018_el_SR_2tag_Dplus_SS:
    regions:
      - 2018_el_SR_2tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_2tag_Dplus_SS_Matched
      - Wjets_emu_Rest | 2018_el_SR_2tag_Dplus_SS_Rest
      - Top_Matched | 2018_el_SR_2tag_Dplus_SS_Matched
      - Top_Rest | 2018_el_SR_2tag_Dplus_SS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_2tag_Dplus_SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_2tag_Dplus_SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 2-tag"
    lumi: "2018"
    save_to_file: True

  2018_el_SR_2tag_Dplus_OS-SS:
    regions:
      - 2018_el_SR_2tag_Dplus_OS
      - -2018_el_SR_2tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_el_SR_2tag_Dplus_OS-SS_Matched
      - Wjets_emu_Rest | 2018_el_SR_2tag_Dplus_OS-SS_Rest
      - Top_Matched | 2018_el_SR_2tag_Dplus_OS-SS_Matched
      - Top_Rest | 2018_el_SR_2tag_Dplus_OS-SS_Rest
      - Wjets_emu_NoMatch | 2018_el_SR_2tag_Dplus_OS-SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_el_SR_2tag_Dplus_OS-SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS"
      - "MadGraph, 2-tag"
    lumi: "2018"
    extra_rebin: 10
    trex_subtraction:
      OS: 2018_el_SR_2tag_Dplus_OS
      SS: 2018_el_SR_2tag_Dplus_SS
    save_to_file: True

  2018_mu_SR_0tag_Dplus_OS:
    regions:
      - 2018_mu_SR_0tag_Dplus_OS
    samples:
      - Wjets_emu_Matched | 2018_mu_SR_0tag_Dplus_OS_Matched
      - Wjets_emu_Rest | 2018_mu_SR_0tag_Dplus_OS_Rest
      - Top_Matched | 2018_mu_SR_0tag_Dplus_OS_Matched
      - Top_Rest | 2018_mu_SR_0tag_Dplus_OS_Rest
      - Wjets_emu_NoMatch | 2018_mu_SR_0tag_Dplus_OS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_SR_0tag_Dplus_OS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 0-tag"
    lumi: "2018"
    save_to_file: True

  2018_mu_SR_0tag_Dplus_SS:
    regions:
      - 2018_mu_SR_0tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_mu_SR_0tag_Dplus_SS_Matched
      - Wjets_emu_Rest | 2018_mu_SR_0tag_Dplus_SS_Rest
      - Top_Matched | 2018_mu_SR_0tag_Dplus_SS_Matched
      - Top_Rest | 2018_mu_SR_0tag_Dplus_SS_Rest
      - Wjets_emu_NoMatch | 2018_mu_SR_0tag_Dplus_SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_SR_0tag_Dplus_SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 0-tag"
    lumi: "2018"
    save_to_file: True

  2018_mu_SR_1tag_Dplus_OS:
    regions:
      - 2018_mu_SR_1tag_Dplus_OS
    samples:
      - Wjets_emu_Matched | 2018_mu_SR_1tag_Dplus_OS_Matched
      - Wjets_emu_Rest | 2018_mu_SR_1tag_Dplus_OS_Rest
      - Top_Matched | 2018_mu_SR_1tag_Dplus_OS_Matched
      - Top_Rest | 2018_mu_SR_1tag_Dplus_OS_Rest
      - Wjets_emu_NoMatch | 2018_mu_SR_1tag_Dplus_OS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_SR_1tag_Dplus_OS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 1-tag"
    lumi: "2018"
    save_to_file: True

  2018_mu_SR_1tag_Dplus_SS:
    regions:
      - 2018_mu_SR_1tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_mu_SR_1tag_Dplus_SS_Matched
      - Wjets_emu_Rest | 2018_mu_SR_1tag_Dplus_SS_Rest
      - Top_Matched | 2018_mu_SR_1tag_Dplus_SS_Matched
      - Top_Rest | 2018_mu_SR_1tag_Dplus_SS_Rest
      - Wjets_emu_NoMatch | 2018_mu_SR_1tag_Dplus_SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_SR_1tag_Dplus_SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 1-tag"
    lumi: "2018"
    save_to_file: True

  2018_mu_SR_2tag_Dplus_OS:
    regions:
      - 2018_mu_SR_2tag_Dplus_OS
    samples:
      - Wjets_emu_Matched | 2018_mu_SR_2tag_Dplus_OS_Matched
      - Wjets_emu_Rest | 2018_mu_SR_2tag_Dplus_OS_Rest
      - Top_Matched | 2018_mu_SR_2tag_Dplus_OS_Matched
      - Top_Rest | 2018_mu_SR_2tag_Dplus_OS_Rest
      - Wjets_emu_NoMatch | 2018_mu_SR_2tag_Dplus_OS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_SR_2tag_Dplus_OS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS"
      - "MadGraph, 2-tag"
    lumi: "2018"
    save_to_file: True

  2018_mu_SR_2tag_Dplus_SS:
    regions:
      - 2018_mu_SR_2tag_Dplus_SS
    samples:
      - Wjets_emu_Matched | 2018_mu_SR_2tag_Dplus_SS_Matched
      - Wjets_emu_Rest | 2018_mu_SR_2tag_Dplus_SS_Rest
      - Top_Matched | 2018_mu_SR_2tag_Dplus_SS_Matched
      - Top_Rest | 2018_mu_SR_2tag_Dplus_SS_Rest
      - Wjets_emu_NoMatch | 2018_mu_SR_2tag_Dplus_SS_NoMatch
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_SR_2tag_Dplus_SS
      - Zjets_emu
      - Other
    label:
      - "W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS"
      - "MadGraph, 2-tag"
    lumi: "2018"
    save_to_file: True

  MatrixMethod_2018_el_SR_0tag_Dplus_OS:
    regions:
      - AntiTight_2018_el_SR_0tag_Dplus_OS
      - -Tight_2018_el_SR_0tag_Dplus_OS
    make_plots: False

  2018_el_SR_0tag_Dplus_OS_Matched:
    regions:
      - 2018_el_SR_0tag_Dplus_OS_Matched
    make_plots: False

  2018_el_SR_0tag_Dplus_OS_Rest:
    regions:
      - 2018_el_SR_0tag_Dplus_OS
      - -2018_el_SR_0tag_Dplus_OS_Matched
      - -2018_el_SR_0tag_Dplus_OS_Other
    make_plots: False

  2018_el_SR_0tag_Dplus_OS_NoMatch:
    regions:
      - 2018_el_SR_0tag_Dplus_OS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_0tag_Dplus_SS:
    regions:
      - AntiTight_2018_el_SR_0tag_Dplus_SS
      - -Tight_2018_el_SR_0tag_Dplus_SS
    make_plots: False

  2018_el_SR_0tag_Dplus_SS_Matched:
    regions:
      - 2018_el_SR_0tag_Dplus_SS_Matched
    make_plots: False

  2018_el_SR_0tag_Dplus_SS_Rest:
    regions:
      - 2018_el_SR_0tag_Dplus_SS
      - -2018_el_SR_0tag_Dplus_SS_Matched
      - -2018_el_SR_0tag_Dplus_SS_Other
    make_plots: False

  2018_el_SR_0tag_Dplus_SS_NoMatch:
    regions:
      - 2018_el_SR_0tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_0tag_Dplus_OS-SS:
    regions:
      - AntiTight_2018_el_SR_0tag_Dplus_OS
      - -Tight_2018_el_SR_0tag_Dplus_OS
      - -AntiTight_2018_el_SR_0tag_Dplus_SS
      - Tight_2018_el_SR_0tag_Dplus_SS
    make_plots: False

  2018_el_SR_0tag_Dplus_OS-SS_Matched:
    regions:
      - 2018_el_SR_0tag_Dplus_OS_Matched
      - -2018_el_SR_0tag_Dplus_SS_Matched
    make_plots: False

  2018_el_SR_0tag_Dplus_OS-SS_Rest:
    regions:
      - 2018_el_SR_0tag_Dplus_OS
      - -2018_el_SR_0tag_Dplus_OS_Matched
      - -2018_el_SR_0tag_Dplus_OS_Other
      - -2018_el_SR_0tag_Dplus_SS
      - 2018_el_SR_0tag_Dplus_SS_Matched
      - 2018_el_SR_0tag_Dplus_SS_Other
    make_plots: False

  2018_el_SR_0tag_Dplus_OS-SS_NoMatch:
    regions:
      - 2018_el_SR_0tag_Dplus_OS_Other
      - -2018_el_SR_0tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_1tag_Dplus_OS:
    regions:
      - AntiTight_2018_el_SR_1tag_Dplus_OS
      - -Tight_2018_el_SR_1tag_Dplus_OS
    make_plots: False

  2018_el_SR_1tag_Dplus_OS_Matched:
    regions:
      - 2018_el_SR_1tag_Dplus_OS_Matched
    make_plots: False

  2018_el_SR_1tag_Dplus_OS_Rest:
    regions:
      - 2018_el_SR_1tag_Dplus_OS
      - -2018_el_SR_1tag_Dplus_OS_Matched
      - -2018_el_SR_1tag_Dplus_OS_Other
    make_plots: False

  2018_el_SR_1tag_Dplus_OS_NoMatch:
    regions:
      - 2018_el_SR_1tag_Dplus_OS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_1tag_Dplus_SS:
    regions:
      - AntiTight_2018_el_SR_1tag_Dplus_SS
      - -Tight_2018_el_SR_1tag_Dplus_SS
    make_plots: False

  2018_el_SR_1tag_Dplus_SS_Matched:
    regions:
      - 2018_el_SR_1tag_Dplus_SS_Matched
    make_plots: False

  2018_el_SR_1tag_Dplus_SS_Rest:
    regions:
      - 2018_el_SR_1tag_Dplus_SS
      - -2018_el_SR_1tag_Dplus_SS_Matched
      - -2018_el_SR_1tag_Dplus_SS_Other
    make_plots: False

  2018_el_SR_1tag_Dplus_SS_NoMatch:
    regions:
      - 2018_el_SR_1tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_1tag_Dplus_OS-SS:
    regions:
      - AntiTight_2018_el_SR_1tag_Dplus_OS
      - -Tight_2018_el_SR_1tag_Dplus_OS
      - -AntiTight_2018_el_SR_1tag_Dplus_SS
      - Tight_2018_el_SR_1tag_Dplus_SS
    make_plots: False

  2018_el_SR_1tag_Dplus_OS-SS_Matched:
    regions:
      - 2018_el_SR_1tag_Dplus_OS_Matched
      - -2018_el_SR_1tag_Dplus_SS_Matched
    make_plots: False

  2018_el_SR_1tag_Dplus_OS-SS_Rest:
    regions:
      - 2018_el_SR_1tag_Dplus_OS
      - -2018_el_SR_1tag_Dplus_OS_Matched
      - -2018_el_SR_1tag_Dplus_OS_Other
      - -2018_el_SR_1tag_Dplus_SS
      - 2018_el_SR_1tag_Dplus_SS_Matched
      - 2018_el_SR_1tag_Dplus_SS_Other
    make_plots: False

  2018_el_SR_1tag_Dplus_OS-SS_NoMatch:
    regions:
      - 2018_el_SR_1tag_Dplus_OS_Other
      - -2018_el_SR_1tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_2tag_Dplus_OS:
    regions:
      - AntiTight_2018_el_SR_2tag_Dplus_OS
      - -Tight_2018_el_SR_2tag_Dplus_OS
    make_plots: False

  2018_el_SR_2tag_Dplus_OS_Matched:
    regions:
      - 2018_el_SR_2tag_Dplus_OS_Matched
    make_plots: False

  2018_el_SR_2tag_Dplus_OS_Rest:
    regions:
      - 2018_el_SR_2tag_Dplus_OS
      - -2018_el_SR_2tag_Dplus_OS_Matched
      - -2018_el_SR_2tag_Dplus_OS_Other
    make_plots: False

  2018_el_SR_2tag_Dplus_OS_NoMatch:
    regions:
      - 2018_el_SR_2tag_Dplus_OS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_2tag_Dplus_SS:
    regions:
      - AntiTight_2018_el_SR_2tag_Dplus_SS
      - -Tight_2018_el_SR_2tag_Dplus_SS
    make_plots: False

  2018_el_SR_2tag_Dplus_SS_Matched:
    regions:
      - 2018_el_SR_2tag_Dplus_SS_Matched
    make_plots: False

  2018_el_SR_2tag_Dplus_SS_Rest:
    regions:
      - 2018_el_SR_2tag_Dplus_SS
      - -2018_el_SR_2tag_Dplus_SS_Matched
      - -2018_el_SR_2tag_Dplus_SS_Other
    make_plots: False

  2018_el_SR_2tag_Dplus_SS_NoMatch:
    regions:
      - 2018_el_SR_2tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_el_SR_2tag_Dplus_OS-SS:
    regions:
      - AntiTight_2018_el_SR_2tag_Dplus_OS
      - -Tight_2018_el_SR_2tag_Dplus_OS
      - -AntiTight_2018_el_SR_2tag_Dplus_SS
      - Tight_2018_el_SR_2tag_Dplus_SS
    make_plots: False

  2018_el_SR_2tag_Dplus_OS-SS_Matched:
    regions:
      - 2018_el_SR_2tag_Dplus_OS_Matched
      - -2018_el_SR_2tag_Dplus_SS_Matched
    make_plots: False

  2018_el_SR_2tag_Dplus_OS-SS_Rest:
    regions:
      - 2018_el_SR_2tag_Dplus_OS
      - -2018_el_SR_2tag_Dplus_OS_Matched
      - -2018_el_SR_2tag_Dplus_OS_Other
      - -2018_el_SR_2tag_Dplus_SS
      - 2018_el_SR_2tag_Dplus_SS_Matched
      - 2018_el_SR_2tag_Dplus_SS_Other
    make_plots: False

  2018_el_SR_2tag_Dplus_OS-SS_NoMatch:
    regions:
      - 2018_el_SR_2tag_Dplus_OS_Other
      - -2018_el_SR_2tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_mu_SR_0tag_Dplus_OS:
    regions:
      - AntiTight_2018_mu_SR_0tag_Dplus_OS
      - -Tight_2018_mu_SR_0tag_Dplus_OS
    make_plots: False

  2018_mu_SR_0tag_Dplus_OS_Matched:
    regions:
      - 2018_mu_SR_0tag_Dplus_OS_Matched
    make_plots: False

  2018_mu_SR_0tag_Dplus_OS_Rest:
    regions:
      - 2018_mu_SR_0tag_Dplus_OS
      - -2018_mu_SR_0tag_Dplus_OS_Matched
      - -2018_mu_SR_0tag_Dplus_OS_Other
    make_plots: False

  2018_mu_SR_0tag_Dplus_OS_NoMatch:
    regions:
      - 2018_mu_SR_0tag_Dplus_OS_Other
    make_plots: False

  MatrixMethod_2018_mu_SR_0tag_Dplus_SS:
    regions:
      - AntiTight_2018_mu_SR_0tag_Dplus_SS
      - -Tight_2018_mu_SR_0tag_Dplus_SS
    make_plots: False

  2018_mu_SR_0tag_Dplus_SS_Matched:
    regions:
      - 2018_mu_SR_0tag_Dplus_SS_Matched
    make_plots: False

  2018_mu_SR_0tag_Dplus_SS_Rest:
    regions:
      - 2018_mu_SR_0tag_Dplus_SS
      - -2018_mu_SR_0tag_Dplus_SS_Matched
      - -2018_mu_SR_0tag_Dplus_SS_Other
    make_plots: False

  2018_mu_SR_0tag_Dplus_SS_NoMatch:
    regions:
      - 2018_mu_SR_0tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_mu_SR_1tag_Dplus_OS:
    regions:
      - AntiTight_2018_mu_SR_1tag_Dplus_OS
      - -Tight_2018_mu_SR_1tag_Dplus_OS
    make_plots: False

  2018_mu_SR_1tag_Dplus_OS_Matched:
    regions:
      - 2018_mu_SR_1tag_Dplus_OS_Matched
    make_plots: False

  2018_mu_SR_1tag_Dplus_OS_Rest:
    regions:
      - 2018_mu_SR_1tag_Dplus_OS
      - -2018_mu_SR_1tag_Dplus_OS_Matched
      - -2018_mu_SR_1tag_Dplus_OS_Other
    make_plots: False

  2018_mu_SR_1tag_Dplus_OS_NoMatch:
    regions:
      - 2018_mu_SR_1tag_Dplus_OS_Other
    make_plots: False

  MatrixMethod_2018_mu_SR_1tag_Dplus_SS:
    regions:
      - AntiTight_2018_mu_SR_1tag_Dplus_SS
      - -Tight_2018_mu_SR_1tag_Dplus_SS
    make_plots: False

  2018_mu_SR_1tag_Dplus_SS_Matched:
    regions:
      - 2018_mu_SR_1tag_Dplus_SS_Matched
    make_plots: False

  2018_mu_SR_1tag_Dplus_SS_Rest:
    regions:
      - 2018_mu_SR_1tag_Dplus_SS
      - -2018_mu_SR_1tag_Dplus_SS_Matched
      - -2018_mu_SR_1tag_Dplus_SS_Other
    make_plots: False

  2018_mu_SR_1tag_Dplus_SS_NoMatch:
    regions:
      - 2018_mu_SR_1tag_Dplus_SS_Other
    make_plots: False

  MatrixMethod_2018_mu_SR_2tag_Dplus_OS:
    regions:
      - AntiTight_2018_mu_SR_2tag_Dplus_OS
      - -Tight_2018_mu_SR_2tag_Dplus_OS
    make_plots: False

  2018_mu_SR_2tag_Dplus_OS_Matched:
    regions:
      - 2018_mu_SR_2tag_Dplus_OS_Matched
    make_plots: False

  2018_mu_SR_2tag_Dplus_OS_Rest:
    regions:
      - 2018_mu_SR_2tag_Dplus_OS
      - -2018_mu_SR_2tag_Dplus_OS_Matched
      - -2018_mu_SR_2tag_Dplus_OS_Other
    make_plots: False

  2018_mu_SR_2tag_Dplus_OS_NoMatch:
    regions:
      - 2018_mu_SR_2tag_Dplus_OS_Other
    make_plots: False

  MatrixMethod_2018_mu_SR_2tag_Dplus_SS:
    regions:
      - AntiTight_2018_mu_SR_2tag_Dplus_SS
      - -Tight_2018_mu_SR_2tag_Dplus_SS
    make_plots: False

  2018_mu_SR_2tag_Dplus_SS_Matched:
    regions:
      - 2018_mu_SR_2tag_Dplus_SS_Matched
    make_plots: False

  2018_mu_SR_2tag_Dplus_SS_Rest:
    regions:
      - 2018_mu_SR_2tag_Dplus_SS
      - -2018_mu_SR_2tag_Dplus_SS_Matched
      - -2018_mu_SR_2tag_Dplus_SS_Other
    make_plots: False

  2018_mu_SR_2tag_Dplus_SS_NoMatch:
    regions:
      - 2018_mu_SR_2tag_Dplus_SS_Other
    make_plots: False
