colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: madgraph

data: Data

systematics:
  - matrix_method

channels:
  2018_el_QCD_Dplus:
    regions:
      - 2018_el_QCD_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2018_el_QCD_Dplus
    label:
      - "2018 el QCD Closure"
      - "MET < 30 GeV, mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_mu_QCD_Dplus:
    regions:
      - 2018_mu_QCD_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_QCD_Dplus
    label:
      - "2018 mu QCD Closure"
      - "MET < 30 GeV, mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  MatrixMethod_2018_el_QCD_Dplus:
    regions:
      - AntiTight_2018_el_QCD_Dplus
      - -Tight_2018_el_QCD_Dplus
    make_plots: False

  MatrixMethod_2018_mu_QCD_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_Dplus
      - -Tight_2018_mu_QCD_Dplus
    make_plots: False
