colorScheme: gemstone_hues

variablesConf: inclusive_wjets

samplesConf: real_fake_rate_measurement

channels:
  Tight_2018_el_SR_0tag_Dplus:
    regions:
      - Tight_2018_el_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el Tight"
      - "0-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2018_el_SR_1tag_Dplus:
    regions:
      - Tight_2018_el_SR_1tag_Dplus
      - Tight_2018_el_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el Tight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2018_mu_SR_0tag_Dplus:
    regions:
      - Tight_2018_mu_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu Tight"
      - "0-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2018_mu_SR_1tag_Dplus:
    regions:
      - Tight_2018_mu_SR_1tag_Dplus
      - Tight_2018_mu_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu Tight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_el_SR_0tag_Dplus:
    regions:
      - AntiTight_2018_el_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el AntiTight"
      - "0-tag"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_el_SR_1tag_Dplus:
    regions:
      - AntiTight_2018_el_SR_1tag_Dplus
      - AntiTight_2018_el_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el AntiTight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_mu_SR_0tag_Dplus:
    regions:
      - AntiTight_2018_mu_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu AntiTight"
    lumi: "2018"
    save_to_file: True

  AntiTight_2018_mu_SR_1tag_Dplus:
    regions:
      - AntiTight_2018_mu_SR_1tag_Dplus
      - AntiTight_2018_mu_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu AntiTight"
      - "1-tag"
    lumi: "2018"
    save_to_file: True

  Tight_2017_el_SR_0tag_Dplus:
    regions:
      - Tight_2017_el_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el Tight"
      - "0-tag"
    lumi: "2017"
    save_to_file: True

  Tight_2017_el_SR_1tag_Dplus:
    regions:
      - Tight_2017_el_SR_1tag_Dplus
      - Tight_2017_el_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el Tight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  Tight_2017_mu_SR_0tag_Dplus:
    regions:
      - Tight_2017_mu_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu Tight"
      - "0-tag"
    lumi: "2017"
    save_to_file: True

  Tight_2017_mu_SR_1tag_Dplus:
    regions:
      - Tight_2017_mu_SR_1tag_Dplus
      - Tight_2017_mu_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu Tight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_el_SR_0tag_Dplus:
    regions:
      - AntiTight_2017_el_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el AntiTight"
      - "0-tag"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_el_SR_1tag_Dplus:
    regions:
      - AntiTight_2017_el_SR_1tag_Dplus
      - AntiTight_2017_el_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el AntiTight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_mu_SR_0tag_Dplus:
    regions:
      - AntiTight_2017_mu_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu AntiTight"
    lumi: "2017"
    save_to_file: True

  AntiTight_2017_mu_SR_1tag_Dplus:
    regions:
      - AntiTight_2017_mu_SR_1tag_Dplus
      - AntiTight_2017_mu_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu AntiTight"
      - "1-tag"
    lumi: "2017"
    save_to_file: True

  Tight_el_SR_0tag_Dplus:
    regions:
      - Tight_2018_el_SR_0tag_Dplus
      - Tight_2017_el_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el Tight"
      - "0-tag"
    lumi: "2017+2018"
    save_to_file: True

  Tight_el_SR_1tag_Dplus:
    regions:
      - Tight_2018_el_SR_1tag_Dplus
      - Tight_2018_el_SR_2tag_Dplus
      - Tight_2017_el_SR_1tag_Dplus
      - Tight_2017_el_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el Tight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True

  Tight_mu_SR_0tag_Dplus:
    regions:
      - Tight_2018_mu_SR_0tag_Dplus
      - Tight_2017_mu_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu Tight"
      - "0-tag"
    lumi: "2017+2018"
    save_to_file: True

  Tight_mu_SR_1tag_Dplus:
    regions:
      - Tight_2018_mu_SR_1tag_Dplus
      - Tight_2018_mu_SR_2tag_Dplus
      - Tight_2017_mu_SR_1tag_Dplus
      - Tight_2017_mu_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu Tight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_el_SR_0tag_Dplus:
    regions:
      - AntiTight_2018_el_SR_0tag_Dplus
      - AntiTight_2017_el_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el AntiTight"
      - "0-tag"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_el_SR_1tag_Dplus:
    regions:
      - AntiTight_2018_el_SR_1tag_Dplus
      - AntiTight_2018_el_SR_2tag_Dplus
      - AntiTight_2017_el_SR_1tag_Dplus
      - AntiTight_2017_el_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "el AntiTight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_mu_SR_0tag_Dplus:
    regions:
      - AntiTight_2018_mu_SR_0tag_Dplus
      - AntiTight_2017_mu_SR_0tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu AntiTight"
    lumi: "2017+2018"
    save_to_file: True

  AntiTight_mu_SR_1tag_Dplus:
    regions:
      - AntiTight_2018_mu_SR_1tag_Dplus
      - AntiTight_2018_mu_SR_2tag_Dplus
      - AntiTight_2017_mu_SR_1tag_Dplus
      - AntiTight_2017_mu_SR_2tag_Dplus
    samples:
      - MG_Wjets_emu_0tag
      - MG_Wjets_emu_1tag
      - Top_ttbar_0tag
      - Top_ttbar_1tag
      - MC_Comb
    label:
      - "mu AntiTight"
      - "1-tag"
    lumi: "2017+2018"
    save_to_file: True
