colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: madgraph

data: Data

systematics:
  - matrix_method

channelVariables:
  lep_pt:
    label: lepton p_{T}
    unit: GeV
    rebin: 2
    x_range: [0, 200]
    ratio_range: [0.5, 1.49]

channels:
  2018_el_QCD_0tag_Dplus:
    regions:
      - 2018_el_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2018_el_QCD_0tag_Dplus
    label:
      - "2018 el QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_el_QCD_1tag_Dplus:
    regions:
      - 2018_el_QCD_1tag_Dplus
      - 2018_el_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2018_el_QCD_1tag_Dplus
    label:
      - "2018 el QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_mu_QCD_0tag_Dplus:
    regions:
      - 2018_mu_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_QCD_0tag_Dplus
    label:
      - "2018 mu QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_mu_QCD_1tag_Dplus:
    regions:
      - 2018_mu_QCD_1tag_Dplus
      - 2018_mu_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2018_mu_QCD_1tag_Dplus
    label:
      - "2018 mu QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2017_el_QCD_0tag_Dplus:
    regions:
      - 2017_el_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2017_el_QCD_0tag_Dplus
    label:
      - "2017 el QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2017"
    save_to_file: True

  2017_el_QCD_1tag_Dplus:
    regions:
      - 2017_el_QCD_1tag_Dplus
      - 2017_el_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2017_el_QCD_1tag_Dplus
    label:
      - "2017 el QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2017"
    save_to_file: True

  2017_mu_QCD_0tag_Dplus:
    regions:
      - 2017_mu_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2017_mu_QCD_0tag_Dplus
    label:
      - "2017 mu QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2017"
    save_to_file: True

  2017_mu_QCD_1tag_Dplus:
    regions:
      - 2017_mu_QCD_1tag_Dplus
      - 2017_mu_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2017_mu_QCD_1tag_Dplus
    label:
      - "2017 mu QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2017"
    save_to_file: True

  2015_el_QCD_0tag_Dplus:
    regions:
      - 2015_el_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2015_el_QCD_0tag_Dplus
    label:
      - "2015 el QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2015"
    save_to_file: True
    #extra_scale: 0.023581430

  2015_el_QCD_1tag_Dplus:
    regions:
      - 2015_el_QCD_1tag_Dplus
      - 2015_el_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2015_el_QCD_1tag_Dplus
    label:
      - "2015 el QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2015"
    save_to_file: True
    #extra_scale: 0.023581430

  2015_mu_QCD_0tag_Dplus:
    regions:
      - 2015_mu_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2015_mu_QCD_0tag_Dplus
    label:
      - "2015 mu QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2015"
    save_to_file: True
    #extra_scale: 0.023581430

  2015_mu_QCD_1tag_Dplus:
    regions:
      - 2015_mu_QCD_1tag_Dplus
      - 2015_mu_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2015_mu_QCD_1tag_Dplus
    label:
      - "2015 mu QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2015"
    save_to_file: True
    #extra_scale: 0.023581430

  2016_el_QCD_0tag_Dplus:
    regions:
      - 2016A-B_el_QCD_0tag_Dplus
      - 2016C-L_el_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2016_el_QCD_0tag_Dplus
    label:
      - "2016 el QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016"
    save_to_file: True

  2016_el_QCD_1tag_Dplus:
    regions:
      - 2016A-B_el_QCD_1tag_Dplus
      - 2016A-B_el_QCD_2tag_Dplus
      - 2016C_L_el_QCD_1tag_Dplus
      - 2016C_L_el_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2016_el_QCD_1tag_Dplus
    label:
      - "2016 el QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016"
    save_to_file: True

  2016_mu_QCD_0tag_Dplus:
    regions:
      - 2016A-B_mu_QCD_0tag_Dplus
      - 2016C-L_mu_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2016_mu_QCD_0tag_Dplus
    label:
      - "2016 mu QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016"
    save_to_file: True

  2016_mu_QCD_1tag_Dplus:
    regions:
      - 2016A-B_mu_QCD_1tag_Dplus
      - 2016A-B_mu_QCD_2tag_Dplus
      - 2016C-L_mu_QCD_1tag_Dplus
      - 2016C-L_mu_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_2016_mu_QCD_1tag_Dplus
    label:
      - "2016 mu QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016"
    save_to_file: True

  el_QCD_0tag_Dplus:
    regions:
      - 2018_el_QCD_0tag_Dplus
      - 2017_el_QCD_0tag_Dplus
      - 2016A-B_el_QCD_0tag_Dplus
      - 2016C-L_el_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_el_QCD_0tag_Dplus
    label:
      - "el QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016+2017+2018"
    save_to_file: True

  el_QCD_1tag_Dplus:
    regions:
      - 2018_el_QCD_1tag_Dplus
      - 2018_el_QCD_2tag_Dplus
      - 2017_el_QCD_1tag_Dplus
      - 2017_el_QCD_2tag_Dplus
      - 2016A-B_el_QCD_1tag_Dplus
      - 2016A-B_el_QCD_2tag_Dplus
      - 2016C-L_el_QCD_1tag_Dplus
      - 2016C-L_el_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_el_QCD_1tag_Dplus
    label:
      - "el QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016+2017+2018"
    save_to_file: True

  mu_QCD_0tag_Dplus:
    regions:
      - 2018_mu_QCD_0tag_Dplus
      - 2017_mu_QCD_0tag_Dplus
      - 2016A-B_mu_QCD_0tag_Dplus
      - 2016C-L_mu_QCD_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_mu_QCD_0tag_Dplus
    label:
      - "mu QCD Closure, 0-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016+2017+2018"
    save_to_file: True

  mu_QCD_1tag_Dplus:
    regions:
      - 2017_mu_QCD_1tag_Dplus
      - 2017_mu_QCD_2tag_Dplus
      - 2018_mu_QCD_1tag_Dplus
      - 2018_mu_QCD_2tag_Dplus
      - 2016A-B_mu_QCD_1tag_Dplus
      - 2016A-B_mu_QCD_2tag_Dplus
      - 2016C-L_mu_QCD_1tag_Dplus
      - 2016C-L_mu_QCD_2tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_mu_QCD_1tag_Dplus
    label:
      - "mu QCD Closure, 1-tag"
      - "mT < 60 GeV"
      - "MadGraph"
    lumi: "2016+2017+2018"
    save_to_file: True

  MatrixMethod_2018_el_QCD_0tag_Dplus:
    regions:
      - AntiTight_2018_el_QCD_0tag_Dplus
      - -Tight_2018_el_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2018_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_el_QCD_1tag_Dplus
      - -Tight_2018_el_QCD_1tag_Dplus
      - AntiTight_2018_el_QCD_2tag_Dplus
      - -Tight_2018_el_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2018_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_0tag_Dplus
      - -Tight_2018_mu_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2018_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_1tag_Dplus
      - -Tight_2018_mu_QCD_1tag_Dplus
      - AntiTight_2018_mu_QCD_2tag_Dplus
      - -Tight_2018_mu_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2017_el_QCD_0tag_Dplus:
    regions:
      - AntiTight_2017_el_QCD_0tag_Dplus
      - -Tight_2017_el_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2017_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2017_el_QCD_1tag_Dplus
      - -Tight_2017_el_QCD_1tag_Dplus
      - AntiTight_2017_el_QCD_2tag_Dplus
      - -Tight_2017_el_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2017_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight_2017_mu_QCD_0tag_Dplus
      - -Tight_2017_mu_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2017_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2017_mu_QCD_1tag_Dplus
      - -Tight_2017_mu_QCD_1tag_Dplus
      - AntiTight_2017_mu_QCD_2tag_Dplus
      - -Tight_2017_mu_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2015_el_QCD_0tag_Dplus:
    regions:
      - AntiTight_2015_el_QCD_0tag_Dplus
      - -Tight_2015_el_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2015_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2015_el_QCD_1tag_Dplus
      - -Tight_2015_el_QCD_1tag_Dplus
      - AntiTight_2015_el_QCD_2tag_Dplus
      - -Tight_2015_el_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2015_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight_2015_mu_QCD_0tag_Dplus
      - -Tight_2015_mu_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2015_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2015_mu_QCD_1tag_Dplus
      - -Tight_2015_mu_QCD_1tag_Dplus
      - AntiTight_2015_mu_QCD_2tag_Dplus
      - -Tight_2015_mu_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2016_el_QCD_0tag_Dplus:
    regions:
      - AntiTight2016A-B_el_QCD_0tag_Dplus
      - -Tight2016A-B_el_QCD_0tag_Dplus
      - AntiTight2016C-L_el_QCD_0tag_Dplus
      - -Tight2016C-L_el_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2016_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2016A-B_el_QCD_1tag_Dplus
      - -Tight_2016A-B_el_QCD_1tag_Dplus
      - AntiTight_2016A-B_el_QCD_2tag_Dplus
      - -Tight_2016A-B_el_QCD_2tag_Dplus
      - AntiTight_2016C-L_el_QCD_1tag_Dplus
      - -Tight_2016C-L_el_QCD_1tag_Dplus
      - AntiTight_2016C-L_el_QCD_2tag_Dplus
      - -Tight_2016C-L_el_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2016_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight2016A-B_mu_QCD_0tag_Dplus
      - -Tight2016A-B_mu_QCD_0tag_Dplus
      - AntiTight2016C-L_mu_QCD_0tag_Dplus
      - -Tight2016C-L_mu_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_2016_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2016A-B_mu_QCD_1tag_Dplus
      - -Tight_2016A-B_mu_QCD_1tag_Dplus
      - AntiTight_2016A-B_mu_QCD_2tag_Dplus
      - -Tight_2016A-B_mu_QCD_2tag_Dplus
      - AntiTight_2016C-L_mu_QCD_1tag_Dplus
      - -Tight_2016C-L_mu_QCD_1tag_Dplus
      - AntiTight_2016C-L_mu_QCD_2tag_Dplus
      - -Tight_2016C-L_mu_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_el_QCD_0tag_Dplus:
    regions:
      - AntiTight_2017_el_QCD_0tag_Dplus
      - -Tight_2017_el_QCD_0tag_Dplus
      - AntiTight_2018_el_QCD_0tag_Dplus
      - -Tight_2018_el_QCD_0tag_Dplus
      - AntiTight_2016A-B_el_QCD_0tag_Dplus
      - -Tight_2016A-B_el_QCD_0tag_Dplus
      - AntiTight_2016C-L_el_QCD_0tag_Dplus
      - -Tight_2016C-L_el_QCD_0tag_Dplus      
    make_plots: False
    save_to_file: False

  MatrixMethod_el_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_el_QCD_1tag_Dplus
      - -Tight_2018_el_QCD_1tag_Dplus
      - AntiTight_2018_el_QCD_2tag_Dplus
      - -Tight_2018_el_QCD_2tag_Dplus
      - AntiTight_2017_el_QCD_1tag_Dplus
      - -Tight_2017_el_QCD_1tag_Dplus
      - AntiTight_2017_el_QCD_2tag_Dplus
      - -Tight_2017_el_QCD_2tag_Dplus
      - AntiTight_2016A-B_el_QCD_1tag_Dplus
      - -Tight_2016A-B_el_QCD_1tag_Dplus
      - AntiTight_2016A-B_el_QCD_2tag_Dplus
      - -Tight_2016A-B_el_QCD_2tag_Dplus
      - AntiTight_2016C-L_el_QCD_1tag_Dplus
      - -Tight_2016C-L_el_QCD_1tag_Dplus
      - AntiTight_2016C-L_el_QCD_2tag_Dplus
      - -Tight_2016C-L_el_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_mu_QCD_0tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_0tag_Dplus
      - -Tight_2018_mu_QCD_0tag_Dplus
      - AntiTight_2017_mu_QCD_0tag_Dplus
      - -Tight_2017_mu_QCD_0tag_Dplus
      - AntiTight_2016A-B_mu_QCD_0tag_Dplus
      - -Tight_2016A-B_mu_QCD_0tag_Dplus
      - AntiTight_2016C-L_mu_QCD_0tag_Dplus
      - -Tight_2016C-L_mu_QCD_0tag_Dplus
    make_plots: False
    save_to_file: False

  MatrixMethod_mu_QCD_1tag_Dplus:
    regions:
      - AntiTight_2018_mu_QCD_1tag_Dplus
      - -Tight_2018_mu_QCD_1tag_Dplus
      - AntiTight_2018_mu_QCD_2tag_Dplus
      - -Tight_2018_mu_QCD_2tag_Dplus
      - AntiTight_2017_mu_QCD_1tag_Dplus
      - -Tight_2017_mu_QCD_1tag_Dplus
      - AntiTight_2017_mu_QCD_2tag_Dplus
      - -Tight_2017_mu_QCD_2tag_Dplus
      - AntiTight_2016A-B_mu_QCD_1tag_Dplus
      - -Tight_2016A-B_mu_QCD_1tag_Dplus
      - AntiTight_2016A-B_mu_QCD_2tag_Dplus
      - -Tight_2016A-B_mu_QCD_2tag_Dplus
      - AntiTight_2016C-L_mu_QCD_1tag_Dplus
      - -Tight_2016C-L_mu_QCD_1tag_Dplus
      - AntiTight_2016C-L_mu_QCD_2tag_Dplus
      - -Tight_2016C-L_mu_QCD_2tag_Dplus
    make_plots: False
    save_to_file: False
