variablesConf: charmed_wjets_eff

samplesConf: SPG_truth_Nminus1

channels:
  2018_wplusd:
    samples:
      - Wjets_emu_Matched_Charm0 | 2018_wplusd_Matched0
#      - Wjets_emu_Matched_Charm0_loose | 2018_wplusd_Matched0
      - Wjets_emu_Matched_Charm_noCuts | 2018_wplusd_Matched
#      - Wjets_emu_Matched_Charm_noCuts_loose | 2018_wplusd_Matched999
    regions:
      - _recoMatch_truth_Dplus_RM0
      - /_recoMatch_truth_Dplus_RM
    label: 'W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Eff'
    lumi: '2018'

  2018_wplusd_Matched0:
    regions:
      - _recoMatch_truth_Dplus_RM0
      - _recoMatch_truth_Dplus_RM1
      #- _recoMatch_truth_Dplus_RM2
      #- _recoMatch_truth_Dplus_RM3
      #- _recoMatch_truth_Dplus_RM4
      #- _recoMatch_truth_Dplus_RM6
      #- _recoMatch_truth_Dplus_RM7
      #- _recoMatch_truth_Dplus_RM8
      #- _recoMatch_truth_Dplus_RM10
      #- _recoMatch_truth_Dplus_RM13
      #- _recoMatch_truth_Dplus_RM999
      - /_truth_Dplus_RM
    make_plots: False

  2018_wplusd_Matched:
    regions:
      - _recoMatch_truth_Dplus_RM0
      - _recoMatch_truth_Dplus_RM1
      - _recoMatch_truth_Dplus_RM2
      - _recoMatch_truth_Dplus_RM3
      - _recoMatch_truth_Dplus_RM4
      - _recoMatch_truth_Dplus_RM6
      - _recoMatch_truth_Dplus_RM7
      - _recoMatch_truth_Dplus_RM8
      - _recoMatch_truth_Dplus_RM10
      - _recoMatch_truth_Dplus_RM13
      - _recoMatch_truth_Dplus_RM999
      - /_truth_Dplus_RM
    make_plots: False
