variablesConf: charmed_wjets_eff

samplesConf: madgraph_truth

channels:
  2018_wplusd:
    samples:
      - Wjets_emu_Matched_Charm | inclusive_wplusd_Matched
      - Top_Matched | inclusive_wplusd_Matched
      - SPG_Matched_Ds | inclusive_wplusd_Matched
      #- SPG_Matched_Ds20 | inclusive_wplusd_Matched
    regions:
      - inclusive_SR_recoMatch_truth_Ds_RM0
      - /inclusive_SR_truth_Ds_RM
    label:
      - "W#rightarrowl#nu+D, D#rightarrowKK#pi, Eff"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_wplusd_Matched:
    regions:
      - inclusive_SR_recoMatch_truth_Ds_RM0
      - /inclusive_SR_truth_Ds_RM
    make_plots: False

  inclusive_wplusd_Matched:
    regions:
      - inclusive_SR_recoMatch_truth_Ds_RM0
      - inclusive_SR_recoMatch_truth_Ds_RM1
      - inclusive_SR_recoMatch_truth_Ds_RM2
      - inclusive_SR_recoMatch_truth_Ds_RM3
      - inclusive_SR_recoMatch_truth_Ds_RM4
      - inclusive_SR_recoMatch_truth_Ds_RM6
      - inclusive_SR_recoMatch_truth_Ds_RM7
      - inclusive_SR_recoMatch_truth_Ds_RM8
      - /inclusive_SR_truth_Ds_RM
    make_plots: False