variablesConf: charmed_wjets_eff

samplesConf: SPG_truth_Nminus1_dstar

channels:
  inclusive_wplusd:
    samples:
      #- Wjets_emu_Matched_Charm0 | inclusive_wplusd_Matched0
      #- Wjets_emu_Matched_Charm0_loose | inclusive_wplusd_Matched0
      #- Wjets_emu_Matched_Charm1 | inclusive_wplusd_Matched1
      #- Wjets_emu_Matched_Charm3 | inclusive_wplusd_Matched3
      #- Wjets_emu_Matched_Charm4 | inclusive_wplusd_Matched4
      #- Wjets_emu_Matched_Charm6 | inclusive_wplusd_Matched6
      #- Wjets_emu_Matched_Charm7 | inclusive_wplusd_Matched7
      - Wjets_emu_Matched_Charm8 | inclusive_wplusd_Matched_ortho
      - Wjets_emu_Matched_Charm_noCuts | inclusive_wplusd_Matched_noCuts
      #- Wjets_emu_Matched_Charm_noCuts_loose | inclusive_wplusd_Matched_noCuts
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    label:
      - "W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Eff"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  inclusive_wplusd_Matched0:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    make_plots: False

  inclusive_wplusd_Matched1:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM1
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    make_plots: False

  inclusive_wplusd_Matched3:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM3
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    make_plots: False

  inclusive_wplusd_Matched4:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM4
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    make_plots: False

  inclusive_wplusd_Matched6:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM6
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    make_plots: False

  inclusive_wplusd_Matched7:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM7
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    make_plots: False

  inclusive_wplusd_Matched8:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM8
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - /inclusive_SR_truth_DstarKPi_RM
    make_plots: False
    
  inclusive_wplusd_Matched_noCuts:
    regions:
      - inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - inclusive_SR_recoMatch_truth_DstarKPi_RM1
      - inclusive_SR_recoMatch_truth_DstarKPi_RM2
      - inclusive_SR_recoMatch_truth_DstarKPi_RM3
      - inclusive_SR_recoMatch_truth_DstarKPi_RM4
      - inclusive_SR_recoMatch_truth_DstarKPi_RM6
      - inclusive_SR_recoMatch_truth_DstarKPi_RM7
      - inclusive_SR_recoMatch_truth_DstarKPi_RM8
      - inclusive_SR_recoMatch_truth_DstarKPi_RM10
      - inclusive_SR_recoMatch_truth_DstarKPi_RM11
      - inclusive_SR_recoMatch_truth_DstarKPi_RM12
      - inclusive_SR_recoMatch_truth_DstarKPi_RM999
      #- /inclusive_SR_truth_DstarKPi_RM
    make_plots: False

  inclusive_wplusd_Matched_ortho:
    regions:
      - inclusive_SR_truth_DstarKPi_RM
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM0
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM1
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM2
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM3
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM4
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM6
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM7 
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM8
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM10
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM11
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM12
      - -inclusive_SR_recoMatch_truth_DstarKPi_RM999
    make_plots: False
    