variablesConf: charmed_wjets_eff

samplesConf: madgraph_truth

channels:
  2018_wplusd:
    samples:
      - Wjets_emu_Matched_Charm | 2018_wplusd_Matched
      - Top_Matched | 2018_wplusd_Matched
      - SPG_Matched | 2018_wplusd_Matched
    regions:
      - inclusive_SR_recoMatch_truth_Dplus_RM0
      - /inclusive_SR_truth_Dplus_RM
    label:
      - "W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Eff"
      - "MadGraph"
    lumi: "2018"
    save_to_file: True

  2018_wplusd_Matched:
    regions:
      - inclusive_SR_recoMatch_truth_Dplus_RM0
      - inclusive_SR_recoMatch_truth_Dplus_RM1
      - inclusive_SR_recoMatch_truth_Dplus_RM2
      - inclusive_SR_recoMatch_truth_Dplus_RM3
      - inclusive_SR_recoMatch_truth_Dplus_RM4
      - inclusive_SR_recoMatch_truth_Dplus_RM6
      - inclusive_SR_recoMatch_truth_Dplus_RM7
      - inclusive_SR_recoMatch_truth_Dplus_RM8
      - /inclusive_SR_truth_Dplus_RM
    make_plots: False
