colorScheme: cheer_up_emo_kid

variablesConf: inclusive_wjets

samplesConf: madgraph

data: Data

samples:
  - Wjets_light_emu
  - Wjets_bjets_emu
  - Wjets_cjets_emu
  - Wjets_tau
  - Zjets
  - Top
  - Diboson

channels:
  2018_el:
    regions:
      - 2018_el_SR
    label: '2018 el SR'
    lumi: '2018'

  2018_mu:
    regions:
      - 2018_mu_SR
    label: '2018 mu SR'
    lumi: '2018'

  2018_el_QCD_PT_Template:
    regions:
      - 2018_el_QCD
    samples:
      - Multijet
      - Wjets_light_emu
      - Wjets_bjets_emu
      - Wjets_cjets_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - '2018 el QCD PT Template'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_mu_QCD_PT_Template:
    regions:
      - 2018_mu_QCD
    samples:
      - Multijet
      - Wjets_light_emu
      - Wjets_bjets_emu
      - Wjets_cjets_emu
      - Wjets_tau
      - Zjets
      - Top
      - Diboson
    label:
      - '2018 mu QCD PT Template'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_el_QCD_PT_Fit:
    regions:
      - 2018_el
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet | 2018_el_QCD_PT_Template
    likelihood_fit:
      variable: lep_pt
      range: [28, 200]
      extrapolated_region: 2018_el_QCD_PT_Extrapolated
      extrapolated_multijet: 2018_el_QCD_PTCut_Template
      fixed:
        - Zjets
        - Top
        - Diboson
    label:
      - '2018 el QCD PT Fit'
      - 'MGPy8EG'
    lumi: '2018'

  2018_mu_QCD_PT_Fit:
    regions:
      - 2018_mu
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet | 2018_mu_QCD_PT_Template
    likelihood_fit:
      variable: lep_pt
      range: [28, 200]
      extrapolated_region: 2018_mu_QCD_PT_Extrapolated
      extrapolated_multijet: 2018_mu_QCD_PTCut_Template
      fixed:
        - Zjets
        - Top
        - Diboson
    label:
      - '2018 mu QCD PT Fit'
      - 'MGPy8EG'
    lumi: '2018'

  2018_el_QCD_PT_Extrapolated:
    regions:
      - 2018_el_SR
    samples:
      - Wjets_light_emu
      - Wjets_bjets_emu
      - Wjets_cjets_emu
      - Zjets
      - Top
      - Multijet | 2018_el_QCD_PTCut_Template
      - Diboson
    scale_factors:
      input_file: 2018_el_QCD_PT_Fit.json
      scale_factors:
        Wjets_light_emu: Wjets
        Wjets_bjets_emu: Wjets
        Wjets_cjets_emu: Wjets
        Zjets: Zjets
        Top: Top
        Diboson: Diboson
    label: '2018 el SR'
    lumi: '2018'

  2018_mu_QCD_PT_Extrapolated:
    regions:
      - 2018_mu_SR
    samples:
      - Wjets_light_emu
      - Wjets_bjets_emu
      - Wjets_cjets_emu
      - Zjets
      - Top
      - Multijet | 2018_mu_QCD_PTCut_Template
      - Diboson
    scale_factors:
      input_file: 2018_mu_QCD_PT_Fit.json
      scale_factors:
        Wjets_light_emu: Wjets
        Wjets_bjets_emu: Wjets
        Wjets_cjets_emu: Wjets
        Zjets: Zjets
        Top: Top
        Diboson: Diboson
    label: '2018 mu SR'
    lumi: '2018'

  2018_el_QCD_PTCut_Template:
    regions:
      - 2018_el_QCD_PTCut
    make_plots: False

  2018_mu_QCD_PTCut_Template:
    regions:
      - 2018_mu_QCD_PTCut
    make_plots: False
