colorScheme: cheer_up_emo_kid

variablesConf: inclusive_wjets

samplesConf: common

data: Data

samples:
  - Powheg_Wjets_light
  - Powheg_Wjets_tau
  - Powheg_Zjets_light
  - Powheg_Zjets_tau
  - Top
  - Diboson

channels:
  2018_el:
    regions:
      - 2018_el_SR
    label: '2018 el SR'
    lumi: '2018'

  2018_mu:
    regions:
      - 2018_mu_SR
    label: '2018 mu SR'
    lumi: '2018'
