colorScheme: cheer_up_emo_kid

variablesConf: inclusive_wjets

samplesConf: inclusive_wjets

data: Data

samples:
  - Sherpa_Wjets_light
  - Sherpa_Wjets_tau
  - Sherpa_Zjets_light
  - Sherpa_Zjets_tau
  - Top
  - Diboson

channels:
  2018_el:
    regions:
      - 2018_el
    label: '2018 el SR'
    lumi: '2018'
  2018_mu:
    regions:
      - 2018_mu
    label: '2018 mu SR'
    lumi: '2018'
