colorScheme: cheer_up_emo_kid

variablesConf: inclusive_wjets

samplesConf: common

data: Data

samples:
  - Sherpa_Wjets_light
  - Sherpa_Wjets_tau
  - Sherpa_Zjets_light
  - Sherpa_Zjets_tau
  - Top
  - Diboson

channels:

  2018_el:
    regions:
      - 2018_el_SR
    label: '2018 el SR'
    lumi: '2018'

  2018_mu:
    regions:
      - 2018_mu_SR
    label: '2018 mu SR'
    lumi: '2018'

  2018_el_QCD_PT_Template:
    regions:
      - 2018_el_QCD
    samples:
      - Multijet
      - Sherpa_Wjets_light
      - Sherpa_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - '2018 el QCD PT Template'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_mu_QCD_PT_Template:
    regions:
      - 2018_mu_QCD
    samples:
      - Multijet
      - Sherpa_Wjets_light
      - Sherpa_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - '2018 mu QCD PT Template'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet

  2018_el_QCD_PT_Fit:
    regions:
      - 2018_el
    samples:
      - EWK
      - Multijet | 2018_el_QCD_PT_Template
    likelihood_fit:
      variable: lep_pt
      range: [28, 38]
      extrapolated_region: 2018_el_QCD_PT_Extrapolated
      extrapolated_multijet: 2018_el_QCD_PTCut_Template
    label:
      - '2018 el QCD PT Fit'
    lumi: '2018'

  2018_mu_QCD_PT_Fit:
    regions:
      - 2018_mu
    samples:
      - EWK
      - Multijet | 2018_mu_QCD_PT_Template
    likelihood_fit:
      variable: lep_pt
      range: [30, 38]
      extrapolated_region: 2018_mu_QCD_PT_Extrapolated
      extrapolated_multijet: 2018_mu_QCD_PTCut_Template
    label:
      - '2018 mu QCD PT Fit'
    lumi: '2018'

  2018_el_QCD_PT_Extrapolated:
    regions:
      - 2018_el_SR
    samples:
      - Sherpa_Wjets_light
      - Sherpa_Wjets_tau
      - Sherpa_Zjets_light
      - Sherpa_Zjets_tau
      - Top
      - Multijet | 2018_el_QCD_PTCut_Template
      - Diboson
    scale_factors:
      input_file: 2018_el_QCD_PT_Fit.json
      ewk: EWK
    label: '2018 el SR'
    lumi: '2018'

  2018_mu_QCD_PT_Extrapolated:
    regions:
      - 2018_mu_SR
    samples:
      - Sherpa_Wjets_light
      - Sherpa_Wjets_tau
      - Sherpa_Zjets_light
      - Sherpa_Zjets_tau
      - Top
      - Multijet | 2018_mu_QCD_PTCut_Template
      - Diboson
    scale_factors:
      input_file: 2018_mu_QCD_PT_Fit.json
      ewk: EWK
    label: '2018 mu SR'
    lumi: '2018'

  2018_el_QCD_PTCut_Template:
    regions:
      - 2018_el_QCD_PTCut
    make_plots: False

  2018_mu_QCD_PTCut_Template:
    regions:
      - 2018_mu_QCD_PTCut
    make_plots: False
