colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets

samplesConf: wplusd_mc_mc

channels:
  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR
      - -SS_2018_el_SR
    samples:
      - Powheg_Wjets_v3
      - Powheg_Wjets_v2
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR
      - -SS_2018_mu_SR
    samples:
      - Powheg_Wjets_v3
      - Powheg_Wjets_v2
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR
    samples:
      - Powheg_Wjets_v3
      - Powheg_Wjets_v2
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_mu_wplusd_OS:
    regions:
      - OS_2018_mu_SR
    samples:
      - Powheg_Wjets_v3
      - Powheg_Wjets_v2
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR
    samples:
      - Powheg_Wjets_v3
      - Powheg_Wjets_v2
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_mu_wplusd_SS:
    regions:
      - SS_2018_mu_SR
    samples:
      - Powheg_Wjets_v3
      - Powheg_Wjets_v2
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'
