---
colorScheme: gemstone_hues
variablesConf: charmed_wjets
samplesConf: sherpa
channels:
  OS_2018_SR_Dplus:
    label:
      - 'W+D, D#rightarrowK#pi#pi, OS'
      - 'Data'
    lumi: '2018'
    regions:
      - 2018_el_minus_0tag_SR_Dplus_OS
      - 2018_el_minus_1tag_SR_Dplus_OS
      - 2018_el_minus_2tag_SR_Dplus_OS
      - 2018_el_plus_0tag_SR_Dplus_OS
      - 2018_el_plus_1tag_SR_Dplus_OS
      - 2018_el_plus_2tag_SR_Dplus_OS
      - 2018_mu_minus_0tag_SR_Dplus_OS
      - 2018_mu_minus_1tag_SR_Dplus_OS
      - 2018_mu_minus_2tag_SR_Dplus_OS
      - 2018_mu_plus_0tag_SR_Dplus_OS
      - 2018_mu_plus_1tag_SR_Dplus_OS
      - 2018_mu_plus_2tag_SR_Dplus_OS
    samples:
      - Data
    save_to_file: true
    extra_rebin: 2
