colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets_dstar

samplesConf: powheg_full_truth_dstar

channels:
  2018_wplusd_OS:
    samples:
      - Wjets_light_Matched | 2018_wplusd_OS_Matched
      - Wjets_light_NoMatch | 2018_wplusd_OS_NoMatch
      - Wjets_light_DsMisMatched | 2018_wplusd_OS_431MisMatched
      - Wjets_light_DzeroMisMatched | 2018_wplusd_OS_421MisMatched
      - Wjets_light_DplusMisMatched | 2018_wplusd_OS_411MisMatched
      - Wjets_light_BaryonMisMatched | 2018_wplusd_OS_BaryonMisMatched
      - Wjets_light_HardScatter | 2018_wplusd_OS_HardScatter
    regions:
      - OS_2018_el_SR_DstarKPi
      - OS_2018_mu_SR_DstarKPi
    label: 'W#rightarrowl#nu+D*, D*#rightarrow(K#pi)#pi, OS'
    lumi: '2018'

  2018_wplusd_SS:
    samples:
      - Wjets_light_Matched | 2018_wplusd_SS_Matched
      - Wjets_light_NoMatch | 2018_wplusd_SS_NoMatch
      - Wjets_light_DsMisMatched | 2018_wplusd_SS_431MisMatched
      - Wjets_light_DzeroMisMatched | 2018_wplusd_SS_421MisMatched
      - Wjets_light_DplusMisMatched | 2018_wplusd_SS_411MisMatched
      - Wjets_light_BaryonMisMatched | 2018_wplusd_SS_BaryonMisMatched
      - Wjets_light_HardScatter | 2018_wplusd_SS_HardScatter
    regions:
      - SS_2018_el_SR_DstarKPi
      - SS_2018_mu_SR_DstarKPi
    label: 'W#rightarrowl#nu+D*, D*#rightarrow(K#pi)#pi, SS'
    lumi: '2018'

  2018_wplusd_OS-SS:
    samples:
      - Wjets_light_Matched | 2018_wplusd_OS-SS_Matched
      - Wjets_light_DsMisMatched | 2018_wplusd_OS-SS_431MisMatched
      - Wjets_light_DzeroMisMatched | 2018_wplusd_OS-SS_421MisMatched
      - Wjets_light_DplusMisMatched | 2018_wplusd_OS-SS_411MisMatched
      - Wjets_light_BaryonMisMatched | 2018_wplusd_OS-SS_BaryonMisMatched
      - Wjets_light_HardScatter | 2018_wplusd_OS-SS_HardScatter
      - Wjets_light_NoMatch | 2018_wplusd_OS-SS_NoMatch
    regions:
      - OS_2018_el_SR_DstarKPi
      - OS_2018_mu_SR_DstarKPi
      - -SS_2018_el_SR_DstarKPi
      - -SS_2018_mu_SR_DstarKPi
    label: 'W#rightarrowl#nu+D*, D*#rightarrow(K#pi)#pi, OS-SS'
    lumi: '2018'

  2018_wplusd_OS_Matched:
    regions:
      - OS_2018_el_SR_DstarKPi_Matched
      - OS_2018_mu_SR_DstarKPi_Matched
    make_plots: False

  2018_wplusd_SS_Matched:
    regions:
      - SS_2018_el_SR_DstarKPi_Matched
      - SS_2018_mu_SR_DstarKPi_Matched
    make_plots: False

  2018_wplusd_OS-SS_Matched:
    regions:
      - OS_2018_el_SR_DstarKPi_Matched
      - OS_2018_mu_SR_DstarKPi_Matched
      - -SS_2018_el_SR_DstarKPi_Matched
      - -SS_2018_mu_SR_DstarKPi_Matched
    make_plots: False

  2018_wplusd_OS_411MisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi_411MisMatched
      - OS_2018_mu_SR_DstarKPi_411MisMatched
    make_plots: False

  2018_wplusd_SS_411MisMatched:
    regions:
      - SS_2018_el_SR_DstarKPi_411MisMatched
      - SS_2018_mu_SR_DstarKPi_411MisMatched
    make_plots: False

  2018_wplusd_OS-SS_411MisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi_411MisMatched
      - OS_2018_mu_SR_DstarKPi_411MisMatched
      - -SS_2018_el_SR_DstarKPi_411MisMatched
      - -SS_2018_mu_SR_DstarKPi_411MisMatched
    make_plots: False

  2018_wplusd_OS_421MisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi_421MisMatched
      - OS_2018_mu_SR_DstarKPi_421MisMatched
    make_plots: False

  2018_wplusd_SS_421MisMatched:
    regions:
      - SS_2018_el_SR_DstarKPi_421MisMatched
      - SS_2018_mu_SR_DstarKPi_421MisMatched
    make_plots: False

  2018_wplusd_OS-SS_421MisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi_421MisMatched
      - OS_2018_mu_SR_DstarKPi_421MisMatched
      - -SS_2018_el_SR_DstarKPi_421MisMatched
      - -SS_2018_mu_SR_DstarKPi_421MisMatched
    make_plots: False

  2018_wplusd_OS_431MisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi_431MisMatched
      - OS_2018_mu_SR_DstarKPi_431MisMatched
    make_plots: False

  2018_wplusd_SS_431MisMatched:
    regions:
      - SS_2018_el_SR_DstarKPi_431MisMatched
      - SS_2018_mu_SR_DstarKPi_431MisMatched
    make_plots: False

  2018_wplusd_OS-SS_431MisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi_431MisMatched
      - OS_2018_mu_SR_DstarKPi_431MisMatched
      - -SS_2018_el_SR_DstarKPi_431MisMatched
      - -SS_2018_mu_SR_DstarKPi_431MisMatched
    make_plots: False

  2018_wplusd_OS_BaryonMisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi
      - OS_2018_mu_SR_DstarKPi
      - -OS_2018_el_SR_DstarKPi_Matched
      - -OS_2018_mu_SR_DstarKPi_Matched
      - -OS_2018_el_SR_DstarKPi_421MisMatched
      - -OS_2018_mu_SR_DstarKPi_421MisMatched
      - -OS_2018_el_SR_DstarKPi_431MisMatched
      - -OS_2018_mu_SR_DstarKPi_431MisMatched
      - -OS_2018_el_SR_DstarKPi_MxMatched
      - -OS_2018_mu_SR_DstarKPi_MxMatched
      - -OS_2018_el_SR_DstarKPi_MxMisMatched
      - -OS_2018_mu_SR_DstarKPi_MxMisMatched
      - -OS_2018_el_SR_DstarKPi_HardMisMatched
      - -OS_2018_mu_SR_DstarKPi_HardMisMatched
      - -OS_2018_el_SR_DstarKPi_Other
      - -OS_2018_mu_SR_DstarKPi_Other
    make_plots: False

  2018_wplusd_SS_BaryonMisMatched:
    regions:
      - SS_2018_el_SR_DstarKPi
      - SS_2018_mu_SR_DstarKPi
      - -SS_2018_el_SR_DstarKPi_Matched
      - -SS_2018_mu_SR_DstarKPi_Matched
      - -SS_2018_el_SR_DstarKPi_421MisMatched
      - -SS_2018_mu_SR_DstarKPi_421MisMatched
      - -SS_2018_el_SR_DstarKPi_431MisMatched
      - -SS_2018_mu_SR_DstarKPi_431MisMatched
      - -SS_2018_el_SR_DstarKPi_MxMatched
      - -SS_2018_mu_SR_DstarKPi_MxMatched
      - -SS_2018_el_SR_DstarKPi_MxMisMatched
      - -SS_2018_mu_SR_DstarKPi_MxMisMatched
      - -SS_2018_el_SR_DstarKPi_HardMisMatched
      - -SS_2018_mu_SR_DstarKPi_HardMisMatched
      - -SS_2018_el_SR_DstarKPi_Other
      - -SS_2018_mu_SR_DstarKPi_Other
    make_plots: False

  2018_wplusd_OS-SS_BaryonMisMatched:
    regions:
      - OS_2018_el_SR_DstarKPi
      - OS_2018_mu_SR_W#rightarrowl#nu+D, D#rightarrowK#pi#piDstarKPi
      - -OS_2018_el_SR_DstarKPi_Matched
      - -OS_2018_mu_SR_DstarKPi_Matched
      - -OS_2018_el_SR_DstarKPi_421MisMatched
      - -OS_2018_mu_SR_DstarKPi_421MisMatched
      - -OS_2018_el_SR_DstarKPi_431MisMatched
      - -OS_2018_mu_SR_DstarKPi_431MisMatched
      - -OS_2018_el_SR_DstarKPi_MxMatched
      - -OS_2018_mu_SR_DstarKPi_MxMatched
      - -OS_2018_el_SR_DstarKPi_MxMisMatched
      - -OS_2018_mu_SR_DstarKPi_MxMisMatched
      - -OS_2018_el_SR_DstarKPi_HardMisMatched
      - -OS_2018_mu_SR_DstarKPi_HardMisMatched
      - -OS_2018_el_SR_DstarKPi_Other
      - -OS_2018_mu_SR_DstarKPi_Other
      - -SS_2018_el_SR_DstarKPi
      - -SS_2018_mu_SR_DstarKPi
      - SS_2018_el_SR_DstarKPi_Matched
      - SS_2018_mu_SR_DstarKPi_Matched
      - SS_2018_el_SR_DstarKPi_421MisMatched
      - SS_2018_mu_SR_DstarKPi_421MisMatched
      - SS_2018_el_SR_DstarKPi_431MisMatched
      - SS_2018_mu_SR_DstarKPi_431MisMatched
      - SS_2018_el_SR_DstarKPi_MxMatched
      - SS_2018_mu_SR_DstarKPi_MxMatched
      - SS_2018_el_SR_DstarKPi_MxMisMatched
      - SS_2018_mu_SR_DstarKPi_MxMisMatched
      - SS_2018_el_SR_DstarKPi_HardMisMatched
      - SS_2018_mu_SR_DstarKPi_HardMisMatched
      - SS_2018_el_SR_DstarKPi_Other
      - SS_2018_mu_SR_DstarKPi_Other
    make_plots: False

  2018_wplusd_OS_HardScatter:
    regions:
      - OS_2018_el_SR_DstarKPi_MxMatched
      - OS_2018_mu_SR_DstarKPi_MxMatched
      - OS_2018_el_SR_DstarKPi_MxMisMatched
      - OS_2018_mu_SR_DstarKPi_MxMisMatched
      - OS_2018_el_SR_DstarKPi_HardMisMatched
      - OS_2018_mu_SR_DstarKPi_HardMisMatched
    make_plots: False

  2018_wplusd_SS_HardScatter:
    regions:
      - SS_2018_el_SR_DstarKPi_MxMatched
      - SS_2018_mu_SR_DstarKPi_MxMatched
      - SS_2018_el_SR_DstarKPi_MxMisMatched
      - SS_2018_mu_SR_W#rightarrowl#nu+D, D#rightarrowK#pi#piDstarKPi_MxMisMatched
      - SS_2018_el_SR_DstarKPi_HardMisMatched
      - SS_2018_mu_SR_DstarKPi_HardMisMatched
    make_plots: False

  2018_wplusd_OS-SS_HardScatter:
    regions:
      - OS_2018_el_SR_DstarKPi_MxMatched
      - OS_2018_mu_SR_DstarKPi_MxMatched
      - OS_2018_el_SR_DstarKPi_MxMisMatched
      - OS_2018_mu_SR_DstarKPi_MxMisMatched
      - OS_2018_el_SR_DstarKPi_HardMisMatched
      - OS_2018_mu_SR_DstarKPi_HardMisMatched
      - -SS_2018_el_SR_DstarKPi_MxMatched
      - -SS_2018_mu_SR_DstarKPi_MxMatched
      - -SS_2018_el_SR_DstarKPi_MxMisMatched
      - -SS_2018_mu_SR_DstarKPi_MxMisMatched
      - -SS_2018_el_SR_DstarKPi_HardMisMatched
      - -SS_2018_mu_SR_DstarKPi_HardMisMatched
    make_plots: False

  2018_wplusd_OS_NoMatch:
    regions:
      - OS_2018_el_SR_DstarKPi_Other
      - OS_2018_mu_SR_DstarKPi_Other
    make_plots: False

  2018_wplusd_SS_NoMatch:
    regions:
      - SS_2018_el_SR_DstarKPi_Other
      - SS_2018_mu_SR_DstarKPi_Other
    make_plots: False

  2018_wplusd_OS-SS_NoMatch:
    regions:
      - OS_2018_el_SR_DstarKPi_Other
      - OS_2018_mu_SR_DstarKPi_Other
      - -SS_2018_el_SR_DstarKPi_Other
      - -SS_2018_mu_SR_DstarKPi_Other
    make_plots: False