variablesConf: charmed_wjets_dstar

samplesConf: madgraph

data: Data

samples:
  - Top
  - Wjets_cjets_emu
  - Wjets_bjets_emu
  - Wjets_light_emu
  - Wjets_tau
  - Zjets
  - Diboson

channels:
  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR_DstarKPi
    label:
      - 'W#rightarrowe#nu+D, D#rightarrow(K#pi)#pi, OS'
      - 'MGPy8EG'
    lumi: '2018'

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR_DstarKPi
    label:
      - 'W#rightarrowe#nu+D, D#rightarrow(K#pi)#pi, SS'
      - 'MGPy8EG'
    lumi: '2018'

  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR_DstarKPi
      - -SS_2018_el_SR_DstarKPi
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Top
      - Wjets_tau
      - Zjets
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrow(K#pi)#pi, OS-SS'
      - 'MGPy8EG'
    lumi: '2018'

  2018_mu_wplusd_OS:
    regions:
      - OS_2018_mu_SR_DstarKPi
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrow(K#pi)#pi, OS'
      - 'MGPy8EG'
    lumi: '2018'

  2018_mu_wplusd_SS:
    regions:
      - SS_2018_mu_SR_DstarKPi
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrow(K#pi)#pi, SS'
      - 'MGPy8EG'
    lumi: '2018'

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR_DstarKPi
      - -SS_2018_mu_SR_DstarKPi
    samples:
      - Wjets_cjets_emu
      - Wjets_bjets_emu
      - Wjets_light_emu
      - Top
      - Wjets_tau
      - Zjets
      - Diboson
    label:
      - 'W#rightarrow#mu#nu+D, D#rightarrow(K#pi)#pi, OS-SS'
      - 'MGPy8EG'
    lumi: '2018'
