variablesConf: charmed_wjets

samplesConf: wplusd_data_data

channels:
  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR_Dplus
      - -SS_2018_el_SR_Dplus
    samples:
      - data
      - data_ref
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR_Dplus
      - -SS_2018_mu_SR_Dplus
    samples:
      - data
      - data_ref
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR_Dplus
    samples:
      - data
      - data_ref
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_mu_wplusd_OS:
    regions:
      - OS_2018_mu_SR_Dplus
    samples:
      - data
      - data_ref
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR_Dplus
    samples:
      - data
      - data_ref
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_mu_wplusd_SS:
    regions:
      - SS_2018_mu_SR_Dplus
    samples:
      - data
      - data_ref
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'
