colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets

samplesConf: common

data: Data

samples:
  - Powheg_Wjets_light
  - Powheg_Wjets_tau
  - Sherpa_Zjets
  - Top
  - Diboson

channels:

  2018_mu_wplusd_OS-SS:
    regions:
      - OS_2018_mu_SR
      - -SS_2018_mu_SR
    label: 'W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'
