colorScheme: cheer_up_emo_kid

variablesConf: charmed_wjets

samplesConf: common

data: Data

samples:
  - Powheg_Wjets_light
  - Powheg_Wjets_tau
  - Sherpa_Zjets
  - Top
  - Diboson

channels:

  2018_el_wplusd_OS:
    regions:
      - OS_2018_el_SR
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_el_wplusd_SS:
    regions:
      - SS_2018_el_SR
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_el_wplusd_OS-SS:
    regions:
      - OS_2018_el_SR
      - -SS_2018_el_SR
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS-SS'
    lumi: '2018'

  2018_el_wplusd_PT_Template_OS:
    regions:
      - OS_2018_el_QCD
    samples:
      - Multijet_Powheg
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet_Powheg

  2018_el_wplusd_PT_Template_SS:
    regions:
      - SS_2018_el_QCD
    samples:
      - Multijet_Powheg
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
      - 'MET < 30 GeV, no m_{T} cut'
    lumi: '2018'
    qcd_template: Multijet_Powheg

  2018_el_wplusd_PT_Loose_OS:
    regions:
      - OS_2018_el
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
      - 'Loose SR for PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Loose_SS:
    regions:
      - SS_2018_el
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Diboson
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
      - 'Loose SR for PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Fit_OS:
    regions:
      - OS_2018_el
    samples:
      - EWK_Powheg
      - Multijet_Powheg | 2018_el_wplusd_PT_Template_OS
    likelihood_fit:
      variable: lep_pt
      range: [28, 100]
      extrapolated_region: 2018_el_wplusd_PT_Extrapolated_OS
      extrapolated_multijet: 2018_el_wplusd_PTCut_Template_OS
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
      - 'Likelihood PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Fit_SS:
    regions:
      - SS_2018_el
    samples:
      - EWK_Powheg
      - Multijet_Powheg | 2018_el_wplusd_PT_Template_SS
    likelihood_fit:
      variable: lep_pt
      range: [28, 100]
      extrapolated_region: 2018_el_wplusd_PT_Extrapolated_SS
      extrapolated_multijet: 2018_el_wplusd_PTCut_Template_SS
    label:
      - 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
      - 'Likelihood PT fit'
    lumi: '2018'

  2018_el_wplusd_PT_Extrapolated_OS:
    regions:
      - OS_2018_el_SR
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_el_wplusd_PTCut_Template_OS
      - Diboson
    scale_factors:
      input_file: 2018_el_wplusd_PT_Fit_OS.json
      ewk: EWK_Powheg
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, OS'
    lumi: '2018'

  2018_el_wplusd_PT_Extrapolated_SS:
    regions:
      - SS_2018_el_SR
    samples:
      - Powheg_Wjets_light
      - Powheg_Wjets_tau
      - Sherpa_Zjets
      - Top
      - Multijet_Powheg | 2018_el_wplusd_PTCut_Template_SS
      - Diboson
    scale_factors:
      input_file: 2018_el_wplusd_PT_Fit_SS.json
      ewk: EWK_Powheg
    label: 'W#rightarrowe#nu+D, D#rightarrowK#pi#pi, SS'
    lumi: '2018'

  2018_el_wplusd_PTCut_Template_OS:
    regions:
      - OS_2018_el_QCD_PTCut
    make_plots: False

  2018_el_wplusd_PTCut_Template_SS:
    regions:
      - SS_2018_el_QCD_PTCut
    make_plots: False
