colorScheme: cheer_up_emo_kid

variablesConf: inclusive_zjets

samplesConf: common

data: Data

samples:
  - Sherpa_Zjets_light
  - Sherpa_Zjets_tau
  - Diboson
  - Top

channels:
  2018_el:
    regions:
      - 2018_el
    label: '2018 el SR'
    lumi: '2018'
  2018_mu:
    regions:
      - 2018_mu
    label: '2018 mu SR'
    lumi: '2018'
  2018_el_rw:
    regions:
      - 2018_el_rw
    label:
      - '2018 el SR'
      - 'p_{T}(V) reweighted'
    lumi: '2018'
  2018_mu_rw:
    regions:
      - 2018_mu_rw
    label:
      - '2018 mu SR'
      - 'p_{T}(V) reweighted'
    lumi: '2018'
