colorScheme: gemstone_hues

variablesConf: charmed_wjets

samplesConf: madgraph

data: Data

channels:
  el_QCD_mtCtrl_metSig_0tag_Dplus:
    regions:
      - el_QCD_mtCtrl_metSig_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_el_QCD_mtCtrl_metSig_0tag_Dplus
    label:
      - "W(e^{#pm})+D, 0-tag"
      - "mT < 40 GeV, MET > 30 GeV"
    lumi: "2015+2016A-B+2016C-L+2017+2018"
    save_to_file: True

  el_QCD_mtCtrl_metCtrl_0tag_Dplus:
    regions:
      - el_QCD_mtCtrl_metCtrl_0tag_Dplus
    samples:
      - Wjets
      - Zjets
      - Top
      - Diboson
      - Multijet_MatrixMethod | MatrixMethod_el_QCD_mtCtrl_metCtrl_0tag_Dplus
    label:
      - "W(e^{#pm})+D, 0-tag"
      - "mT < 40 GeV, MET < 30 GeV"
    lumi: "2015+2016A-B+2016C-L+2017+2018"
    save_to_file: True

  MatrixMethod_el_QCD_mtCtrl_metSig_0tag_Dplus:
    make_plots: false
    save_to_file: false
    regions:
      - AntiTight_el_QCD_mtCtrl_metSig_0tag_Dplus
      - -Tight_el_QCD_mtCtrl_metSig_0tag_Dplus

  MatrixMethod_el_QCD_mtCtrl_metCtrl_0tag_Dplus:
    make_plots: false
    save_to_file: false
    regions:
      - AntiTight_el_QCD_mtCtrl_metCtrl_0tag_Dplus
      - -Tight_el_QCD_mtCtrl_metCtrl_0tag_Dplus
