---
variablesConf: charmed_wjets_truth
samplesConf: wplusd_truth
systematics:
  - sherpa2211_theory_qcd
  # - sherpa2211_theory_as
  # - sherpa2211_theory_pdf
  # - sherpa2211_theory_ew

channels:
  OS-SS_Dplus:
    regions:
      - el_minus_Dplus_OS
      - el_plus_Dplus_OS
      - mu_minus_Dplus_OS
      - mu_plus_Dplus_OS
      - -el_minus_Dplus_SS
      - -el_plus_Dplus_SS
      - -mu_minus_Dplus_SS
      - -mu_plus_Dplus_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrowl#nu+D, Truth-level
      - inclusive OS-SS
  OS-SS_el_minus_Dplus:
    regions:
      - el_minus_Dplus_OS
      - -el_minus_Dplus_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrowe#nu+D, Truth-level
      - inclusive OS-SS
  OS-SS_el_plus_Dplus:
    regions:
      - el_plus_Dplus_OS
      - -el_plus_Dplus_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrowe#nu+D, Truth-level
      - inclusive OS-SS
  OS-SS_mu_minus_Dplus:
    regions:
      - mu_minus_Dplus_OS
      - -mu_minus_Dplus_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrow#mu#nu+D, Truth-level
      - inclusive OS-SS
  OS-SS_mu_plus_Dplus:
    regions:
      - mu_plus_Dplus_OS
      - -mu_plus_Dplus_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrow#mu#nu+D, Truth-level
      - inclusive OS-SS

  Dmeson:
    regions:
      - el_minus_Dmeson_OS
      - el_plus_Dmeson_OS
      - mu_minus_Dmeson_OS
      - mu_plus_Dmeson_OS
      - el_minus_Dmeson_SS
      - el_plus_Dmeson_SS
      - mu_minus_Dmeson_SS
      - mu_plus_Dmeson_SS
    samples:
      - Sherpa2211_Wjets
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
    label:
      - W#rightarrowl#nu+D, Truth-level
      - inclusive OS+SS
  OS-SS_Dmeson:
    regions:
      - el_minus_Dmeson_OS
      - el_plus_Dmeson_OS
      - mu_minus_Dmeson_OS
      - mu_plus_Dmeson_OS
      - -el_minus_Dmeson_SS
      - -el_plus_Dmeson_SS
      - -mu_minus_Dmeson_SS
      - -mu_plus_Dmeson_SS
    samples:
      - Sherpa2211_Wjets
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
    label:
      - W#rightarrowl#nu+D, Truth-level
      - inclusive OS-SS

  # D+ -> Kpipi
  OS-SS_Dplus_Kpipi:
    regions:
      - el_minus_Dplus_OS_Kpipi
      - el_plus_Dplus_OS_Kpipi
      - mu_minus_Dplus_OS_Kpipi
      - mu_plus_Dplus_OS_Kpipi
      - -el_minus_Dplus_SS_Kpipi
      - -el_plus_Dplus_SS_Kpipi
      - -mu_minus_Dplus_SS_Kpipi
      - -mu_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_el_minus_Dplus_Kpipi:
    regions:
      - el_minus_Dplus_OS_Kpipi
      - -el_minus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowe#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_el_plus_Dplus_Kpipi:
    regions:
      - el_plus_Dplus_OS_Kpipi
      - -el_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrore#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_mu_minus_Dplus_Kpipi:
    regions:
      - mu_minus_Dplus_OS_Kpipi
      - -mu_minus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_mu_plus_Dplus_Kpipi:
    regions:
      - mu_plus_Dplus_OS_Kpipi
      - -mu_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_lep_plus_Dplus_Kpipi:
    regions:
      - mu_plus_Dplus_OS_Kpipi
      - -mu_plus_Dplus_SS_Kpipi
      - el_plus_Dplus_OS_Kpipi
      - -el_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_lep_minus_Dplus_Kpipi:
    regions:
      - mu_minus_Dplus_OS_Kpipi
      - -mu_minus_Dplus_SS_Kpipi
      - el_minus_Dplus_OS_Kpipi
      - -el_minus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS

  # W+D*
  OS-SS_Dstar:
    regions:
      - el_minus_Dstar_OS
      - el_plus_Dstar_OS
      - mu_minus_Dstar_OS
      - mu_plus_Dstar_OS
      - -el_minus_Dstar_SS
      - -el_plus_Dstar_SS
      - -mu_minus_Dstar_SS
      - -mu_plus_Dstar_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrowl#nu+D*, Truth-level
      - inclusive OS-SS
  OS-SS_el_minus_Dstar:
    regions:
      - el_minus_Dstar_OS
      - -el_minus_Dstar_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrowe#nu+D*, Truth-level
      - inclusive OS-SS
  OS-SS_el_plus_Dstar:
    regions:
      - el_plus_Dstar_OS
      - -el_plus_Dstar_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrowe#nu+D*, Truth-level
      - inclusive OS-SS
  OS-SS_mu_minus_Dstar:
    regions:
      - mu_minus_Dstar_OS
      - -mu_minus_Dstar_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrow#mu#nu+D*, Truth-level
      - inclusive OS-SS
  OS-SS_mu_plus_Dstar:
    regions:
      - mu_plus_Dstar_OS
      - -mu_plus_Dstar_SS
    samples:
      - MG_Wjets
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
    label:
      - W#rightarrow#mu#nu+D*, Truth-level
      - inclusive OS-SS

  # D* -> Kpipi
  OS-SS_Dstar_Kpipi:
    regions:
      - el_minus_Dstar_OS_Kpipi
      - el_plus_Dstar_OS_Kpipi
      - mu_minus_Dstar_OS_Kpipi
      - mu_plus_Dstar_OS_Kpipi
      - -el_minus_Dstar_SS_Kpipi
      - -el_plus_Dstar_SS_Kpipi
      - -mu_minus_Dstar_SS_Kpipi
      - -mu_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowl#nu+D, D*#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_el_minus_Dstar_Kpipi:
    regions:
      - el_minus_Dstar_OS_Kpipi
      - -el_minus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowe#nu+D, D*#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_el_plus_Dstar_Kpipi:
    regions:
      - el_plus_Dstar_OS_Kpipi
      - -el_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrore#nu+D, D*#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_mu_minus_Dstar_Kpipi:
    regions:
      - mu_minus_Dstar_OS_Kpipi
      - -mu_minus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrow#mu#nu+D, D*#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_mu_plus_Dstar_Kpipi:
    regions:
      - mu_plus_Dstar_OS_Kpipi
      - -mu_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrow#mu#nu+D, D*#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_lep_plus_Dstar_Kpipi:
    regions:
      - mu_plus_Dstar_OS_Kpipi
      - -mu_plus_Dstar_SS_Kpipi
      - el_plus_Dstar_OS_Kpipi
      - -el_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS
  OS-SS_lep_minus_Dstar_Kpipi:
    regions:
      - mu_minus_Dstar_OS_Kpipi
      - -mu_minus_Dstar_SS_Kpipi
      - el_minus_Dstar_OS_Kpipi
      - -el_minus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - MGFxFx_Wjets
      - MGFxFx_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi, Truth-level
      - inclusive OS-SS