---
variablesConf: charmed_wjets_truth
samplesConf: wplusd_truth
systematics:
  - sherpa2211_theory_qcd
  - sherpa2211_theory_as
  - sherpa2211_theory_pdf
  - sherpa2211_theory_ew

channels:
  # lep:
  #   regions:
  #     - el_minus
  #     - el_plus
  #     - mu_minus
  #     - mu_plus
  #   samples:
  #     - Sherpa2211_Wjets_cjets_e | el
  #     - Sherpa2211_Wjets_bjets_e | el
  #     - Sherpa2211_Wjets_light_e | el
  #     - Sherpa2211_Wjets_cjets_mu | mu
  #     - Sherpa2211_Wjets_bjets_mu | mu
  #     - Sherpa2211_Wjets_light_mu | mu
  #   label:
  #     - W#rightarrowl#nu
  #     - inclusive, Truth-level
  # el:
  #   regions:
  #     - el_minus
  #     - el_plus
  #   samples:
  #     # - MG_Wjets
  #     # - MGPy8EG_NLO_WplusD
  #     - Sherpa2211_WplusD
  #     - Sherpa2211_Wjets
  #     # - Sherpa_Wjets
  #   label:
  #     - W#rightarrowe#nu
  #     - inclusive, Truth-level
  # mu:
  #   regions:
  #     - mu_minus
  #     - mu_plus
  #   samples:
  #     # - MG_Wjets
  #     # - MGPy8EG_NLO_WplusD
  #     - Sherpa2211_WplusD
  #     - Sherpa2211_Wjets
  #     # - Sherpa_Wjets
  #   label:
  #     - W#rightarrow#mu#nu
  #     - inclusive, Truth-level
  # OS-SS_Dplus:
  #   regions:
  #     - el_minus_Dplus_OS
  #     - el_plus_Dplus_OS
  #     - mu_minus_Dplus_OS
  #     - mu_plus_Dplus_OS
  #     - -el_minus_Dplus_SS
  #     - -el_plus_Dplus_SS
  #     - -mu_minus_Dplus_SS
  #     - -mu_plus_Dplus_SS
  #   samples:
  #     - MG_Wjets
  #     - MGPy8EG_NLO_WplusD
  #     - Sherpa2211_WplusD
  #     - Sherpa2211_Wjets
  #     # - Sherpa_Wjets
  #   label:
  #     - W#rightarrowl#nu+D
  #     - inclusive OS-SS, Truth-level
  # OS-SS_el_Dplus:
  #   regions:
  #     - el_minus_Dplus_OS
  #     - el_plus_Dplus_OS
  #     - -el_minus_Dplus_SS
  #     - -el_plus_Dplus_SS
  #   samples:
  #     - MG_Wjets
  #     - MGPy8EG_NLO_WplusD
  #     - Sherpa2211_WplusD
  #     - Sherpa2211_Wjets
  #     # - Sherpa_Wjets
  #   label:
  #     - W#rightarrowe#nu+D
  #     - inclusive OS-SS, Truth-level
  # OS-SS_mu_Dplus:
  #   regions:
  #     - mu_minus_Dplus_OS
  #     - mu_plus_Dplus_OS
  #     - -mu_minus_Dplus_SS
  #     - -mu_plus_Dplus_SS
  #   samples:
  #     - MG_Wjets
  #     - MGPy8EG_NLO_WplusD
  #     - Sherpa2211_WplusD
  #     - Sherpa2211_Wjets
  #     # - Sherpa_Wjets
  #   label:
  #     - W#rightarrow#mu#nu+D
  #     - inclusive OS-SS, Truth-level


  # D+ -> Kpipi
  OS-SS_Dplus_Kpipi:
    regions:
      - el_minus_Dplus_OS_Kpipi
      - el_plus_Dplus_OS_Kpipi
      - mu_minus_Dplus_OS_Kpipi
      - mu_plus_Dplus_OS_Kpipi
      - -el_minus_Dplus_SS_Kpipi
      - -el_plus_Dplus_SS_Kpipi
      - -mu_minus_Dplus_SS_Kpipi
      - -mu_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_el_minus_Dplus_Kpipi:
    regions:
      - el_minus_Dplus_OS_Kpipi
      - -el_minus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowe#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_el_plus_Dplus_Kpipi:
    regions:
      - el_plus_Dplus_OS_Kpipi
      - -el_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrore#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_mu_minus_Dplus_Kpipi:
    regions:
      - mu_minus_Dplus_OS_Kpipi
      - -mu_minus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_mu_plus_Dplus_Kpipi:
    regions:
      - mu_plus_Dplus_OS_Kpipi
      - -mu_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrow#mu#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_lep_plus_Dplus_Kpipi:
    regions:
      - mu_plus_Dplus_OS_Kpipi
      - -mu_plus_Dplus_SS_Kpipi
      - el_plus_Dplus_OS_Kpipi
      - -el_plus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_lep_minus_Dplus_Kpipi:
    regions:
      - mu_minus_Dplus_OS_Kpipi
      - -mu_minus_Dplus_SS_Kpipi
      - el_minus_Dplus_OS_Kpipi
      - -el_minus_Dplus_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level


  # D* -> Kpipi
  OS-SS_Dstar_Kpipi:
    regions:
      - el_minus_Dstar_OS_Kpipi
      - el_plus_Dstar_OS_Kpipi
      - mu_minus_Dstar_OS_Kpipi
      - mu_plus_Dstar_OS_Kpipi
      - -el_minus_Dstar_SS_Kpipi
      - -el_plus_Dstar_SS_Kpipi
      - -mu_minus_Dstar_SS_Kpipi
      - -mu_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowl#nu+D, D*#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_el_minus_Dstar_Kpipi:
    regions:
      - el_minus_Dstar_OS_Kpipi
      - -el_minus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowe#nu+D, D*#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_el_plus_Dstar_Kpipi:
    regions:
      - el_plus_Dstar_OS_Kpipi
      - -el_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrore#nu+D, D*#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_mu_minus_Dstar_Kpipi:
    regions:
      - mu_minus_Dstar_OS_Kpipi
      - -mu_minus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrow#mu#nu+D, D*#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_mu_plus_Dstar_Kpipi:
    regions:
      - mu_plus_Dstar_OS_Kpipi
      - -mu_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrow#mu#nu+D, D*#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_lep_plus_Dstar_Kpipi:
    regions:
      - mu_plus_Dstar_OS_Kpipi
      - -mu_plus_Dstar_SS_Kpipi
      - el_plus_Dstar_OS_Kpipi
      - -el_plus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level
  OS-SS_lep_minus_Dstar_Kpipi:
    regions:
      - mu_minus_Dstar_OS_Kpipi
      - -mu_minus_Dstar_SS_Kpipi
      - el_minus_Dstar_OS_Kpipi
      - -el_minus_Dstar_SS_Kpipi
    samples:
      - MG_Wjets
      - MGPy8EG_NLO_WplusD
      - Sherpa2211_WplusD
      - Sherpa2211_Wjets
      # - Sherpa_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS, Truth-level