---
variablesConf: charmed_wjets_truth
samplesConf: wplusd_truth
channels:

  OS-SS_Dplus:
    regions:
      - el_minus_Dplus_OS
      - el_plus_Dplus_OS
      - mu_minus_Dplus_OS
      - mu_plus_Dplus_OS
      - -el_minus_Dplus_SS
      - -el_plus_Dplus_SS
      - -mu_minus_Dplus_SS
      - -mu_plus_Dplus_SS
    samples:
      - MG_Wjets
      - Powheg_Wjets
      - Sherpa_Wjets
      - Sherpa2210_Wjets
      - MGFxFx_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - inclusive OS-SS
  OS-SS_el_minus_Dplus:
    regions:
      - el_minus_Dplus_OS
      - -el_minus_Dplus_SS
    samples:
      - MG_Wjets
      - Powheg_Wjets
      - Sherpa_Wjets
      - Sherpa2210_Wjets
      - MGFxFx_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - el_minus OS-SS
  OS-SS_el_plus_Dplus:
    regions:
      - el_plus_Dplus_OS
      - -el_plus_Dplus_SS
    samples:
      - MG_Wjets
      - Powheg_Wjets
      - Sherpa_Wjets
      - Sherpa2210_Wjets
      - MGFxFx_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - el_plus OS-SS
  OS-SS_mu_minus_Dplus:
    regions:
      - mu_minus_Dplus_OS
      - -mu_minus_Dplus_SS
    samples:
      - MG_Wjets
      - Powheg_Wjets
      - Sherpa_Wjets
      - Sherpa2210_Wjets
      - MGFxFx_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - mu_minus OS-SS
  OS-SS_mu_plus_Dplus:
    regions:
      - mu_plus_Dplus_OS
      - -mu_plus_Dplus_SS
    samples:
      - MG_Wjets
      - Powheg_Wjets
      - Sherpa_Wjets
      - Sherpa2210_Wjets
      - MGFxFx_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - mu_plus OS-SS
  OS-SS_mu_Dplus:
    regions:
      - mu_minus_Dplus_OS
      - -mu_minus_Dplus_SS
      - mu_plus_Dplus_OS
      - -mu_plus_Dplus_SS
    samples:
      - MG_Wjets
      - Powheg_Wjets
      - Sherpa_Wjets
      - Sherpa2210_Wjets
      - MGFxFx_Wjets
    label:
      - W#rightarrowl#nu+D, D#rightarrowK#pi#pi
      - mu OS-SS
