colorScheme: gemstone_hues

Wjets_emu_Rest:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "11002"
  legendLabel: "W+jets"
  shortName: Wjets_emu_Rest

Wjets_emu_Rest_Loose:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
    - MG_Wjets_tau
  subtract:
  lineColor: "21000"
  legendLabel: "W+jets Loose"
  shortName: Wjets_emu_Rest_Loose

Wjets_emu_MisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
    - MG_Wjets_tau
  subtract:
  lineColor: "11004"
  legendLabel: "W+c^{mis-match}"
  shortName: Wjets_emu_MisMatched

Wjets_emu_MisMatched_Loose:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
    - MG_Wjets_tau
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+c^{mis-match}"
  shortName: Wjets_emu_MisMatched_Loose

DibosonZjets:
  add:
    - Diboson
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  lineColor: "15002"
  legendLabel: "Other"
  shortName: DibosonZjets

DibosonZjets_Loose:
  add:
    - Diboson
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  lineColor: "21000"
  legendLabel: "Loose Other"
  shortName: DibosonZjets_Loose

Multijet_MatrixMethod:
  add: data
  subtract:
  lineColor: "14003"
  legendLabel: "MJ"
  shortName: Multijet_MatrixMethod

Multijet_MatrixMethod_Loose:
  add: data
  subtract:
  lineColor: "21000"
  legendLabel: "Loose MJ"
  shortName: Multijet_MatrixMethod_Loose

Wjets_emu_Rest_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Loose Inclusive W+jets"
  shortName: Wjets_emu_Rest_PostProc

Wjets_emu_Rest_PostProc_Loose:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "15002"
  legendLabel: "Loose W+jets"
  shortName: Wjets_emu_Rest_PostProc_Loose

Wjets_emu_Rest_Fit:
  add:
    - wjets_bkg_fit
  subtract:
  lineColor: "21000"
  legendLabel: "W+jets Fit"
  shortName: Wjets_emu_Rest_Fit

Wjets_emu_Rest_Fit_Loose:
  add:
    - wjets_bkg_fit
  subtract:
  lineColor: "15002"
  legendLabel: "W+jets Fit Loose"
  shortName: Wjets_emu_Rest_Fit_Loose

Sherpa_Wjets_emu_Rest_Fit:
  add:
    - sherpa_wjets_bkg_fit
  subtract:
  lineColor: "15002"
  legendLabel: "Sherpa W+jets Fit"
  shortName: Sherpa_Wjets_emu_Rest_Fit

Wjets_emu_MisMatched_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+c^{mis-match}"
  shortName: Wjets_emu_MisMatched_PostProc

DibosonZjets_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Loose Other"
  shortName: DibosonZjets_PostProc

MultiJet_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Loose MJ"
  shortName: MultiJet_PostProc

Sherpa_Wjets_emu_Rest:
  add:
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_highpt_emu
    - Sh_Wjets_light_emu
    - Sh_Wjets_tau
  subtract:
  lineColor: "14002"
  legendLabel: "Sherpa W+jets"
  shortName: Sherpa_Wjets_emu_Rest

Sherpa_Wjets_emu_Rest_PostProc:
  add:
    - inclusive_sherpa_bkg
  subtract:
  lineColor: "14004"
  legendLabel: "Sherpa W+jets"
  shortName: Sherpa_Wjets_emu_Rest_PostProc

Powheg_Wjets_emu_Rest:
  add:
    - Ph_Wjets_emu
    - Ph_Wjets_tau
  subtract:
  lineColor: "11004"
  legendLabel: "Powheg W+jets"
  shortName: Powheg_Wjets_emu_Rest

Powheg_Wjets_emu_Rest_PostProc:
  add:
    - inclusive_powheg_bkg
  subtract:
  lineColor: "11004"
  legendLabel: "Powheg W+jets"
  shortName: Powheg_Wjets_emu_Rest_PostProc