Data:
  add: data
  subtract:

Sherpa_Wjets:
  add:
    - Sh_Wjets
  subtract:
  fillColor: "10000"
  legendLabel: W+jets

Sherpa_Wjets_light:
  add: Sh_Wjets_light
  subtract:
  fillColor: "10000"
  lineColor: "10001"
  legendLabel: W#rightarrowl#nu

Sherpa_Wjets_tau:
  add: Sh_Wjets_tau
  subtract:
  fillColor: "10001"
  lineColor: "10000"
  legendLabel: W#rightarrow#tau#nu

Powheg_Wjets:
  add:
    - Ph_Wjets_light
    - Ph_Wjets_tau
  subtract:
  fillColor: "10000"
  lineColor: "10001"
  legendLabel: W+jets

Powheg_Wjets_light:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10000"
  lineColor: "10001"
  legendLabel: W#rightarrowl#nu

Powheg_Wjets_tau:
  add: Ph_Wjets_tau
  subtract:
  fillColor: "10001"
  lineColor: "10000"
  legendLabel: W#rightarrow#tau#nu

Sherpa_Zjets:
  add:
    - Sh_Zjets_light
    - Sh_Zjets_tau
  subtract:
  fillColor: "10002"
  lineColor: "10003"
  legendLabel: Z+jets

Sherpa_Zjets_light:
  add: Sh_Zjets_light
  subtract:
  fillColor: "10002"
  lineColor: "10003"
  legendLabel: Z#rightarrowll

Sherpa_Zjets_tau:
  add: Sh_Zjets_tau
  subtract:
  fillColor: "10003"
  lineColor: "10002"
  legendLabel: Z#rightarrow#tau#tau

Top:
  add: Top
  subtract:
  fillColor: "10004"

Diboson:
  add: Diboson
  subtract:
  fillColor: "10005"

EWK:
  add:
    - Sh_Wjets
    - Sh_Zjets
    - Top
    - Diboson
  subtract:
  fillColor: "10000"
  legendLabel: EWK

Multijet:
  add: data
  subtract:
    - Sh_Wjets
    - Sh_Zjets
    - Top
    - Diboson
  fillColor: "10006"
  legendLabel: Multijet
