colorScheme: cheer_up_emo_kid

Data:
  add: data
  subtract:

DataMinusBackground:
  add: data
  subtract:
    - Ph_Wjets_tau
    - Sh_Zjets
    - Top
    - Diboson

Sherpa_Wjets:
  add:
    - Sh_Wjets
  subtract:
  fillColor: "10000"
  legendLabel: W+jets

Sherpa_Wjets_light:
  add: Sh_Wjets_light
  subtract:
  fillColor: "10000"
  lineColor: "10001"
  legendLabel: W#rightarrowl#nu

Sherpa_Wjets_tau:
  add: Sh_Wjets_tau
  subtract:
  fillColor: "10001"
  lineColor: "10000"
  legendLabel: W#rightarrow#tau#nu

Powheg_Wjets:
  add:
    - Ph_Wjets
  subtract:
  fillColor: "10000"
  lineColor: "10001"
  legendLabel: W+jets

Powheg_Wjets_light:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10000"
  lineColor: "10001"
  legendLabel: W#rightarrowl#nu

Powheg_Wjets_tau:
  add: Ph_Wjets_tau
  subtract:
  fillColor: "10001"
  lineColor: "10000"
  legendLabel: W#rightarrow#tau#nu

Powheg_Zjets:
  add:
    - Ph_Zjets
  subtract:
  fillColor: "10002"
  lineColor: "10003"
  legendLabel: Z+jets

Powheg_Zjets_light:
  add: Ph_Zjets_light
  subtract:
  fillColor: "10002"
  lineColor: "10003"
  legendLabel: Z#rightarrowll

Powheg_Zjets_tau:
  add: Ph_Zjets_tau
  subtract:
  fillColor: "10003"
  lineColor: "10002"
  legendLabel: Z#rightarrow#tau#tau

Sherpa_Zjets:
  add:
    - Sh_Zjets_light
    - Sh_Zjets_tau
  subtract:
  fillColor: "10002"
  lineColor: "10003"
  legendLabel: Z+jets

Sherpa_Zjets_light:
  add: Sh_Zjets_light
  subtract:
  fillColor: "10002"
  lineColor: "10003"
  legendLabel: Z#rightarrowll

Sherpa_Zjets_tau:
  add: Sh_Zjets_tau
  subtract:
  fillColor: "10003"
  lineColor: "10002"
  legendLabel: Z#rightarrow#tau#tau

Top:
  add: Top
  subtract:
  fillColor: "10004"
  legendLabel: Top

Diboson:
  add: Diboson
  subtract:
  fillColor: "10005"
  legendLabel: Diboson

EWK:
  add:
    - Sh_Wjets
    - Sh_Zjets
    - Top
    - Diboson
  subtract:
  fillColor: "10000"
  legendLabel: EWK

EWK_Powheg:
  add:
    - Ph_Wjets
    - Sh_Zjets
    - Top
    - Diboson
  subtract:
  fillColor: "10000"
  legendLabel: EWK

Sherpa_VJets:
  add:
    - Sh_Wjets
    - Sh_Zjets
  subtract:
  fillColor: "10000"
  legendLabel: V+jets

VJets:
  add:
    - Ph_Wjets
    - Sh_Zjets
  subtract:
  fillColor: "10000"
  legendLabel: V+jets

WJetsTop:
  add:
    - Ph_Wjets
    - Top
  subtract:
  fillColor: "10000"
  legendLabel: W+jets + Top

Multijet:
  add: data
  subtract:
    - Sh_Wjets
    - Sh_Zjets
    - Top
    - Diboson
  fillColor: "10006"
  legendLabel: Multijet

Multijet_Powheg:
  add: data
  subtract:
    - Ph_Wjets
    - Sh_Zjets
    - Top
    - Diboson
  fillColor: "10006"
  legendLabel: Multijet

Multijet_Sherpa:
  add: data
  subtract:
    - Sh_Wjets
    - Sh_Zjets
    - Top
    - Diboson
  fillColor: "10006"
  legendLabel: Multijet
