colorScheme: cheer_up_emo_kid_extended

Data:
  add: data
  subtract:

Wjets_light_Matched:
  add: MG_Wjets_light
  subtract:
  fillColor: "10002"
  legendLabel: 'W+#it{D}'
  fitName: Wjets_light_Matched

Wjets_light_MisMatched:
  add: MG_Wjets_light
  subtract:
  fillColor: "10001"
  legendLabel: 'W+#it{D} Mis'

Wjets_light_Rest:
  add: MG_Wjets_light
  subtract:
  fillColor: "10000"
  legendLabel: W+jets
  fitName: Wjets_light_Rest

Wjets_tau:
  add: MG_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: W#rightarrow#tau#nu

Zjets:
  add:
    - MG_Zjets_light
    - MG_Zjets_tau
  subtract:
  fillColor: "10004"
  legendLabel: Z+jets

Zjets_light:
  add: MG_Zjets_light
  subtract:
  fillColor: "10004"
  legendLabel: Z#rightarrowll

Zjets_tau:
  add: MG_Zjets_tau
  subtract:
  fillColor: "10005"
  legendLabel: Z#rightarrow#tau#tau

Top:
  add: Top
  subtract:
  fillColor: "10006"
  legendLabel: Top

Diboson:
  add: Diboson
  subtract:
  fillColor: "10007"
  legendLabel: Diboson

Multijet:
  add: data
  subtract:
    - MG_Wjets_light
    - MG_Wjets_tau
    - MG_Zjets_light
    - MG_Zjets_tau
    - Top
    - Diboson
  fillColor: "10008"
  legendLabel: Multijet
  fitName: Multijet
