colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "10000"
  legendLabel: "W+jets"

Zjets:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  fillColor: "11000"
  legendLabel: "Z+jets"

Wjets_light_emu:
  add: MG_Wjets_light_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W#rightarrowl#nu + u"

Wjets_cjets_emu:
  add: MG_Wjets_cjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W#rightarrowl#nu + c"

Wjets_bjets_emu:
  add: MG_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu + b"

Wjets_tau:
  add: MG_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: "W#rightarrow#tau#nu"

Zjets_light_emu:
  add: MG_Zjets_light_emu
  subtract:
  fillColor: "11000"
  legendLabel: "W#rightarrowl#nu + u"

Zjets_cjets_emu:
  add: MG_Zjets_cjets_emu
  subtract:
  fillColor: "11001"
  legendLabel: "W#rightarrowl#nu + c"

Zjets_bjets_emu:
  add: MG_Zjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: "W#rightarrowl#nu + b"

Zjets_tau:
  add: MG_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: "Z#rightarrow#tau#tau"

Zjets_emu:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11000"
  legendLabel: "Z#rightarrowll"

Top:
  add: Top
  subtract:
  fillColor: "12001"
  legendLabel: Top

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson

Multijet:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top
    - Diboson
  fillColor: "14000"
  legendLabel: Multijet
