colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_emu_Matched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi)"
  shortName: Wjets_emu_Matched

Wjets_emu_Matched_truth_pt_bin1:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "14000"
  legendLabel: "W+#it{D} (bin 1)"
  shortName: Wjets_emu_Matched_truth_pt_bin1

Wjets_emu_Matched_truth_pt_bin2:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "14001"
  legendLabel: "W+#it{D} (bin 2)"
  shortName: Wjets_emu_Matched_truth_pt_bin2


Wjets_emu_Matched_truth_pt_bin3:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "14002"
  legendLabel: "W+#it{D} (bin 3)"
  shortName: Wjets_emu_Matched_truth_pt_bin3


Wjets_emu_Matched_truth_pt_bin4:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "14003"
  legendLabel: "W+#it{D} (bin 4)"
  shortName: Wjets_emu_Matched_truth_pt_bin4


Wjets_emu_Matched_truth_pt_bin5:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "14004"
  legendLabel: "W+#it{D} (bin 5)"
  shortName: Wjets_emu_Matched_truth_pt_bin5

Wjets_emu_MatchedShared:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "10002"
  legendLabel: "'' Shared"
  shortName: Wjets_emu_MatchedShared

Wjets_emu_411MisMatched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W+#it{D}(other)"
  shortName: Wjets_emu_411MisMatched

Wjets_emu_431MisMatched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W+#it{D}s"
  shortName: Wjets_emu_431MisMatched

Wjets_emu_BaryonMisMatched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "19000"
  legendLabel: "W+Baryon"
  shortName: Wjets_emu_BaryonMisMatched

Wjets_emu_Rest:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "11002"
  legendLabel: "W+jets"
  shortName: Wjets_emu_Rest

Wjets_emu_BkgShared:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "11002"
  legendLabel: "'' Shared"
  shortName: Wjets_emu_BkgShared

Wjets_emu_MisMatched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "11004"
  legendLabel: "W+c^{mis-match}"
  shortName: Wjets_emu_MisMatched

Wjets_emu_Bkg:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "11004"
  legendLabel: "W+jets"
  shortName: Wjets_emu_Bkg

Wjets_emu_413MisMatched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "11004"
  legendLabel: "W+#it{D}*"
  shortName: Wjets_emu_413MisMatched

Wjets_emu_421MisMatched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "11002"
  legendLabel: "W+#it{D}0"
  shortName: Wjets_emu_421MisMatched

Wjets_emu_MatchedFid:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D_{fid}}"
  shortName: Wjets_emu_MatchedFid

Wjets_emu_MatchedNoFid:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "13005"
  legendLabel: "W+#it{D_{nofid}}"
  shortName: Wjets_emu_MatchedNoFid

Wjets_emu_Charm:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  # fillColor: "16000"
  fillColor: "10001"
  legendLabel: "W+c^{match}"
  shortName: Wjets_emu_Charm

Wjets_emu_CharmGeom:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_light_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
  subtract:
  # fillColor: "16000"
  fillColor: "10007"
  legendLabel: "W+c^{match} Geom"
  shortName: Wjets_emu_Charm

Wjets_emu_HardMisMatched:
  add:
    - MG_Wjets_emu
    # - MG_Wjets_cjets_emu
    # - MG_Wjets_bjets_emu
    # - MG_Wjets_light_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W+Light"
  shortName: Wjets_emu_Charm

Wjets_emu_NoMatch:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10000"
  legendLabel: "No Match"
  shortName: Wjets_emu_NoMatch

Top_Matched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top w/ #it{D}"
  shortName: Top_Matched

Top_Charm:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: "Top w/ Charm"
  shortName: Top_Charm

Top_HardMisMatched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12000"
  legendLabel: "Top w/ Light"
  shortName: Top_Charm

Top_NoMatch:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top+#it{D}(PU)"

Top_Rest:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12000"
  legendLabel: "Top"
  shortName: Top_Rest

Zjets:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  fillColor: "11002"
  legendLabel: Z+jets

Zjets_emu:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: Z#rightarrowll
  shortName: Zjets_emu

Zjets_emu_Matched:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: "Z+#it{D}"
  shortName: Zjets_emu_Matched

Zjets_emu_Rest:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11000"
  legendLabel: Z#rightarrowll
  shortName: Zjets_emu_Rest

Zjets_tau:
  add: MG_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: Z#rightarrow#tau#tau
  shortName: Zjets_tau

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top
  shortName: Top

Top_HS:
  add:
    - Top_ttbar_HS
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}
  shortName: Top_HS

Top_ISR:
  add:
    - Top_ttbar_ISR
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}
  shortName: Top_ISR

Top_Shower:
  add:
    - Top_ttbar_Shower
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}
  shortName: Top_Shower

Top_ttbar:
  add: Top_ttbar
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}

Top_single_top:
  add: Top_single_top
  subtract:
  fillColor: "12002"
  legendLabel: "single-#it{t}"

Top_ttx:
  add: Top_ttx
  subtract:
  fillColor: "12003"
  legendLabel: t#bar{t}X

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson
  shortName: Diboson

Other:
  add:
    - Diboson
    - MG_Zjets_tau
    - MG_Wjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: Other

DibosonZjetsTau:
  add:
    - Diboson
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: DibosonZjetsTau

DibosonVjetsTau:
  add:
    - Diboson
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - MG_Wjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: DibosonVjetsTau

Multijet:
  add: data
  subtract:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  fillColor: "15002"
  legendLabel: Multijet
  shortName: Multijet

Multijet_MatrixMethod:
  add: data
  subtract:
  fillColor: "15002"
  legendLabel: Multijet
  shortName: Multijet_MatrixMethod

Multijet_MatrixMethod_Offset:
  add: data
  subtract:
  fillColor: "15002"
  legendLabel: Multijet
  shortName: Multijet_MatrixMethod_Offset

Multijet_MatrixMethod_FF:
  add:
    - data_FF
    - MC
  subtract:
  fillColor: "15002"
  legendLabel: "Multijet"
  shortName: Multijet_MatrixMethod

MockMC:
  add: data
  subtract:
  fillColor: "13001"
  legendLabel: "Ch. Symm."
  shortName: MockMC
  statError: True

MockMC_minus_MC:
  add: data
  subtract: MC
  fillColor: "13001"
  legendLabel: "Ch. Symm."
  shortName: MockMC
  statError: True

Offset:
  add: data
  subtract:
  offset: 100
  ghost: True
  fillColor: "13004"
  legendLabel: "Offset"
  shortName: Offset

SPG_Matched:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}(#it{K}#pi#pi) SPG"
  shortName: SPG_Matched

SPG_411MisMatched:
  add:
    - SPG_Dminus
    - SPG_Dplus
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}(other) SPG"
  shortName: SPG_411MisMatched

SPG_431MisMatched:
  add:
    - SPG_Ds
    - SPG_Dsminus
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}_{S} SPG"
  shortName: SPG_431MisMatched

SPG_421MisMatched:
  add:
    - SPG_D0_Dstar
    - SPG_D0_Dstar_bar
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}0/#it{D}* SPG"
  shortName: SPG_421MisMatched

SPG_BaryonMisMatched:
  add:
    - SPG_Baryon
    - SPG_Baryonbar
  subtract:
  lineColor: "21000"
  legendLabel: "Anti-Baryon SPG"
  shortName: SPG_BaryonMisMatched

SPG_CharmMisMatched:
  add:
    - SPG_Dminus_postProc
    - SPG_Dplus_postProc
    - SPG_Ds_postProc
    - SPG_D0_Dstar_postProc
    - SPG_Baryon_postProc
    - SPG_Dsminus_postProc
    - SPG_D0_Dstar_bar_postProc
    - SPG_Baryonbar_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "Charm SPG"
  shortName: SPG_CharmMisMatched

Wjets_Rest_Loose_OS-SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
    - MG_Wjets_tau
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+jets OS-SS"
  ignoreTruthMatching:
    - MG_Wjets_tau
  shortName: Wjets_Rest_Loose_OS-SS

Wjets_emu_MisMatched_Loose_OS-SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+c^{mis-match} OS-SS"
  shortName: Wjets_emu_MisMatched_Loose_OS-SS

MGFxFx_Wjets_Reshowered_Matched:
  add:
    - MGFxFx_Wjets_Reshowered
  subtract:
  lineColor: "11004"
  legendLabel: "Re Matched"
  shortName: MGFxFx_Wjets_Reshowered_Matched

MGFxFx_Wjets_Reshowered:
  add:
    - MGFxFx_Wjets_Reshowered
  subtract:
  lineColor: "21000"
  legendLabel: "Re w/o Truth"
  shortName: MGFxFx_Wjets_Reshowered

Wjets_emu_Rest_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+jets"
  shortName: Wjets_emu_Rest_PostProc

Wjets_emu_MisMatched_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+c^{mis-match}"
  shortName: Wjets_emu_MisMatched_PostProc

Wjets_emu_Bkg_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+jets"
  shortName: Wjets_emu_Bkg_PostProc

DibosonVjetsTau_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: Loose Other
  shortName: DibosonVjetsTau_Loose

MultiJet_PostProc:
  add:
    - inclusive_bkg
  subtract:
  lineColor: "21000"
  legendLabel: Loose MJ
  shortName: MultiJet_PostProc

SPG_Matched_truth_pt_bin1:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 1)"
  shortName: SPG_Matched_truth_pt_bin1

SPG_Matched_truth_pt_bin2:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 2)"
  shortName: SPG_Matched_truth_pt_bin2

SPG_Matched_truth_pt_bin3:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 3)"
  shortName: SPG_Matched_truth_pt_bin3

SPG_Matched_truth_pt_bin4:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 4)"
  shortName: SPG_Matched_truth_pt_bin4

SPG_Matched_truth_pt_bin5:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 5)"
  shortName: SPG_Matched_truth_pt_bin5

Sherpa_Wjets_emu_Rest:
  add:
    - inclusive_sherpa_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa W+jets"
  shortName: Sherpa_Wjets_emu_Rest

Sherpa_Wjets_emu_Rest_PostProc:
  add:
    - inclusive_sherpa_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa W+jets"
  shortName: Sherpa_Wjets_emu_Rest_PostProc

Sherpa_Wjets_emu_Bkg:
  add:
    - inclusive_sherpa_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa W+jets"
  shortName: Sherpa_Wjets_emu_Bkg

Sherpa_Wjets_emu_Bkg_PostProc:
  add:
    - inclusive_sherpa_bkg
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa W+jets"
  shortName: Sherpa_Wjets_emu_Bkg_PostProc
