colorScheme: gemstone_hues

Data:
  add: data
  subtract:

DataMinusBackground:
  add: data
  subtract:
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson

Wjets:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "10002"
  legendLabel: "W+jets"

Wjets_emu:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: W#rightarrowl#nu

Zjets:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  fillColor: "11000"
  legendLabel: "Z+jets"

Wjets_light_emu:
  add: MG_Wjets_light_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W#rightarrowl#nu + u"

Wjets_bjets_emu:
  add: MG_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W#rightarrowl#nu + b"

Wjets_cjets_emu:
  add: MG_Wjets_cjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu + c"

Wjets_tau:
  add: MG_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: "W#rightarrow#tau#nu"

Zjets_light_emu:
  add: MG_Zjets_light_emu
  subtract:
  fillColor: "11000"
  legendLabel: "Z#rightarrowll + u"

Zjets_bjets_emu:
  add: MG_Zjets_bjets_emu
  subtract:
  fillColor: "11001"
  legendLabel: "Z#rightarrowll + b"

Zjets_cjets_emu:
  add: MG_Zjets_cjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: "Z#rightarrowll + c"

Zjets_tau:
  add: MG_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: "Z#rightarrow#tau#tau"

Zjets_emu:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: "Z#rightarrowll"

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top

Top_ttbar:
  add: Top_ttbar
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}

Top_single_top:
  add: Top_single_top
  subtract:
  fillColor: "12002"
  legendLabel: "single-#it{t}"

Top_ttx:
  add: Top_ttx
  subtract:
  fillColor: "12003"
  legendLabel: t#bar{t}X

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson

Other:
  add:
    - Diboson
    - MG_Zjets_tau
    - MG_Wjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other

DibosonVjetsTau:
  add:
    - Diboson
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - MG_Wjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: DibosonVjetsTau

Multijet:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  fillColor: "14003"
  legendLabel: Multijet
  shortName: Multijet

Multijet_MatrixMethod:
  add: data
  subtract:
  fillColor: "14003"
  legendLabel: Multijet
  shortName: Multijet_MatrixMethod

Multijet_Data:
  add: data
  subtract:
  lineColor: "14003"
  legendLabel: AntiTight Data
  shortName: Multijet_Data

Multijet_Data_Tight:
  add: data
  subtract:
  lineColor: "10002"
  legendLabel: Tight Data
  shortName: Multijet_Data_Tight

Multijet_Data_AntiTight:
  add: data
  subtract:
  lineColor: "14003"
  legendLabel: AntiTight Data
  shortName: Multijet_Data_AntiTight

Multijet_PromptMC:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  subtract:
  lineColor: "10002"
  legendLabel: AntiTight MC
  shortName: Multijet_PromptMC

Zero_Fake:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  subtract:
  fillColor: "10002"
  legendLabel: 0 Fakes

One_Fake:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  subtract:
  fillColor: "11002"
  legendLabel: 1 Fake

Two_Fake:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  subtract:
  fillColor: "12004"
  legendLabel: 2 Fakes

Three_Fake:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  subtract:
  fillColor: "13000"
  legendLabel: 3 Fakes

MockMC_minus_MC:
  add: data
  subtract: MC
  fillColor: "13001"
  legendLabel: "Ch. Symm."
  shortName: MockMC
  statError: True

Wjets_light_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "10000"
  legendLabel: "W#rightarrowl#nu + u"

Wjets_bjets_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "10001"
  legendLabel: "W#rightarrowl#nu + b"

Wjets_cjets_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu + c"

Wjets_tau_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: "W#rightarrowl#nu + #tau"

Wjets_cjets_dplus_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "15001"
  legendLabel: "W#rightarrowl#nu + D+"

Wjets_cjets_dzero_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "15002"
  legendLabel: "W#rightarrowl#nu + D0"

Wjets_cjets_dsubs_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "15003"
  legendLabel: "W#rightarrowl#nu + Ds"

Wjets_cjets_baryon_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "15004"
  legendLabel: "W#rightarrowl#nu + #Lambda"

Wjets_cjets_other_ftag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  fillColor: "15005"
  legendLabel: "W#rightarrowl#nu + c"
