colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_emu_Top_Matched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10002"
  legendLabel: "Sig. W+#it{D}"
  shortName: Wjets_emu_Top_Matched

Wjets_emu_Top_Rest:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10000"
  legendLabel: "Bkg. W+#it{D}"
  shortName: Wjets_emu_Top_Rest

Wjets_emu_Top_Charm:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10001"
  legendLabel: "Top/W w/ Charm."
  shortName: Wjets_emu_Top_Charm

Wjets_emu_Top_HardMisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10001"
  legendLabel: "Top/W w/ Light."
  shortName: Wjets_emu_Top_Charm

Wjets_emu_Top_NoMatch:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10004"
  legendLabel: "PU #it{D}"
  shortName: Wjets_emu_Top_NoMatch

Wjets_emu_Matched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W+#it{D}"
  shortName: Wjets_emu_Matched

Wjets_emu_Charm:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W+Charm"
  shortName: Wjets_emu_Charm

Wjets_emu_HardMisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W+Light"
  shortName: Wjets_emu_Charm

Wjets_emu_NoMatch:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10004"
  legendLabel: "No Match"
  shortName: Wjets_emu_NoMatch

Wjets_emu_Rest:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W+jets"
  shortName: Wjets_emu_Rest

Top_Matched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top w/ #it{D}"
  shortName: Top_Matched

Top_Charm:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: "Top w/ Charm"
  shortName: Top_Charm

Top_HardMisMatched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12000"
  legendLabel: "Top w/ Light"
  shortName: Top_Charm

Top_NoMatch:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top+#it{D}(PU)"

Top_Rest:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12000"
  legendLabel: "Top"
  shortName: Top_Rest

Wjets_emu:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu"

Wjets_tau:
  add: MG_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: W#rightarrow#tau#nu

Zjets:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  fillColor: "11002"
  legendLabel: Z+jets

Zjets_emu:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: Z#rightarrowll
  shortName: Zjets_emu

Zjets_tau:
  add: MG_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: Z#rightarrow#tau#tau
  shortName: Zjets_tau

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top
  shortName: Top

Top_ttbar:
  add: Top_ttbar
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}

Top_single_top:
  add: Top_single_top
  subtract:
  fillColor: "12002"
  legendLabel: "single-#it{t}"

Top_ttx:
  add: Top_ttx
  subtract:
  fillColor: "12003"
  legendLabel: t#bar{t}X

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson
  shortName: Diboson

Other:
  add:
    - Diboson
    - MG_Zjets_tau
    - MG_Wjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: Other

Multijet:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  fillColor: "14002"
  legendLabel: Multijet
  shortName: Multijet

Multijet_MatrixMethod:
  add: data
  subtract:
  fillColor: "14003"
  legendLabel: Multijet
  shortName: Multijet_MatrixMethod

MockMC:
  add: data
  subtract:
  fillColor: "13001"
  legendLabel: MockMC
  shortName: MockMC
  statError: True
