colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_emu_Top_Matched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10002"
  legendLabel: "Sig. W+#it{D}"
  shortName: Wjets_emu_Top_Matched

Wjets_emu_Top_Rest:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10000"
  legendLabel: "Bkg. W+#it{D}"
  shortName: Wjets_emu_Top_Rest

Wjets_emu_Top_Charm:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10001"
  legendLabel: "Top/W w/ Charm."
  shortName: Wjets_emu_Top_Charm

Wjets_emu_Top_HardMisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10001"
  legendLabel: "Top/W w/ Light."
  shortName: Wjets_emu_Top_Charm

Wjets_emu_Top_NoMatch:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10004"
  legendLabel: "PU #it{D}"
  shortName: Wjets_emu_Top_NoMatch

Wjets_emu_Matched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D}(K#pi#pi)"
  shortName: Wjets_emu_Matched

Wjets_emu_411MisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W+#it{D}(other)"
  shortName: Wjets_emu_411MisMatched

Wjets_emu_431MisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W+#it{D}s"
  shortName: Wjets_emu_431MisMatched

Wjets_emu_BaryonMisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "19000"
  legendLabel: "W+Baryon"
  shortName: Wjets_emu_BaryonMisMatched

Wjets_emu_Rest:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "21000"
  legendLabel: "W+jets"
  shortName: Wjets_emu_Rest

Wjets_emu_413MisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "11004"
  legendLabel: "W+#it{D}*"
  shortName: Wjets_emu_413MisMatched

Wjets_emu_421MisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: "W+#it{D}0"
  shortName: Wjets_emu_421MisMatched

Wjets_emu_MatchedFid:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D_{fid}}"
  shortName: Wjets_emu_MatchedFid

Wjets_emu_MatchedNoFid:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "13005"
  legendLabel: "W+#it{D_{nofid}}"
  shortName: Wjets_emu_MatchedNoFid

Wjets_emu_MatchedNoFid:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W+#it{D_{nofid}}"
  shortName: Wjets_emu_MatchedNoFid

Wjets_emu_Charm:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W+Charm"
  shortName: Wjets_emu_Charm

Wjets_emu_HardMisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W+Light"
  shortName: Wjets_emu_Charm

Wjets_emu_NoMatch:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10000"
  legendLabel: "No Match"
  shortName: Wjets_emu_NoMatch

Wjets_bujets_emu_Rest_fit:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W+jets + u/b"
  shortName: Wjets_bujets_emu_Rest
  fit: "pol0"

Wjets_bujets_emu_Rest:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W+jets + u/b"
  shortName: Wjets_bujets_emu_Rest

Wjets_light_emu_Rest:
  add:
    - MG_Wjets_light_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W+jets + u"
  shortName: Wjets_light_emu_Rest

Wjets_cjets_emu_Rest:
  add:
    - MG_Wjets_cjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W+jets + c"
  shortName: Wjets_cjets_emu_Rest

Wjets_bjets_emu_Rest:
  add:
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10003"
  legendLabel: "W+jets + b"
  shortName: Wjets_bjets_emu_Rest

Top_Matched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top w/ #it{D}"
  shortName: Top_Matched

Top_Charm:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: "Top w/ Charm"
  shortName: Top_Charm

Top_HardMisMatched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12000"
  legendLabel: "Top w/ Light"
  shortName: Top_Charm

Top_NoMatch:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top+#it{D}(PU)"

Top_Rest:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12000"
  legendLabel: "Top"
  shortName: Top_Rest

Wjets_emu:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu"

Wjets_emu_Sherpa2210:
  add:
    - Sh_2210_Wjets_light_emu
    - Sh_2210_Wjets_cjets_emu
    - Sh_2210_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu"
  shortName: Wjets_emu_Sherpa2210

MG_FxFx_Wjets_emu:
  add:
    - MG_FxFx_Wjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu"
  shortName: MG_FxFx_Wjets_emu

Wjets_tau:
  add: MG_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: W#rightarrow#tau#nu

Zjets:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  fillColor: "11002"
  legendLabel: Z+jets

Zjets_emu:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: Z#rightarrowll
  shortName: Zjets_emu

Zjets_emu_Matched:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: "Z+#it{D}"
  shortName: Zjets_emu_Matched

Zjets_emu_Rest:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11000"
  legendLabel: Z#rightarrowll
  shortName: Zjets_emu_Rest

Zjets_tau:
  add: MG_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: Z#rightarrow#tau#tau
  shortName: Zjets_tau

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top
  shortName: Top

Top_HS:
  add:
    - Top_ttbar_HS
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}
  shortName: Top_HS

Top_ISR:
  add:
    - Top_ttbar_ISR
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}
  shortName: Top_ISR

Top_Shower:
  add:
    - Top_ttbar_Shower
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}
  shortName: Top_Shower

Top_ttbar:
  add: Top_ttbar
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}

Top_single_top:
  add: Top_single_top
  subtract:
  fillColor: "12002"
  legendLabel: "single-#it{t}"

Top_ttx:
  add: Top_ttx
  subtract:
  fillColor: "12003"
  legendLabel: t#bar{t}X

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson
  shortName: Diboson

Other:
  add:
    - Diboson
    - MG_Zjets_tau
    - MG_Wjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: Other

DibosonZjetsTau:
  add:
    - Diboson
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - MG_Wjets_tau
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: DibosonZjetsTau

Multijet:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  fillColor: "14002"
  legendLabel: Multijet
  shortName: Multijet

Multijet_MatrixMethod:
  add: data
  subtract:
  fillColor: "14003"
  legendLabel: Multijet
  shortName: Multijet_MatrixMethod
  makeGhostSample: True

MockMC:
  add: data
  subtract:
  fillColor: "13001"
  legendLabel: "Ch. Symm."
  shortName: MockMC
  statError: True
  
Wjets_emu_Matched_Charm:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
#    - Top_ttbar
#    - Top_single_top
#    - Top_ttx
  subtract:
  fillColor: "10002"
  legendLabel: "Matched #it{D}"
  shortName: Wjets_emu_Matched

SPG_Matched:
  add:
    - "D_CharmAnalysis.999914.DMinus"
  subtract:
  fillColor: "11000"
  legendLabel: "SPG"
  shortName: SPG_Matched
