colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_light:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: W#rightarrowl#nu
  shortName: Wjets_light

Wjets_emu_Matched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: 'W+#it{D}'
  shortName: Wjets_light_Matched

Wjets_emu_MisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: 'W+#it{D} Mis'

Wjets_emu_Rest:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: W+jets
  shortName: Wjets_light_Rest

Wjets_tau:
  add: MG_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: W#rightarrow#tau#nu

Zjets:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
  subtract:
  fillColor: "11000"
  legendLabel: Z+jets

Zjets_light:
  add:
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
  subtract:
  fillColor: "11000"
  legendLabel: Z#rightarrowll

Zjets_tau:
  add: MG_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: Z#rightarrow#tau#tau

Top:
  add: Top
  subtract:
  fillColor: "12001"
  legendLabel: Top

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson

Multijet:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top
    - Diboson
  fillColor: "14000"
  legendLabel: Multijet
  shortName: Multijet
