colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_emu_Matched:
  add:
    - Ph_Wjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: 'W+#it{D}'
  shortName: Wjets_light_Matched

Wjets_emu_MisMatched:
  add:
    - Ph_Wjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: 'W+#it{D} Mis'

Wjets_emu_Rest:
  add:
    - Ph_Wjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: W+jets
  shortName: Wjets_light_Rest

Wjets_tau:
  add: Ph_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: W#rightarrow#tau#nu

Zjets:
  add:
    - Ph_Zjets_emu
  subtract:
  fillColor: "11000"
  legendLabel: Z+jets

Zjets_light:
  add:
    - Ph_Zjets_emu
  subtract:
  fillColor: "11000"
  legendLabel: Z#rightarrowll

Zjets_tau:
  add: Ph_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: Z#rightarrow#tau#tau

Top:
  add: Top
  subtract:
  fillColor: "12001"
  legendLabel: Top

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson

Multijet:
  add: data
  subtract:
    - Ph_Wjets_emu
    - Ph_Wjets_tau
    - Ph_Zjets_emu
    - Ph_Zjets_tau
    - Top
    - Diboson
  fillColor: "14000"
  legendLabel: Multijet
  shortName: Multijet
