colorScheme: cheer_up_emo_kid_extended

Wjets_light_Matched:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10002"
  legendLabel: 'W+#it{D}^{#pm}'
  fitName: Wjets_light_Matched

Wjets_light_DplusMisMatched:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10000"
  legendLabel: 'W+#it{D}^{#pm} Mis'
  fitName: Wjets_light_Dplus_MisMatched

Wjets_light_DzeroMisMatched:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10001"
  legendLabel: 'W+#it{D}^{0} Mis'
  fitName: Wjets_light_Dzero_MisMatched

Wjets_light_DsMisMatched:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10003"
  legendLabel: 'W+#it{D}_{s} Mis'
  fitName: Wjets_light_Ds_MisMatched

Wjets_light_BaryonMisMatched:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10004"
  legendLabel: 'W+(#Lambda_{c}, #Omega_{c}, #Xi_{c}) Mis'
  fitName: Wjets_light_Baryon_MisMatched

Wjets_light_HardScatter:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10005"
  legendLabel: '>0 Match Track Mis'
  fitName: Wjets_light_HardScatter

Wjets_light_NoMatch:
  add: Ph_Wjets_light
  subtract:
  fillColor: "10006"
  fitName: Wjets_light_NoMatch