colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_emu:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: W#rightarrowl#nu

Wjets_tau:
  add: Ph_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: W#rightarrow#tau#nu

Zjets_emu:
  add: Ph_Zjets_emu
  subtract:
  fillColor: "11000"
  legendLabel: Z#rightarrowll

Zjets_tau:
  add: Ph_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: Z#rightarrow#tau#tau

Wjets:
  add:
    - Ph_Wjets_emu
    - Ph_Wjets_tau
  subtract:
  fillColor: "10000"
  legendLabel: W+jets

Zjets:
  add:
    - Ph_Zjets_emu
    - Ph_Zjets_tau
  subtract:
  fillColor: "11000"
  legendLabel: Z+jets

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top

Top_ttbar:
  add: Top_ttbar
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}

Top_single_top:
  add: Top_single_top
  subtract:
  fillColor: "12002"
  legendLabel: "single-#it{t}"

Top_ttx:
  add: Top_ttx
  subtract:
  fillColor: "12003"
  legendLabel: t#bar{t}X

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson

Multijet:
  add: data
  subtract:
    - Ph_Wjets_emu
    - Ph_Wjets_tau
    - Ph_Zjets_emu
    - Ph_Zjets_tau
    - Top
    - Diboson
  fillColor: "14000"
  legendLabel: Multijet

DataMinusBackground:
  add: data
  subtract:
    - Ph_Wjets_tau
    - Ph_Zjets_emu
    - Ph_Zjets_tau
    - Top
    - Diboson
