colorScheme: cheer_up_emo_kid_extended

Wjets_emu_Matched:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: 'W+#it{D}*'
  shortName: Wjets_emu_Matched

Wjets_emu_NoMatch:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10006"
  legendLabel: 'No Match'
  shortName: Wjets_emu_NoMatch

Wjets_emu_DsMisMatched:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10003"
  legendLabel: 'W+#it{D}_{s}'
  shortName: Wjets_emu_Ds_MisMatched

Wjets_emu_DzeroMisMatched:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: 'W+#it{D}^{0}'
  shortName: Wjets_emu_Dzero_MisMatched

Wjets_emu_DplusMisMatched:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10000"
  legendLabel: 'W+#it{D}^{+}'
  shortName: Wjets_emu_Dplus_MisMatched

Wjets_emu_BaryonMisMatched:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10004"
  legendLabel: 'W+(#Lambda_{c}, #Omega_{c}, #Xi_{c})'
  shortName: Wjets_emu_Baryon_MisMatched

Wjets_emu_HardScatter:
  add: Ph_Wjets_emu
  subtract:
  fillColor: "10005"
  legendLabel: '>0 Hard Track'
  shortName: Wjets_emu_HardScatter
