colorScheme: gemstone_hues

MG_Wjets_emu:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: 'MG W#rightarrowl#nu'

Sh_Wjets_emu:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
  subtract:
  lineColor: "10002"
  legendLabel: 'Sherpa W#rightarrowl#nu'

Ph_Wjets_emu:
  add: Ph_Wjets_emu
  subtract:
  lineColor: "10000"
  legendLabel: 'Powheg W#rightarrowl#nu'

Top_ttbar:
  add: Top_ttbar
  subtract:
  lineColor: "12001"
  legendLabel: t#bar{t}

MG_Multijet:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "14004"
  legendLabel: 'Multijet (MG)'
  shortName: MG_Multijet

Sh_Multijet:
  add: data
  subtract:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_tau
    - Sh_Wjets_highpt_emu
    - Sh_Zjets_light_emu
    - Sh_Zjets_cjets_emu
    - Sh_Zjets_bjets_emu
    - Sh_Zjets_tau
    - Sh_Zjets_highpt_emu
    - Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "14002"
  legendLabel: 'Multijet (Sh)'
  shortName: Sh_Multijet

MG_Multijet_Up:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "15002"
  legendLabel: 'Multijet (MG, +10%)'
  shortName: MG_Multijet
  scaleMC: 1.1

MG_Multijet_Dn:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "15004"
  legendLabel: 'Multijet (MG, -10%)'
  shortName: MG_Multijet
  scaleMC: 0.9

