colorScheme: gemstone_hues

MG_Wjets_emu:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: 'MG W#rightarrowl#nu'

Sh_2211_Wjets_emu:
  add:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
#    - Sh_Wjets_highpt_emu
  subtract:
  lineColor: "10002"
  legendLabel: 'Sherpa W#rightarrowl#nu'

Ph_Wjets_emu:
  add: Ph_Wjets_emu
  subtract:
  lineColor: "10000"
  legendLabel: 'Powheg W#rightarrowl#nu'

Top_ttbar:
  add: Top_ttbar
  subtract:
  lineColor: "12001"
  legendLabel: t#bar{t}

MG_Multijet:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
#    - Sh_2211_Zjets
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "14004"
  legendLabel: 'Multijet (MG)'
  shortName: MG_Multijet

Sh_2211_Multijet:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
#    - Sh_2211_Zjets
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "14002"
  legendLabel: 'Multijet (Sh)'
  shortName: Sh_2211_Multijet

MG_Multijet_Up:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - Sh_2211_Zjets
#    - MG_Zjets_light_emu
#    - MG_Zjets_cjets_emu
#    - MG_Zjets_bjets_emu
#    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "15002"
  legendLabel: 'Multijet (MG, +10%)'
  shortName: MG_Multijet
  scaleMC: 1.1

MG_Multijet_Dn:
  add: data
  subtract:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
    - MG_Zjets_light_emu
    - MG_Zjets_cjets_emu
    - MG_Zjets_bjets_emu
    - MG_Zjets_tau
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "15004"
  legendLabel: 'Multijet (MG, -10%)'
  shortName: MG_Multijet
  scaleMC: 0.9

Sh_2211_Multijet_Up:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
#    - Sh_2211_Zjets
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "15002"
  legendLabel: 'Multijet (Sh, +10%)'
  shortName: Sh_Multijet_Var
  scaleMC: 1.1

Sh_2211_Multijet_Dn:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "15004"
  legendLabel: 'Multijet (Sh, -10%)'
  shortName: Sh_Multijet_Var
  scaleMC: 0.9

#samples conf for special fake rate measurement
MC_Comb:
  add:
    - MG_all
  subtract:
  lineColor: "11004"
  legendLabel: 'W + D All'

MC_Comb_sys_var:
  add:
    - MG_all
  subtract:
  lineColor: "11006"
  legendLabel: 'W + D MG var'

MG_Wjets_emu_0tag_Dplus:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: 'MG W + D^{+}, 0tag'

MG_Wjets_emu_0tag_Dstar:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10002"
  legendLabel: 'MG W + D*, 0tag'

Sh_2211_Wjets_emu_0tag_Dplus:
  add:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: 'Sh2211 W + D^{+}, 0tag'

Sh_2211_Wjets_emu_0tag_Dstar:
  add:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
  subtract:
  lineColor: "14002"
  legendLabel: 'Sh2211 W + D*, 0tag'

Top_ttbar_0tag_Dplus:
  add: Top_ttbar
  subtract:
  lineColor: "12001"
  legendLabel: 't#bar{t} + D^{+}, 0tag'

Top_ttbar_0tag_Dstar:
  add: Top_ttbar
  subtract:
  lineColor: "12003"
  legendLabel: 't#bar{t} + D*, 0tag'

MG_Wjets_emu_1tag_Dplus:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10005"
  legendLabel: 'MG W + D^{+}, 1tag'

MG_Wjets_emu_1tag_Dstar:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10003"
  legendLabel: 'MG W + D*, 1tag'

Sh_2211_Wjets_emu_1tag_Dplus:
  add:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: 'Sh2211 W + D^{+}, 1tag'

Sh_2211_Wjets_emu_1tag_Dstar:
  add:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
  subtract:
  lineColor: "14002"
  legendLabel: 'Sh2211 W + D*, 1tag'

Top_ttbar_1tag_Dplus:
  add: Top_ttbar
  subtract:
  lineColor: "12002"
  legendLabel: 't#bar{t} + D^{+}, 1tag'

Top_ttbar_1tag_Dstar:
  add: Top_ttbar
  subtract:
  lineColor: "12004"
  legendLabel: 't#bar{t} + D*, 1tag'

MG_Wjets_emu_0tag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: 'MG W + D, 0tag'

MG_Wjets_emu_1tag:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10002"
  legendLabel: 'MG W + D, 1tag'

Sh_2211_Wjets_emu_0tag:
  add:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: 'Sh 2211 W + D, 0tag'

Sh_2211_Wjets_emu_1tag:
  add:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
  subtract:
  lineColor: "14002"
  legendLabel: 'Sh 2211 W + D, 1tag'

Top_ttbar_0tag:
  add: Top_ttbar
  subtract:
  lineColor: "12001"
  legendLabel: 't#bar{t} + D, 0tag'

Top_ttbar_1tag:
  add: Top_ttbar
  subtract:
  lineColor: "12003"
  legendLabel: 't#bar{t} + D, 1tag'

#Scale variations to be made into systematics 
Sh_2211_Multijet_GEN_MUR2_MUF2_PDF303200_PSMUR2_PSMUF2:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "10004"
  legendLabel: 'Sherpa W#rightarrowl#nu MUR2_MUF2'
  shortName: Sh_Multijet_Var

#Scale variations to be made into systematics 
Sh_2211_Multijet_GEN_MUR05_MUF1_PDF303200_PSMUR05_PSMUF1:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "10006"
  legendLabel: 'Sherpa W#rightarrowl#nu MUR05_MUF1'
  shortName: Sh_Multijet_Var

#Scale variations to be made into systematics 
Sh_2211_Multijet_GEN_MUR2_MUF1_PDF303200_PSMUR2_PSMUF1:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "11002"
  legendLabel: 'Sherpa W#rightarrowl#nu MUR2_MUF1'
  shortName: Sh_Multijet_Var

#Scale variations to be made into systematics 
Sh_2211_Multijet_GEN_MUR1_MUF2_PDF303200_PSMUR1_PSMUF2:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "11004"
  legendLabel: 'Sherpa W#rightarrowl#nu MUR1_MUF2'
  shortName: Sh_Multijet_Var

#Scale variations to be made into systematics 
Sh_2211_Multijet_GEN_MUR05_MUF05_PDF303200_PSMUR05_PSMUF05:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "10006"
  legendLabel: 'Sherpa W#rightarrowl#nu MUR05_MUF05'
  shortName: Sh_Multijet_Var

#Scale variations to be made into systematics 
Sh_2211_Multijet_GEN_MUR1_MUF05_PDF303200_PSMUR1_PSMUF05:
  add: data
  subtract:
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_tau
#    - Sh_Wjets_highpt_emu
    - Sh_2211_Zjets_light_emu
    - Sh_2211_Zjets_cjets_emu
    - Sh_2211_Zjets_bjets_emu
    - Sh_2211_Zjets_tau
    #- Sh_Zjets_highpt_emu
    #- Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  lineColor: "12002"
  legendLabel: 'Sh MUR1_MUF05'
  shortName: Sh_Multijet_Var