colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_Matched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "10004"
  legendLabel: "W+D (Matched)"

Wjets_HardMisMatched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "11001"
  legendLabel: "W+D (HardMis)"

Wjets_MxMisMatched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "14004"
  legendLabel: "W+D (MxMis)"

Wjets_MxMatched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "15001"
  legendLabel: "W+D (Mx)"

Wjets_413MisMatched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "10004"
  legendLabel: "W+D (413Mis)"

Wjets_421MisMatched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "11001"
  legendLabel: "W+D (421Mis)"

Wjets_431MisMatched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "14004"
  legendLabel: "W+D (431Mis)"

Wjets_BaryonMisMatched:
  add:
    - Sh_Wjets
  subtract:
  lineColor: "15001"
  legendLabel: "W+D (BaryonMis)"

Wjets_rw_Matched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "10005"
  legendLabel: "W+D_{rw} (Matched)"

Wjets_rw_HardMisMatched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "11002"
  legendLabel: "W+D_{rw} (HardMis)"

Wjets_rw_MxMisMatched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "14005"
  legendLabel: "W+D_{rw} (MxMis)"

Wjets_rw_MxMatched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "15002"
  legendLabel: "W+D_{rw} (Mx)"

Wjets_rw_413MisMatched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "10005"
  legendLabel: "W+D_{rw} (413Mis)"

Wjets_rw_421MisMatched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "11002"
  legendLabel: "W+D_{rw} (421Mis)"

Wjets_rw_431MisMatched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "14005"
  legendLabel: "W+D_{rw} (431Mis)"

Wjets_rw_BaryonMisMatched:
  add:
    - Sh_Wjets_rw
  subtract:
  lineColor: "15002"
  legendLabel: "W+D_{rw} (BaryonMis)"

Zjets_Matched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "10004"
  legendLabel: "Z+D (Matched)"

Zjets_HardMisMatched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "11001"
  legendLabel: "Z+D (HardMis)"

Zjets_MxMisMatched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "14004"
  legendLabel: "Z+D (MxMis)"

Zjets_MxMatched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "15001"
  legendLabel: "Z+D (Mx)"

Zjets_413MisMatched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "10004"
  legendLabel: "Z+D (413Mis)"

Zjets_421MisMatched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "11001"
  legendLabel: "Z+D (421Mis)"

Zjets_431MisMatched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "14004"
  legendLabel: "Z+D (431Mis)"

Zjets_BaryonMisMatched:
  add:
    - Sh_Zjets
  subtract:
  lineColor: "15001"
  legendLabel: "Z+D (BaryonMis)"

Zjets_rw_Matched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "10005"
  legendLabel: "Z+D_{rw} (Matched)"

Zjets_rw_HardMisMatched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "11002"
  legendLabel: "Z+D_{rw} (HardMis)"

Zjets_rw_MxMisMatched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "14005"
  legendLabel: "Z+D_{rw} (MxMis)"

Zjets_rw_MxMatched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "15002"
  legendLabel: "Z+D_{rw} (Mx)"

Zjets_rw_413MisMatched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "10005"
  legendLabel: "Z+D_{rw} (413Mis)"

Zjets_rw_421MisMatched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "11002"
  legendLabel: "Z+D_{rw} (421Mis)"

Zjets_rw_431MisMatched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "14005"
  legendLabel: "Z+D_{rw} (431Mis)"

Zjets_rw_BaryonMisMatched:
  add:
    - Sh_Zjets_rw
  subtract:
  lineColor: "15002"
  legendLabel: "W+D_{rw} (BaryonMis)"
