colorScheme: gemstone_hues

Data:
  add: data
  subtract: null

Sherpa2211_Wjets_Matched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi)"
  shortName: Sherpa2211_Wjets_Matched

Sherpa2211_Wjets_MisMatched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  fillColor: "11004"
  legendLabel: "W+c^{mis-match}"
  shortName: Sherpa2211_Wjets_MisMatched

Sherpa2211_Wjets_Rest:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  fillColor: "11002"
  legendLabel: "W+jets"
  shortName: Sherpa2211_Wjets_Rest

Sherpa2211_Wjets_Charm:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  fillColor: "10001"
  legendLabel: "W+c^{match}"
  shortName: Sherpa2211_Wjets_Charm

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top
  shortName: Top

DibosonZjets:
  add:
    - Diboson
    - Sherpa2211_Zjets
  subtract:
  fillColor: "15000"
  legendLabel: Other
  shortName: DibosonZjets

Multijet_MatrixMethod:
  add: data
  subtract:
  fillColor: "15002"
  legendLabel: Multijet
  shortName: Multijet_MatrixMethod
