colorScheme: cheer_up_emo_kid_extended

Data:
  add: data
  subtract:

DataMinusBackground:
  add: data
  subtract:
    - Sh_Wjets_tau
    - Sh_Zjets
    - Top
    - Diboson

Wjets:
  add:
    - Sh_Wjets_light
    - Sh_Wjets_tau
  subtract:
  fillColor: "10000"
  legendLabel: W+jets

Wjets_emu:
  add: Sh_Wjets_light
  subtract:
  fillColor: "10000"
  lineColor: "10001"
  legendLabel: W#rightarrowl#nu

Wjets_light_emu:
  add: Sh_Wjets_light_emu
  subtract:
  fillColor: "10000"
  legendLabel: 'W#rightarrowl#nu + u'

Wjets_cjets_emu:
  add: Sh_Wjets_cjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: 'W#rightarrowl#nu + c'

Wjets_bjets_emu:
  add: Sh_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: 'W#rightarrowl#nu + b'

Wjets_tau:
  add: Sh_Wjets_highpt_emu
  add: Sh_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: 'W#rightarrow#tau#nu'

Zjets:
  add:
    - Sh_Zjets_light
    - Sh_Zjets_tau
  subtract:
  fillColor: "10004"
  legendLabel: Z+jets

Zjets_emu:
  add: Sh_Zjets_light
  subtract:
  fillColor: "10004"
  legendLabel: Z#rightarrowll

Zjets_tau:
  add: Sh_Zjets_tau
  subtract:
  fillColor: "10005"
  legendLabel: Z#rightarrow#tau#tau

Top:
  add: Top
  subtract:
  fillColor: "10006"
  legendLabel: Top

Diboson:
  add: Diboson
  subtract:
  fillColor: "10007"
  legendLabel: Diboson

Multijet:
  add: data
  subtract:
    - Sh_Wjets_light
    - Sh_Wjets_tau
    - Sh_Zjets
    - Top
    - Diboson
  fillColor: "10006"
  legendLabel: Multijet
