colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_tau
    - Sh_Wjets_highpt_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W+jets"

Wjets_emu:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
  subtract:
  fillColor: "10000"
  legendLabel: W#rightarrowl#nu

Zjets:
  add:
    - Sh_Zjets_light_emu
    - Sh_Zjets_cjets_emu
    - Sh_Zjets_bjets_emu
    - Sh_Zjets_tau
    - Sh_Zjets_highpt_emu
    - Sh_Zjets_lowmass_emu
  subtract:
  fillColor: "11000"
  legendLabel: "Z+jets"

Zjets_emu:
  add:
    - Sh_Zjets_light_emu
    - Sh_Zjets_cjets_emu
    - Sh_Zjets_bjets_emu
    - Sh_Zjets_highpt_emu
    - Sh_Zjets_lowmass_emu
  subtract:
  fillColor: "11000"
  legendLabel: "Z#rightarrowll"

Wjets_light_emu:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_highpt_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W#rightarrowl#nu + u"

Wjets_bjets_emu:
  add: Sh_Wjets_bjets_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W#rightarrowl#nu + b"

Wjets_cjets_emu:
  add: Sh_Wjets_cjets_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W#rightarrowl#nu + c"

Wjets_tau:
  add: Sh_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: "W#rightarrow#tau#nu"

Zjets_light_emu:
  add: Sh_Zjets_light_emu
  subtract:
  fillColor: "11000"
  legendLabel: "Z#rightarrowll + u"

Zjets_bjets_emu:
  add: Sh_Zjets_bjets_emu
  subtract:
  fillColor: "11001"
  legendLabel: "Z#rightarrowll + b"

Zjets_cjets_emu:
  add: Sh_Zjets_cjets_emu
  subtract:
  fillColor: "11002"
  legendLabel: "Z#rightarrowll + c"

Zjets_tau:
  add: Sh_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: "Z#rightarrow#tau#tau"

Zjets_highpt_emu:
  add: Sh_Zjets_highpt_emu
  subtract:
  fillColor: "11004"
  legendLabel: "high p_{T} Z"

Zjets_lowmass_emu:
  add: Sh_Zjets_lowmass_emu
  subtract:
  fillColor: "11005"
  legendLabel: "low mZ"

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top

Top_ttbar:
  add: Top_ttbar
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}

Top_single_top:
  add: Top_single_top
  subtract:
  fillColor: "12002"
  legendLabel: "single-#it{t}"

Top_ttx:
  add: Top_ttx
  subtract:
  fillColor: "12003"
  legendLabel: t#bar{t}X

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson

Multijet:
  add: data
  subtract:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_tau
    - Sh_Wjets_highpt_emu
    - Sh_Zjets_light_emu
    - Sh_Zjets_cjets_emu
    - Sh_Zjets_bjets_emu
    - Sh_Zjets_tau
    - Sh_Zjets_highpt_emu
    - Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  fillColor: "14002"
  legendLabel: Multijet
  shortName: Multijet
