colorScheme: gemstone_hues

Data:
  add: data
  subtract:

Wjets_emu_Top_Matched:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10002"
  legendLabel: "Sig. W+#it{D}"
  shortName: Wjets_emu_Top_Matched

Wjets_emu_Top_Rest:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10000"
  legendLabel: "Bkg. W+#it{D}"
  shortName: Wjets_emu_Top_Rest

Wjets_emu_Top_Charm:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10001"
  legendLabel: "Top/W w/ Charm."
  shortName: Wjets_emu_Top_Charm

Wjets_emu_Top_HardMisMatched:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10001"
  legendLabel: "Top/W w/ Light."
  shortName: Wjets_emu_Top_Charm

Wjets_emu_Top_NoMatch:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10004"
  legendLabel: "PU #it{D}"
  shortName: Wjets_emu_Top_NoMatch

Wjets_emu_Matched:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
  subtract:
  fillColor: "10002"
  legendLabel: "W+#it{D}"
  shortName: Wjets_light_Matched

Wjets_emu_Charm:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
  subtract:
  fillColor: "10001"
  legendLabel: "W+Charm"
  shortName: Wjets_light_Charm

Wjets_emu_HardMisMatched:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
  subtract:
  fillColor: "10000"
  legendLabel: "W+Light"
  shortName: Wjets_light_HardMisMatched

Wjets_emu_NoMatch:
  add:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_highpt_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D}(PU)"
  shortName: Wjets_light_Matched

Top_Matched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top w/ #it{D}"
  shortName: Top_Matched

Top_Charm:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: "Top w/ Charm"
  shortName: Top_Charm

Top_HardMisMatched:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12000"
  legendLabel: "Top w/ Light"
  shortName: Top_Charm

Top_NoMatch:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12002"
  legendLabel: "Top+#it{D}(PU)"

Wjets_tau:
  add: Sh_Wjets_tau
  subtract:
  fillColor: "10003"
  legendLabel: W#rightarrow#tau#nu

Zjets:
  add:
    - Sh_Zjets_light_emu
    - Sh_Zjets_cjets_emu
    - Sh_Zjets_bjets_emu
    - Sh_Zjets_tau
    - Sh_Zjets_highpt_emu
    - Sh_Zjets_lowmass_emu
  subtract:
  fillColor: "11000"
  legendLabel: Z+jets

Zjets_emu:
  add:
    - Sh_Zjets_light_emu
    - Sh_Zjets_cjets_emu
    - Sh_Zjets_bjets_emu
    - Sh_Zjets_highpt_emu
    - Sh_Zjets_lowmass_emu
  subtract:
  fillColor: "11002"
  legendLabel: Z#rightarrowll

Zjets_tau:
  add: Sh_Zjets_tau
  subtract:
  fillColor: "11003"
  legendLabel: Z#rightarrow#tau#tau

Top:
  add:
    - Top_ttbar
    - Top_single_top
    - Top_ttx
  subtract:
  fillColor: "12001"
  legendLabel: Top

Top_ttbar:
  add: Top_ttbar
  subtract:
  fillColor: "12001"
  legendLabel: t#bar{t}

Top_single_top:
  add: Top_single_top
  subtract:
  fillColor: "12002"
  legendLabel: "single-#it{t}"

Top_ttx:
  add: Top_ttx
  subtract:
  fillColor: "12003"
  legendLabel: t#bar{t}X

Diboson:
  add: Diboson
  subtract:
  fillColor: "13000"
  legendLabel: Diboson

Other:
  add:
    - Diboson
    - Sh_Zjets_tau
    - Sh_Wjets_tau
  subtract:
  fillColor: "13000"
  legendLabel: Other

Multijet:
  add: data
  subtract:
    - Sh_Wjets_light_emu
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_tau
    - Sh_Wjets_highpt_emu
    - Sh_Zjets_light_emu
    - Sh_Zjets_cjets_emu
    - Sh_Zjets_bjets_emu
    - Sh_Zjets_tau
    - Sh_Zjets_highpt_emu
    - Sh_Zjets_lowmass_emu
    - Top_ttbar
    - Top_single_top
    - Top_ttx
    - Diboson
  fillColor: "14002"
  legendLabel: Multijet
  shortName: Multijet
