colorScheme: gemstone_hues

Wjets_emu_Matched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi) OS"
  shortName: Wjets_emu_Matched

Wjets_emu_411MisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11002"
  legendLabel: "W+#it{D}(other) OS"
  shortName: Wjets_emu_411MisMatched

Wjets_emu_Matched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi) OS-SS"
  shortName: Wjets_emu_Matched_OS-SS

Wjets_emu_Matched_OS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi) OS"
  shortName: Wjets_emu_Matched_OS

Wjets_emu_Matched_SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi) SS"
  shortName: Wjets_emu_Matched_SS

Wjets_Rest_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  lineColor: "11002"
  legendLabel: "W+jets OS-SS"
  ignoreTruthMatching:
    - MG_Wjets_tau
  shortName: Wjets_Rest_OS-SS

Wjets_Rest_Loose_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_tau
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+jets OS-SS"
  ignoreTruthMatching:
    - MG_Wjets_tau
  shortName: Wjets_Rest_Loose_OS-SS

Wjets_emu_MisMatched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+c^{mis-match} OS-SS"
  shortName: Wjets_emu_MisMatched_OS-SS

Wjets_emu_MisMatched_Loose_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "21000"
  legendLabel: "Loose W+c^{mis-match} OS-SS"
  shortName: Wjets_emu_MisMatched_Loose_OS-SS

Wjets_emu_411MisMatched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}(other) OS-SS"
  shortName: Wjets_emu_411MisMatched_OS-SS

Wjets_emu_411MisMatched_OS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}(other) OS"
  shortName: Wjets_emu_411MisMatched_OS

Wjets_emu_411MisMatched_SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+#it{D}(other) SS"
  shortName: Wjets_emu_411MisMatched_SS

Wjets_emu_431MisMatched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}_{S} OS-SS"
  shortName: Wjets_emu_431MisMatched_OS-SS

Wjets_emu_431MisMatched_OS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}_{S} OS"
  shortName: Wjets_emu_431MisMatched_OS

Wjets_emu_431MisMatched_SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+#it{D}_{S} SS"
  shortName: Wjets_emu_431MisMatched_SS

Wjets_emu_421MisMatched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}0/#it{D}* OS-SS"
  shortName: Wjets_emu_421MisMatched_OS-SS

Wjets_emu_421MisMatched_OS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}0/#it{D}* OS"
  shortName: Wjets_emu_421MisMatched_OS

Wjets_emu_421MisMatched_SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+#it{D}0/#it{D}* SS"
  shortName: Wjets_emu_421MisMatched_SS

Wjets_emu_BaryonMisMatched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+Baryon OS-SS"
  shortName: Wjets_emu_BaryonMisMatched_OS-SS

Wjets_emu_BaryonMisMatched_OS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+Baryon OS"
  shortName: Wjets_emu_BaryonMisMatched_OS

Wjets_emu_BaryonMisMatched_SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+Baryon SS"
  shortName: Wjets_emu_BaryonMisMatched_SS

Wjets_emu_CharmMisMatched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+Charm OS-SS"
  shortName: Wjets_emu_CharmMisMatched_OS-SS

Wjets_emu_CharmMisMatched_OS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+Charm OS"
  shortName: Wjets_emu_CharmMisMatched_OS

Wjets_emu_CharmMisMatched_SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+Charm SS"
  shortName: Wjets_emu_CharmMisMatched_SS

SPG_DPlus_Matched:
  add:
    - SPG_Dplus
  subtract:
  lineColor: "14004"
  legendLabel: "#it{D}(#it{K}#pi#pi) SPG^{+}"
  shortName: SPG_DPlus_Matched

SPG_DPlus_411MisMatched:
  add:
    - SPG_Dplus
  subtract:
  lineColor: "14004"
  legendLabel: "#it{D}(other) SPG^{+}"
  shortName: SPG_DPlus_411MisMatched

SPG_DPlus_431MisMatched:
  add:
    - SPG_Ds
  subtract:
  lineColor: "14004"
  legendLabel: "#it{D}_{S} SPG^{+}"
  shortName: SPG_DPlus_431MisMatched

SPG_DPlus_421MisMatched:
  add:
    - SPG_D0
  subtract:
  lineColor: "14004"
  legendLabel: "#it{D}0/#it{D}* SPG^{+}"
  shortName: SPG_DPlus_421MisMatched

SPG_DPlus_BaryonMisMatched:
  add:
    - SPG_Baryon
  subtract:
  lineColor: "14004"
  legendLabel: "Baryon SPG^{+}"
  shortName: SPG_DPlus_BaryonMisMatched

SPG_DPlus_CharmMisMatched:
  add:
    - SPG_Ds
    - SPG_D0
    - SPG_Baryon
  subtract:
  lineColor: "14004"
  legendLabel: "Charm SPG^{+}"
  shortName: SPG_DPlus_CharmMisMatched

SPG_DMinus_Matched:
  add:
    - SPG_Dminus
  subtract:
  lineColor: "11004"
  legendLabel: "#it{D}(#it{K}#pi#pi) SPG^{-}"
  shortName: SPG_DMinus_Matched

SPG_DMinus_411MisMatched:
  add:
    - SPG_Dminus
  subtract:
  lineColor: "11004"
  legendLabel: "#it{D}(other) SPG^{-}"
  shortName: SPG_DMinus_411MisMatched

SPG_DMinus_431MisMatched:
  add:
    - SPG_Dsminus
  subtract:
  lineColor: "11004"
  legendLabel: "#it{D}_{S} SPG^{-}"
  shortName: SPG_DMinus_431MisMatched

SPG_DMinus_421MisMatched:
  add:
    - SPG_D0bar
  subtract:
  lineColor: "11004"
  legendLabel: "#it{D}0/#it{D}* SPG^{-}"
  shortName: SPG_DMinus_421MisMatched

SPG_DMinus_BaryonMisMatched:
  add:
    - SPG_Baryonbar
  subtract:
  lineColor: "11004"
  legendLabel: "Anti-Baryon SPG^{-}"
  shortName: SPG_DMinus_BaryonMisMatched

SPG_DMinus_CharmMisMatched:
  add:
    - SPG_Ds
    - SPG_D0
    - SPG_Baryon
  subtract:
  lineColor: "11004"
  legendLabel: "Charm SPG^{-}"
  shortName: SPG_DMinus_CharmMisMatched

SPG_Matched:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}(#it{K}#pi#pi) SPG"
  shortName: SPG_Matched

SPG_411MisMatched:
  add:
    - SPG_Dminus
    - SPG_Dplus
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}(other) SPG"
  shortName: SPG_411MisMatched

SPG_431MisMatched:
  add:
    - SPG_Ds_postProc
    - SPG_Dsminus_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}_{S} SPG"
  shortName: SPG_431MisMatched

SPG_421MisMatched:
  add:
    - SPG_D0_postProc
    - SPG_D0bar_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}0/#it{D}* SPG"
  shortName: SPG_421MisMatched

SPG_BaryonMisMatched:
  add:
    - SPG_Baryon_postProc
    - SPG_Baryonbar_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "Baryon SPG"
  shortName: SPG_BaryonMisMatched

SPG_CharmMisMatched:
  add:
    - SPG_Ds_postProc
    - SPG_D0_postProc
    - SPG_Baryon_postProc
    - SPG_Dsminus_postProc
    - SPG_D0bar_postProc
    - SPG_Baryonbar_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "Charm SPG"
  shortName: SPG_CharmMisMatched

SPG_Matched_Ds:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "12000"
  legendLabel: "Matched"
  shortName: SPG_Matched

SPG_Matched_Dstar:
  add:
    - "D_CharmAnalysis.999918.DstarMinusToDZeroPiMinus"
  subtract:
  fillColor: "12000"
  legendLabel: "Matched"
  shortName: SPG_Matched

SPG_Matched_Ds20:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "11000"
  legendLabel: "Matched"
  shortName: SPG_Matched


SPG_Other_Ds:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "11002"
  legendLabel: "Other"
  shortName: SPG_Other

SPG_431MisMatched_Ds:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "11004"
  legendLabel: "MisMatched"
  shortName: SPG_MisMatched

SPG_411MisMatched_Ds:
  add:
    - "D_CharmAnalysis.999914.DMinus.tree"
  subtract:
  fillColor: "11004"
  legendLabel: "D+ MisMatched"
  shortName: SPG_MisMatched

