colorScheme: gemstone_hues

Wjets_emu_Matched:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "MG W+#it{D}(#it{K}#pi#pi)"
  shortName: Wjets_emu_Matched

Wjets_emu_Matched_OS:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "ROOT.kRed+1"
  legendLabel: "LO MG (OS)"
  shortName: Wjets_emu_Matched_OS

Wjets_emu_Matched_SS:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "ROOT.kBlue+1"
  legendLabel: "LO MG (SS)"
  shortName: Wjets_emu_Matched_SS

Wjets_emu_Matched_OS-SS:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "ROOT.kGreen+1"
  legendLabel: "LO MG (OS-SS)"
  shortName: Wjets_emu_Matched_OS-SS

Wjets_emu_411MisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "MG W+#it{D}(other)"
  shortName: Wjets_emu_411MisMatched

Wjets_emu_431MisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "MG W+#it{D}_{S}"
  shortName: Wjets_emu_431MisMatched

Wjets_emu_421MisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "MG W+#it{D}0/#it{D}*"
  shortName: Wjets_emu_421MisMatched

Wjets_emu_BaryonMisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "MG W+Baryon"
  shortName: Wjets_emu_BaryonMisMatched

Wjets_emu_CharmMisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "MG W+Charm"
  shortName: Wjets_emu_CharmMisMatched

Wjets_emu_411MisMatched_OS-SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}(other) OS-SS"
  shortName: Wjets_emu_411MisMatched_OS-SS

Wjets_emu_411MisMatched_OS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}(other) OS"
  shortName: Wjets_emu_411MisMatched_OS

Wjets_emu_411MisMatched_SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+#it{D}(other) SS"
  shortName: Wjets_emu_411MisMatched_SS

Wjets_emu_431MisMatched_OS-SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}_{S} OS-SS"
  shortName: Wjets_emu_431MisMatched_OS-SS

Wjets_emu_431MisMatched_OS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}_{S} OS"
  shortName: Wjets_emu_431MisMatched_OS

Wjets_emu_431MisMatched_SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+#it{D}_{S} SS"
  shortName: Wjets_emu_431MisMatched_SS

Wjets_emu_421MisMatched_OS-SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}0/#it{D}* OS-SS"
  shortName: Wjets_emu_421MisMatched_OS-SS

Wjets_emu_421MisMatched_OS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}0/#it{D}* OS"
  shortName: Wjets_emu_421MisMatched_OS

Wjets_emu_421MisMatched_SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+#it{D}0/#it{D}* SS"
  shortName: Wjets_emu_421MisMatched_SS

Wjets_emu_BaryonMisMatched_OS-SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+Baryon OS-SS"
  shortName: Wjets_emu_BaryonMisMatched_OS-SS

Wjets_emu_BaryonMisMatched_OS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+Baryon OS"
  shortName: Wjets_emu_BaryonMisMatched_OS

Wjets_emu_BaryonMisMatched_SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+Baryon SS"
  shortName: Wjets_emu_BaryonMisMatched_SS

Wjets_emu_CharmMisMatched_OS-SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+Charm OS-SS"
  shortName: Wjets_emu_CharmMisMatched_OS-SS

Wjets_emu_CharmMisMatched_OS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+Charm OS"
  shortName: Wjets_emu_CharmMisMatched_OS

Wjets_emu_CharmMisMatched_SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "14004"
  legendLabel: "W+Charm SS"
  shortName: Wjets_emu_CharmMisMatched_SS

SPG_Matched:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}(#it{K}#pi#pi) SPG"
  shortName: SPG_Matched

SPG_411MisMatched:
  add:
    - SPG_Dminus_postProc
    - SPG_Dplus_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}(other) SPG"
  shortName: SPG_411MisMatched

SPG_431MisMatched:
  add:
    - SPG_Ds_postProc
    - SPG_Dsminus_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}_{S} SPG"
  shortName: SPG_431MisMatched

SPG_421MisMatched:
  add:
    - SPG_D0_Dstar_postProc
    - SPG_D0_Dstar_bar_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "#it{D}0/#it{D}* SPG"
  shortName: SPG_421MisMatched

SPG_BaryonMisMatched:
  add:
    - SPG_Baryon_postProc
    - SPG_Baryonbar_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "Baryon SPG"
  shortName: SPG_BaryonMisMatched

SPG_CharmMisMatched:
  add:
    - SPG_Dminus_postProc
    - SPG_Dplus_postProc
    - SPG_Ds_postProc
    - SPG_D0_Dstar_postProc
    - SPG_Baryon_postProc
    - SPG_Dsminus_postProc
    - SPG_D0_Dstar_bar_postProc
    - SPG_Baryonbar_postProc
  subtract:
  lineColor: "21000"
  legendLabel: "Charm SPG"
  shortName: SPG_CharmMisMatched

Wjets_emu_Matched_truth_pt_bin1:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D} (bin 1)"
  shortName: Wjets_emu_Matched_truth_pt_bin1

Wjets_emu_Matched_truth_pt_bin2:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D} (bin 2)"
  shortName: Wjets_emu_Matched_truth_pt_bin2

Wjets_emu_Matched_truth_pt_bin3:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D} (bin 3)"
  shortName: Wjets_emu_Matched_truth_pt_bin3

Wjets_emu_Matched_truth_pt_bin4:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D} (bin 4)"
  shortName: Wjets_emu_Matched_truth_pt_bin4

Wjets_emu_Matched_truth_pt_bin5:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "10004"
  legendLabel: "W+#it{D} (bin 5)"
  shortName: Wjets_emu_Matched_truth_pt_bin5

SPG_Matched_truth_pt_bin1:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 1)"
  shortName: SPG_Matched_truth_pt_bin1

SPG_Matched_truth_pt_bin2:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 2)"
  shortName: SPG_Matched_truth_pt_bin2

SPG_Matched_truth_pt_bin3:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 3)"
  shortName: SPG_Matched_truth_pt_bin3

SPG_Matched_truth_pt_bin4:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 4)"
  shortName: SPG_Matched_truth_pt_bin4

SPG_Matched_truth_pt_bin5:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "21000"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 5)"
  shortName: SPG_Matched_truth_pt_bin5

Sh2211_Wjets_emu_Matched:
  add:
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh2.2.11"
  shortName: Sh2211_Wjets_emu_Matched

MGPy8EG_NLO_WplusD:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "NLO MG W+D"
  shortName: MGPy8EG_NLO_WplusD

Sherpa2211_WplusD:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh.2.11 W+D"
  shortName: Sherpa2211_WplusD

Sherpa2211_WplusD_OS:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh.2.11 W+D (OS)"
  shortName: Sherpa2211_WplusD_OS

Sherpa2211_WplusD_SS:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh.2.11 W+D (SS)"
  shortName: Sherpa2211_WplusD_SS

Sherpa2211_WplusD_OS-SS:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh.2.11 W+D (OS-SS)"
  shortName: Sherpa2211_WplusD_OS-SS

Sherpa2211_WplusD_Matched_truth_pt_bin1:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh.2.11 W+D (bin 1)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin1

Sherpa2211_WplusD_Matched_truth_pt_bin2:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh.2.11 W+D (bin 2)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin2

Sherpa2211_WplusD_Matched_truth_pt_bin3:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh.2.11 W+D (bin 3)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin3

Sherpa2211_WplusD_Matched_truth_pt_bin4:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh.2.11 W+D (bin 4)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin4

Sherpa2211_WplusD_Matched_truth_pt_bin5:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh.2.11 W+D (bin 5)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin5
