colorScheme: gemstone_hues

MG_Wjets_Matched:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "21000"
  legendLabel: "MG W+#it{D}(#it{K}#pi#pi)"
  shortName: MG_Wjets_Matched

MG_Wjets_411MisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "MG W+#it{D}(other)"
  shortName: MG_Wjets_411MisMatched

MG_Wjets_431MisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "MG W+#it{D}_{S}"
  shortName: MG_Wjets_431MisMatched

MG_Wjets_421MisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "MG W+#it{D}0/#it{D}*"
  shortName: MG_Wjets_421MisMatched

MG_Wjets_BaryonMisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "MG W+Baryon"
  shortName: MG_Wjets_BaryonMisMatched

MG_Wjets_CharmMisMatched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "MG W+Charm"
  shortName: MG_Wjets_CharmMisMatched

SPG_Matched:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "#it{D}(#it{K}#pi#pi) SPG"
  shortName: SPG_Matched

SPG_411MisMatched:
  add:
    - SPG_Dminus_postProc
    - SPG_Dplus_postProc
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "#it{D}(other) SPG"
  shortName: SPG_411MisMatched

SPG_431MisMatched:
  add:
    - SPG_Ds_postProc
    - SPG_Dsminus_postProc
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "#it{D}_{S} SPG"
  shortName: SPG_431MisMatched

SPG_421MisMatched:
  add:
    - SPG_D0_Dstar_postProc
    - SPG_D0_Dstar_bar_postProc
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "#it{D}0/#it{D}* SPG"
  shortName: SPG_421MisMatched

SPG_BaryonMisMatched:
  add:
    - SPG_Baryon_postProc
    - SPG_Baryonbar_postProc
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Baryon SPG"
  shortName: SPG_BaryonMisMatched

SPG_CharmMisMatched:
  add:
    - SPG_Dminus_postProc
    - SPG_Dplus_postProc
    - SPG_Ds_postProc
    - SPG_D0_Dstar_postProc
    - SPG_Baryon_postProc
    - SPG_Dsminus_postProc
    - SPG_D0_Dstar_bar_postProc
    - SPG_Baryonbar_postProc
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Charm SPG"
  shortName: SPG_CharmMisMatched

MG_Wjets_Matched_truth_pt_bin1:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "21000"
  legendLabel: "W+#it{D} (bin 1)"
  shortName: MG_Wjets_Matched_truth_pt_bin1

MG_Wjets_Matched_truth_pt_bin2:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "21000"
  legendLabel: "W+#it{D} (bin 2)"
  shortName: MG_Wjets_Matched_truth_pt_bin2

MG_Wjets_Matched_truth_pt_bin3:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "21000"
  legendLabel: "W+#it{D} (bin 3)"
  shortName: MG_Wjets_Matched_truth_pt_bin3

MG_Wjets_Matched_truth_pt_bin4:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "21000"
  legendLabel: "W+#it{D} (bin 4)"
  shortName: MG_Wjets_Matched_truth_pt_bin4

MG_Wjets_Matched_truth_pt_bin5:
  add:
    # - MG_Wjets_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  fillColor: "21000"
  legendLabel: "W+#it{D} (bin 5)"
  shortName: MG_Wjets_Matched_truth_pt_bin5

SPG_Matched_truth_pt_bin1:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 1)"
  shortName: SPG_Matched_truth_pt_bin1

SPG_Matched_truth_pt_bin2:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 2)"
  shortName: SPG_Matched_truth_pt_bin2

SPG_Matched_truth_pt_bin3:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 3)"
  shortName: SPG_Matched_truth_pt_bin3

SPG_Matched_truth_pt_bin4:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 4)"
  shortName: SPG_Matched_truth_pt_bin4

SPG_Matched_truth_pt_bin5:
  add:
    - SPG_Dplus
    - SPG_Dminus
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "SPG #it{D}(#it{K}#pi#pi) (bin 5)"
  shortName: SPG_Matched_truth_pt_bin5

MGPy8EG_NLO_WplusD_Matched:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D"
  shortName: MGPy8EG_NLO_WplusD_Matched

MGPy8EG_NLO_WplusD_Matched_truth_pt_bin1:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D (bin 1)"
  shortName: MGPy8EG_NLO_WplusD_Matched_truth_pt_bin1

MGPy8EG_NLO_WplusD_Matched_truth_pt_bin2:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D (bin 2)"
  shortName: MGPy8EG_NLO_WplusD_Matched_truth_pt_bin2

MGPy8EG_NLO_WplusD_Matched_truth_pt_bin3:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D (bin 3)"
  shortName: MGPy8EG_NLO_WplusD_Matched_truth_pt_bin3

MGPy8EG_NLO_WplusD_Matched_truth_pt_bin4:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D (bin 4)"
  shortName: MGPy8EG_NLO_WplusD_Matched_truth_pt_bin4

MGPy8EG_NLO_WplusD_Matched_truth_pt_bin5:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D (bin 5)"
  shortName: MGPy8EG_NLO_WplusD_Matched_truth_pt_bin5 

Sherpa2211_WplusD_Matched:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh (MG Shape)"
  shortName: Sherpa2211_WplusD_Matched

Sherpa2211_WplusD_Matched_truth_pt_bin1:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh, MG Shape (bin 1)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin1

Sherpa2211_WplusD_Matched_truth_pt_bin2:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh, MG Shape (bin 2)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin2

Sherpa2211_WplusD_Matched_truth_pt_bin3:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh, MG Shape (bin 3)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin3

Sherpa2211_WplusD_Matched_truth_pt_bin4:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh, MG Shape (bin 4)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin4

Sherpa2211_WplusD_Matched_truth_pt_bin5:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh, MG Shape (bin 5)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin5

Sherpa2211_WplusD_Matched_Plain:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+D"
  shortName: Sherpa2211_WplusD_Matched_Plain

Sherpa2211_WplusD_Matched_truth_pt_bin1_Plain:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+D (bin 1)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin1_Plain

Sherpa2211_WplusD_Matched_truth_pt_bin2_Plain:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+D (bin 2)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin2_Plain

Sherpa2211_WplusD_Matched_truth_pt_bin3_Plain:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+D (bin 3)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin3_Plain

Sherpa2211_WplusD_Matched_truth_pt_bin4_Plain:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+D (bin 4)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin4_Plain

Sherpa2211_WplusD_Matched_truth_pt_bin5_Plain:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+D (bin 5)"
  shortName: Sherpa2211_WplusD_Matched_truth_pt_bin5_Plain



Sherpa2211_Wjets:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+jets"
  shortName: Sherpa2211_Wjets

Sherpa2211_Wjets_truth_pt_bin1:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+jets (bin 1)"
  shortName: Sherpa2211_Wjets_truth_pt_bin1

Sherpa2211_Wjets_truth_pt_bin2:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+jets (bin 2)"
  shortName: Sherpa2211_Wjets_truth_pt_bin2

Sherpa2211_Wjets_truth_pt_bin3:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+jets (bin 3)"
  shortName: Sherpa2211_Wjets_truth_pt_bin3

Sherpa2211_Wjets_truth_pt_bin4:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+jets (bin 4)"
  shortName: Sherpa2211_Wjets_truth_pt_bin4

Sherpa2211_Wjets_truth_pt_bin5:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+jets (bin 5)"
  shortName: Sherpa2211_Wjets_truth_pt_bin5

Sherpa2211_Wjets_411MisMatched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh W+#it{D}(other)"
  shortName: Sherpa2211_Wjets_411MisMatched

Sherpa2211_Wjets_421MisMatched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh W+#it{D}0/#it{D}*"
  shortName: Sherpa2211_Wjets_421MisMatched

Sherpa2211_Wjets_431MisMatched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh W+#it{D}_{S}"
  shortName: Sherpa2211_Wjets_421MisMatched

Sherpa2211_Wjets_BaryonMisMatched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh W+Baryon"
  shortName: Sherpa2211_Wjets_BaryonMisMatched

Sherpa2211_Wjets_CharmMisMatched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
    - Sh_2211_Wjets_tau
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh W+Charm"
  shortName: Sherpa2211_Wjets_CharmMisMatched

Sherpa2211_WplusD_Matched_Fit:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kGray+2"
  legendLabel: "Sh (Fit)"
  shortName: Sherpa2211_WplusD_Matched_Fit
  statError: False

Sherpa2211_WplusD_Matched_Fit_up:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sh (Fit +1 #sigma)"
  shortName: Sherpa2211_WplusD_Matched_Fit_up
  statError: False

Sherpa2211_WplusD_Matched_Fit_dn:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh (Fit -1 #sigma)"
  shortName: Sherpa2211_WplusD_Matched_Fit_dn
  statError: False

Matched_Fit:
  add:
    - DplusMassFit
  subtract:
  lineColor: "ROOT.kGray"
  legendLabel: "fit"
  shortName: Matched_Fit
  statError: False

Matched_Fit_up:
  add:
    - DplusMassFit
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "fit"
  shortName: Matched_Fit_up
  statError: False

Matched_Fit_dn:
  add:
    - DplusMassFit
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "fit"
  shortName: Matched_Fit_dn
  statError: False
