colorScheme: gemstone_hues

Wjets_emu_Matched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi) OS"
  shortName: Wjets_emu_Matched

Wjets_emu_Matched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "W+#it{D}(#it{K}#pi#pi) OS-SS"
  shortName: Wjets_emu_Matched_OS-SS

Wjets_emu_411MisMatched:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "11002"
  legendLabel: "W+#it{D}(other) OS"
  shortName: Wjets_emu_411MisMatched

Wjets_emu_411MisMatched_OS-SS:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10002"
  legendLabel: "W+#it{D}(other) OS-SS"
  shortName: Wjets_emu_411MisMatched_OS-SS

SPG_DPlus_Matched:
  add:
    - SPG_Dplus
  subtract:
  lineColor: "14004"
  legendLabel: "#it{D}(#it{K}#pi#pi) SPG"
  shortName: SPG_DPlus_Matched

SPG_DPlus_411MisMatched:
  add:
    - SPG_Dplus
  subtract:
  lineColor: "14002"
  legendLabel: "#it{D}(other) SPG"
  shortName: SPG_DPlus_411MisMatched

SPG_Matched:
  add:
    - "D_CharmAnalysis.999914.DMinus"
  subtract:
  fillColor: "11000"
  legendLabel: "SPG"
  shortName: SPG_Matched

SPG_Matched_Ds:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "12000"
  legendLabel: "Matched"
  shortName: SPG_Matched

SPG_Matched_Dstar:
  add:
    - "D_CharmAnalysis.999918.DstarMinusToDZeroPiMinus"
  subtract:
  fillColor: "12000"
  legendLabel: "Matched"
  shortName: SPG_Matched

SPG_Matched_Ds20:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "11000"
  legendLabel: "Matched"
  shortName: SPG_Matched


SPG_Other_Ds:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "11002"
  legendLabel: "Other"
  shortName: SPG_Other

SPG_431MisMatched_Ds:
  add:
    - "D_CharmAnalysis.999912.DsMinus.tree"
  subtract:
  fillColor: "11004"
  legendLabel: "MisMatched"
  shortName: SPG_MisMatched

SPG_411MisMatched_Ds:
  add:
    - "D_CharmAnalysis.999914.DMinus.tree"
  subtract:
  fillColor: "11004"
  legendLabel: "D+ MisMatched"
  shortName: SPG_MisMatched

