colorScheme: gemstone_hues

Wplus:
  add:
    - MG_Wjets_cjets_emu
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "W^{+} + jets"
  shortName: Wplus

Wminus:
  add:
    - MG_Wjets_cjets_emu
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "W^{-} + jets"
  shortName: Wminus

WPlusD_OS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "W + D (OS)"
  shortName: WPlusD_OS

WPlusD_SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "W + D (SS)"
  shortName: WPlusD_SS

WPlusD_OS_minus_SS:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "W + D (OS-SS)"
  shortName: WPlusD_OSSS
