colorScheme: gemstone_hues

MG_Wjets_emu_Matched:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "LO MG"
  shortName: MG_Wjets_emu_Matched

Powheg_Wjets_emu_Matched:
  add:
    - Ph_Wjets_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "LO Powheg"
  shortName: Powheg_Wjets_emu_Matched

Sherpa_Wjets_emu_Matched:
  add:
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_light_emu
    - Sh_Wjets_highpt_emu
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sherpa2.2.1"
  shortName: Sherpa_Wjets_emu_Matched

MGFxFx_Wjets_emu_Matched:
  add:
    - MG_FxFx_Wjets_emu
  subtract:
  lineColor: "15002"
  legendLabel: "MG FxFx"
  shortName: MGFxFx_Wjets_emu_Matched

Sherpa2210_Wjets_emu_Matched:
  add:
    - Sh_2210_Wjets_cjets_emu
    - Sh_2210_Wjets_bjets_emu
    - Sh_2210_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa2.2.10"
  shortName: Sherpa2210_Wjets_emu_Matched
