colorScheme: gemstone_hues

MG_Wjets_emu_Rest_el_minus:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10001"
  legendLabel: "MG W+jets e-"
  shortName: MG_Wjets_emu_Rest

MG_Wjets_emu_Rest_el_plus:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "MG W+jets e+"
  shortName: MG_Wjets_emu_Rest

MG_Wjets_emu_Rest_mu_minus:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14001"
  legendLabel: "MG W+jets #mu-"
  shortName: MG_Wjets_emu_Rest

MG_Wjets_emu_Rest_mu_plus:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "MG W+jets #mu+"
  shortName: MG_Wjets_emu_Rest

Wjets_light_emu_Rest:
  add:
    - MG_Wjets_light_emu
  subtract:
  lineColor: "10001"
  legendLabel: "MG W+u"
  shortName: Wjets_light_emu_Rest

Wjets_cjets_emu_Rest:
  add:
    - MG_Wjets_cjets_emu
  subtract:
  lineColor: "10002"
  legendLabel: "MG W+c"
  shortName: Wjets_cjets_emu_Rest

Wjets_bujets_emu_Rest:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "12002"
  legendLabel: "MG W+b/u"
  shortName: Wjets_bujets_emu_Rest

Wjets_bjets_emu_Rest:
  add:
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "12001"
  legendLabel: "MG W+b"
  shortName: Wjets_bjets_emu_Rest

Wjets_bujets_emu_Rest_SR:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "13002"
  legendLabel: "W+b/u"
  shortName: Wjets_bujets_emu_Rest_SR

Wjets_bujets_emu_Rest_LooseSR:
  add:
    - MG_Wjets_light_emu
    - MG_Wjets_bjets_emu
  subtract:
  lineColor: "13003"
  legendLabel: "W+b/u Loose"
  shortName: Wjets_bujets_emu_Rest_LooseSR

Wjets_cjets_emu_Rest_SR:
  add:
    - MG_Wjets_cjets_emu
  subtract:
  lineColor: "10002"
  legendLabel: "W+c"
  shortName: Wjets_cjets_emu_Rest_SR

Wjets_cjets_emu_Rest_LooseSR:
  add:
    - MG_Wjets_cjets_emu
  subtract:
  lineColor: "10003"
  legendLabel: "W+c Loose"
  shortName: Wjets_cjets_emu_Rest_LooseSR

Multijet_MatrixMethod:
  add: data
  subtract:
  lineColor: "14003"
  legendLabel: "Multijet MM"
  shortName: Multijet_MatrixMethod

Multijet_MatrixMethod_FF:
  add:
    - data_FF
    - MC
  subtract:
  lineColor: "10003"
  legendLabel: "Multijet FF"
  shortName: Multijet_MatrixMethod_FF

STDM13_Wjets_emu_Matched:
  add:
    - STDM13_MG_Wjets_light_emu
    - STDM13_MG_Wjets_cjets_emu
    - STDM13_MG_Wjets_bjets_emu
  subtract:
  lineColor: "10004"
  legendLabel: "STDM13 W+#it{D}(#it{K}#pi#pi)"
  shortName: STDM13_Wjets_emu_Matched

STDM13_Wjets_emu_411MisMatched:
  add:
    - STDM13_MG_Wjets_light_emu
    - STDM13_MG_Wjets_cjets_emu
    - STDM13_MG_Wjets_bjets_emu
  subtract:
  lineColor: "10002"
  legendLabel: "STDM13 W+#it{D}(other)"
  shortName: STDM13_Wjets_emu_411MisMatched

FTAG4_Wjets_emu_Matched:
  add:
    - FTAG4_MG_Wjets_light_emu
    - FTAG4_MG_Wjets_cjets_emu
    - FTAG4_MG_Wjets_bjets_emu
  subtract:
  lineColor: "14004"
  legendLabel: "FTAG4 W+#it{D}(#it{K}#pi#pi)"
  shortName: FTAG4_Wjets_emu_Matched

FTAG4_Wjets_emu_411MisMatched:
  add:
    - FTAG4_MG_Wjets_light_emu
    - FTAG4_MG_Wjets_cjets_emu
    - FTAG4_MG_Wjets_bjets_emu
  subtract:
  lineColor: "14002"
  legendLabel: "FTAG4 W+#it{D}(other)"
  shortName: FTAG4_Wjets_emu_411MisMatched
