colorScheme: gemstone_hues

MG_Wjets_emu_Matched:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "21000"
  legendLabel: "LO MG"
  shortName: MG_Wjets_emu_Matched

Powheg_Wjets_emu_Matched:
  add:
    - Ph_Wjets_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "LO Powheg"
  shortName: Powheg_Wjets_emu_Matched

Sherpa_Wjets_emu_Matched:
  add:
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_light_emu
    - Sh_Wjets_highpt_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sherpa2.2.1"
  shortName: Sherpa_Wjets_emu_Matched

MGFxFx_Wjets_emu_Matched:
  add:
    - MG_FxFx_Wjets_emu
  subtract:
  lineColor: "15002"
  legendLabel: "MG FxFx"
  shortName: MGFxFx_Wjets_emu_Matched

Sherpa2210_Wjets_emu_Matched:
  add:
    - Sh_2210_Wjets_cjets_emu
    - Sh_2210_Wjets_bjets_emu
    - Sh_2210_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa2.2.10"
  shortName: Sherpa2210_Wjets_emu_Matched

Sherpa2211_Wjets_emu_Matched:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sherpa2.2.11"
  shortName: Sherpa2211_Wjets_emu_Matched

Sherpa2211_WplusD:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh.2.11 W+D"
  scaleMC: 0.092
  shortName: Sherpa2211_WplusD

Sherpa2211_Wjets:
  add:
    - Sh_2211_Wjets_cjets_emu
    - Sh_2211_Wjets_bjets_emu
    - Sh_2211_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh.2.11 W+jets"
  shortName: Sherpa2211_Wjets

MGPy8EG_NLO_WplusD:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D"
  scaleMC: 0.092
  shortName: MGPy8EG_NLO_WplusD

MGPy8EG_NLO_WplusD_rw:
  add:
    - MG_NLO_WplusD_rw
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "NLO MG W+D (rw)"
  shortName: MGPy8EG_NLO_WplusD_rw

MG_NLO_WplusD_Dstar:
  add:
    - MG_NLO_WplusD_Dstar
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D (D*)"
  shortName: MG_NLO_WplusD_Dstar

MG_NLO_WplusD_prompt:
  add:
    - MG_NLO_WplusD_prompt
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "NLO MG W+D"
  shortName: MG_NLO_WplusD_prompt

Sherpa2211_WplusD_Loose:
  add:
    - Sh_2211_WplusD
  subtract:
  lineColor: "ROOT.kBlue+2"
  legendLabel: "Sh.2.11 W+D Loose"
  scaleMC: 0.092
  shortName: Sherpa2211_WplusD_Loose

MGPy8EG_NLO_WplusD_Loose:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed+2"
  legendLabel: "NLO MG W+D Loose"
  scaleMC: 0.092
  shortName: MGPy8EG_NLO_WplusD_Loose

MG_Wjets_emu_Matched_Loose:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "ROOT.kGray+2"
  legendLabel: "LO MG Loose"
  shortName: MG_Wjets_emu_Matched_Loose

Sherpa_Wjets_emu_Matched_Loose:
  add:
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_light_emu
    - Sh_Wjets_highpt_emu
  subtract:
  lineColor: "ROOT.kGreen+2"
  legendLabel: "Sherpa2.2.1"
  shortName: Sherpa_Wjets_emu_Matched_Loose
