colorScheme: gemstone_hues

MG_Wjets:
  add:
    - MG_Wjets_emu
  subtract:
  lineColor: "21000"
  legendLabel: "LO MG W+jets"
  shortName: MG_Wjets

Powheg_Wjets:
  add:
    - Ph_Wjets_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Powheg"
  shortName: Ph_Wjets_emu

Sherpa_Wjets:
  add:
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_light_emu
    - Sh_Wjets_highpt_emu
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sherpa2.2.1"
  shortName: Sherpa_Wjets

Sherpa2210_Wjets:
  add:
    - Sh_2210_Wjets_cjets_emu
    - Sh_2210_Wjets_bjets_emu
    - Sh_2210_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa2.2.10"
  shortName: Sherpa2210_Wjets

MGFxFx_Wjets:
  add:
    - MG_FxFx_Wjets_cjets_emu
    - MG_FxFx_Wjets_bjets_emu
    - MG_FxFx_Wjets_light_emu
  subtract:
  lineColor: "15002"
  legendLabel: "FxFx W+jets"
  shortName: MGFxFx_Wjets

MGPy8EG_FxFx_WplusD_Matched:
  add:
    - MG_FxFx_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "FxFx W+D"
  shortName: MGPy8EG_FxFx_WplusD_Matched

Sherpa2211_WplusD_Matched:
  add:
    - Sh_WplusD
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "Sh2.2.11 W+D"
  shortName: Sherpa2211_WplusD_Matched

Sherpa2211_Wjets:
  add:
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Sh2.2.11 W+jets"
  shortName: Sherpa2211_Wjets

MGPy8EG_NLO_WplusD:
  add:
    - MG_NLO_WplusD
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "NLO MG W+D"
  shortName: MGPy8EG_NLO_WplusD
