colorScheme: gemstone_hues

MG_Wjets:
  add:
    - MG_Wjets_cjets_emu
    - MG_Wjets_bjets_emu
    - MG_Wjets_light_emu
  subtract:
  lineColor: "ROOT.kBlue"
  legendLabel: "MG W+#it{D}"
  shortName: MG_Wjets

Powheg_Wjets:
  add:
    - Ph_Wjets_emu
  subtract:
  lineColor: "ROOT.kGreen"
  legendLabel: "Powheg W+#it{D}"
  shortName: Ph_Wjets_emu

Sherpa_Wjets:
  add:
    - Sh_Wjets_cjets_emu
    - Sh_Wjets_bjets_emu
    - Sh_Wjets_light_emu
    - Sh_Wjets_highpt_emu
  subtract:
  lineColor: "ROOT.kRed"
  legendLabel: "Sherpa2.2.1 W+#it{D}"
  shortName: Sherpa_Wjets

Sherpa2210_Wjets:
  add:
    - Sh_2210_Wjets_cjets_emu
    - Sh_2210_Wjets_bjets_emu
    - Sh_2210_Wjets_light_emu
  subtract:
  lineColor: "21000"
  legendLabel: "Sherpa2.2.10 W+#it{D}"
  shortName: Sherpa2210_Wjets

MGFxFx_Wjets:
  add:
    - MG_FxFx_Wjets_emu
  subtract:
  lineColor: "15002"
  legendLabel: "MG FxFx W+#it{D}"
  shortName: MGFxFx_Wjets
